import { createApp } from 'vue'
import { createPinia } from 'pinia'
import { createI18n } from 'vue-i18n'
import Harness from './Harness.vue'
import settings from '@/core/i18n/locales/zh/admin/settings'
import dashboard from '@/core/i18n/locales/zh/dashboard'
import misc from '@/core/i18n/locales/zh/misc'
import common from '@/core/i18n/locales/zh/common'
import '@/core/themes/style.css'
createApp(Harness).use(createPinia()).use(createI18n({legacy:false,locale:'zh',messages:{zh:{...common,...dashboard,...misc,admin:settings}}})).mount('#app')
