// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/accountegressbinding"
	"github.com/Wei-Shaw/sub2api/ent/ipv6egresspool"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AccountEgressBindingUpdate is the builder for updating AccountEgressBinding entities.
type AccountEgressBindingUpdate struct {
	config
	hooks    []Hook
	mutation *AccountEgressBindingMutation
}

// Where appends a list predicates to the AccountEgressBindingUpdate builder.
func (_u *AccountEgressBindingUpdate) Where(ps ...predicate.AccountEgressBinding) *AccountEgressBindingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccountEgressBindingUpdate) SetUpdatedAt(v time.Time) *AccountEgressBindingUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *AccountEgressBindingUpdate) SetAccountID(v int64) *AccountEgressBindingUpdate {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *AccountEgressBindingUpdate) SetNillableAccountID(v *int64) *AccountEgressBindingUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetPoolID sets the "pool_id" field.
func (_u *AccountEgressBindingUpdate) SetPoolID(v int64) *AccountEgressBindingUpdate {
	_u.mutation.SetPoolID(v)
	return _u
}

// SetNillablePoolID sets the "pool_id" field if the given value is not nil.
func (_u *AccountEgressBindingUpdate) SetNillablePoolID(v *int64) *AccountEgressBindingUpdate {
	if v != nil {
		_u.SetPoolID(*v)
	}
	return _u
}

// SetSourceIpv6 sets the "source_ipv6" field.
func (_u *AccountEgressBindingUpdate) SetSourceIpv6(v string) *AccountEgressBindingUpdate {
	_u.mutation.SetSourceIpv6(v)
	return _u
}

// SetNillableSourceIpv6 sets the "source_ipv6" field if the given value is not nil.
func (_u *AccountEgressBindingUpdate) SetNillableSourceIpv6(v *string) *AccountEgressBindingUpdate {
	if v != nil {
		_u.SetSourceIpv6(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *AccountEgressBindingUpdate) SetStatus(v string) *AccountEgressBindingUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AccountEgressBindingUpdate) SetNillableStatus(v *string) *AccountEgressBindingUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *AccountEgressBindingUpdate) SetVersion(v int64) *AccountEgressBindingUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *AccountEgressBindingUpdate) SetNillableVersion(v *int64) *AccountEgressBindingUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *AccountEgressBindingUpdate) AddVersion(v int64) *AccountEgressBindingUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetRotatedAt sets the "rotated_at" field.
func (_u *AccountEgressBindingUpdate) SetRotatedAt(v time.Time) *AccountEgressBindingUpdate {
	_u.mutation.SetRotatedAt(v)
	return _u
}

// SetNillableRotatedAt sets the "rotated_at" field if the given value is not nil.
func (_u *AccountEgressBindingUpdate) SetNillableRotatedAt(v *time.Time) *AccountEgressBindingUpdate {
	if v != nil {
		_u.SetRotatedAt(*v)
	}
	return _u
}

// ClearRotatedAt clears the value of the "rotated_at" field.
func (_u *AccountEgressBindingUpdate) ClearRotatedAt() *AccountEgressBindingUpdate {
	_u.mutation.ClearRotatedAt()
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *AccountEgressBindingUpdate) SetAccount(v *Account) *AccountEgressBindingUpdate {
	return _u.SetAccountID(v.ID)
}

// SetPool sets the "pool" edge to the IPv6EgressPool entity.
func (_u *AccountEgressBindingUpdate) SetPool(v *IPv6EgressPool) *AccountEgressBindingUpdate {
	return _u.SetPoolID(v.ID)
}

// Mutation returns the AccountEgressBindingMutation object of the builder.
func (_u *AccountEgressBindingUpdate) Mutation() *AccountEgressBindingMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *AccountEgressBindingUpdate) ClearAccount() *AccountEgressBindingUpdate {
	_u.mutation.ClearAccount()
	return _u
}

// ClearPool clears the "pool" edge to the IPv6EgressPool entity.
func (_u *AccountEgressBindingUpdate) ClearPool() *AccountEgressBindingUpdate {
	_u.mutation.ClearPool()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AccountEgressBindingUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountEgressBindingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AccountEgressBindingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountEgressBindingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccountEgressBindingUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := accountegressbinding.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountEgressBindingUpdate) check() error {
	if v, ok := _u.mutation.SourceIpv6(); ok {
		if err := accountegressbinding.SourceIpv6Validator(v); err != nil {
			return &ValidationError{Name: "source_ipv6", err: fmt.Errorf(`ent: validator failed for field "AccountEgressBinding.source_ipv6": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := accountegressbinding.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AccountEgressBinding.status": %w`, err)}
		}
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AccountEgressBinding.account"`)
	}
	if _u.mutation.PoolCleared() && len(_u.mutation.PoolIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AccountEgressBinding.pool"`)
	}
	return nil
}

func (_u *AccountEgressBindingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accountegressbinding.Table, accountegressbinding.Columns, sqlgraph.NewFieldSpec(accountegressbinding.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(accountegressbinding.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SourceIpv6(); ok {
		_spec.SetField(accountegressbinding.FieldSourceIpv6, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(accountegressbinding.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(accountegressbinding.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(accountegressbinding.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RotatedAt(); ok {
		_spec.SetField(accountegressbinding.FieldRotatedAt, field.TypeTime, value)
	}
	if _u.mutation.RotatedAtCleared() {
		_spec.ClearField(accountegressbinding.FieldRotatedAt, field.TypeTime)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   accountegressbinding.AccountTable,
			Columns: []string{accountegressbinding.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   accountegressbinding.AccountTable,
			Columns: []string{accountegressbinding.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PoolCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accountegressbinding.PoolTable,
			Columns: []string{accountegressbinding.PoolColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ipv6egresspool.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PoolIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accountegressbinding.PoolTable,
			Columns: []string{accountegressbinding.PoolColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ipv6egresspool.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountegressbinding.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AccountEgressBindingUpdateOne is the builder for updating a single AccountEgressBinding entity.
type AccountEgressBindingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccountEgressBindingMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccountEgressBindingUpdateOne) SetUpdatedAt(v time.Time) *AccountEgressBindingUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *AccountEgressBindingUpdateOne) SetAccountID(v int64) *AccountEgressBindingUpdateOne {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *AccountEgressBindingUpdateOne) SetNillableAccountID(v *int64) *AccountEgressBindingUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetPoolID sets the "pool_id" field.
func (_u *AccountEgressBindingUpdateOne) SetPoolID(v int64) *AccountEgressBindingUpdateOne {
	_u.mutation.SetPoolID(v)
	return _u
}

// SetNillablePoolID sets the "pool_id" field if the given value is not nil.
func (_u *AccountEgressBindingUpdateOne) SetNillablePoolID(v *int64) *AccountEgressBindingUpdateOne {
	if v != nil {
		_u.SetPoolID(*v)
	}
	return _u
}

// SetSourceIpv6 sets the "source_ipv6" field.
func (_u *AccountEgressBindingUpdateOne) SetSourceIpv6(v string) *AccountEgressBindingUpdateOne {
	_u.mutation.SetSourceIpv6(v)
	return _u
}

// SetNillableSourceIpv6 sets the "source_ipv6" field if the given value is not nil.
func (_u *AccountEgressBindingUpdateOne) SetNillableSourceIpv6(v *string) *AccountEgressBindingUpdateOne {
	if v != nil {
		_u.SetSourceIpv6(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *AccountEgressBindingUpdateOne) SetStatus(v string) *AccountEgressBindingUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AccountEgressBindingUpdateOne) SetNillableStatus(v *string) *AccountEgressBindingUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *AccountEgressBindingUpdateOne) SetVersion(v int64) *AccountEgressBindingUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *AccountEgressBindingUpdateOne) SetNillableVersion(v *int64) *AccountEgressBindingUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *AccountEgressBindingUpdateOne) AddVersion(v int64) *AccountEgressBindingUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetRotatedAt sets the "rotated_at" field.
func (_u *AccountEgressBindingUpdateOne) SetRotatedAt(v time.Time) *AccountEgressBindingUpdateOne {
	_u.mutation.SetRotatedAt(v)
	return _u
}

// SetNillableRotatedAt sets the "rotated_at" field if the given value is not nil.
func (_u *AccountEgressBindingUpdateOne) SetNillableRotatedAt(v *time.Time) *AccountEgressBindingUpdateOne {
	if v != nil {
		_u.SetRotatedAt(*v)
	}
	return _u
}

// ClearRotatedAt clears the value of the "rotated_at" field.
func (_u *AccountEgressBindingUpdateOne) ClearRotatedAt() *AccountEgressBindingUpdateOne {
	_u.mutation.ClearRotatedAt()
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *AccountEgressBindingUpdateOne) SetAccount(v *Account) *AccountEgressBindingUpdateOne {
	return _u.SetAccountID(v.ID)
}

// SetPool sets the "pool" edge to the IPv6EgressPool entity.
func (_u *AccountEgressBindingUpdateOne) SetPool(v *IPv6EgressPool) *AccountEgressBindingUpdateOne {
	return _u.SetPoolID(v.ID)
}

// Mutation returns the AccountEgressBindingMutation object of the builder.
func (_u *AccountEgressBindingUpdateOne) Mutation() *AccountEgressBindingMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *AccountEgressBindingUpdateOne) ClearAccount() *AccountEgressBindingUpdateOne {
	_u.mutation.ClearAccount()
	return _u
}

// ClearPool clears the "pool" edge to the IPv6EgressPool entity.
func (_u *AccountEgressBindingUpdateOne) ClearPool() *AccountEgressBindingUpdateOne {
	_u.mutation.ClearPool()
	return _u
}

// Where appends a list predicates to the AccountEgressBindingUpdate builder.
func (_u *AccountEgressBindingUpdateOne) Where(ps ...predicate.AccountEgressBinding) *AccountEgressBindingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AccountEgressBindingUpdateOne) Select(field string, fields ...string) *AccountEgressBindingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AccountEgressBinding entity.
func (_u *AccountEgressBindingUpdateOne) Save(ctx context.Context) (*AccountEgressBinding, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountEgressBindingUpdateOne) SaveX(ctx context.Context) *AccountEgressBinding {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AccountEgressBindingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountEgressBindingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccountEgressBindingUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := accountegressbinding.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountEgressBindingUpdateOne) check() error {
	if v, ok := _u.mutation.SourceIpv6(); ok {
		if err := accountegressbinding.SourceIpv6Validator(v); err != nil {
			return &ValidationError{Name: "source_ipv6", err: fmt.Errorf(`ent: validator failed for field "AccountEgressBinding.source_ipv6": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := accountegressbinding.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AccountEgressBinding.status": %w`, err)}
		}
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AccountEgressBinding.account"`)
	}
	if _u.mutation.PoolCleared() && len(_u.mutation.PoolIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AccountEgressBinding.pool"`)
	}
	return nil
}

func (_u *AccountEgressBindingUpdateOne) sqlSave(ctx context.Context) (_node *AccountEgressBinding, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accountegressbinding.Table, accountegressbinding.Columns, sqlgraph.NewFieldSpec(accountegressbinding.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AccountEgressBinding.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, accountegressbinding.FieldID)
		for _, f := range fields {
			if !accountegressbinding.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != accountegressbinding.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(accountegressbinding.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SourceIpv6(); ok {
		_spec.SetField(accountegressbinding.FieldSourceIpv6, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(accountegressbinding.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(accountegressbinding.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(accountegressbinding.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RotatedAt(); ok {
		_spec.SetField(accountegressbinding.FieldRotatedAt, field.TypeTime, value)
	}
	if _u.mutation.RotatedAtCleared() {
		_spec.ClearField(accountegressbinding.FieldRotatedAt, field.TypeTime)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   accountegressbinding.AccountTable,
			Columns: []string{accountegressbinding.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   accountegressbinding.AccountTable,
			Columns: []string{accountegressbinding.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PoolCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accountegressbinding.PoolTable,
			Columns: []string{accountegressbinding.PoolColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ipv6egresspool.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PoolIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accountegressbinding.PoolTable,
			Columns: []string{accountegressbinding.PoolColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ipv6egresspool.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AccountEgressBinding{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountegressbinding.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
