// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/accountegressbinding"
	"github.com/Wei-Shaw/sub2api/ent/ipv6egresspool"
)

// AccountEgressBindingCreate is the builder for creating a AccountEgressBinding entity.
type AccountEgressBindingCreate struct {
	config
	mutation *AccountEgressBindingMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *AccountEgressBindingCreate) SetCreatedAt(v time.Time) *AccountEgressBindingCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AccountEgressBindingCreate) SetNillableCreatedAt(v *time.Time) *AccountEgressBindingCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AccountEgressBindingCreate) SetUpdatedAt(v time.Time) *AccountEgressBindingCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AccountEgressBindingCreate) SetNillableUpdatedAt(v *time.Time) *AccountEgressBindingCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *AccountEgressBindingCreate) SetAccountID(v int64) *AccountEgressBindingCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetPoolID sets the "pool_id" field.
func (_c *AccountEgressBindingCreate) SetPoolID(v int64) *AccountEgressBindingCreate {
	_c.mutation.SetPoolID(v)
	return _c
}

// SetSourceIpv6 sets the "source_ipv6" field.
func (_c *AccountEgressBindingCreate) SetSourceIpv6(v string) *AccountEgressBindingCreate {
	_c.mutation.SetSourceIpv6(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *AccountEgressBindingCreate) SetStatus(v string) *AccountEgressBindingCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *AccountEgressBindingCreate) SetNillableStatus(v *string) *AccountEgressBindingCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *AccountEgressBindingCreate) SetVersion(v int64) *AccountEgressBindingCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *AccountEgressBindingCreate) SetNillableVersion(v *int64) *AccountEgressBindingCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetRotatedAt sets the "rotated_at" field.
func (_c *AccountEgressBindingCreate) SetRotatedAt(v time.Time) *AccountEgressBindingCreate {
	_c.mutation.SetRotatedAt(v)
	return _c
}

// SetNillableRotatedAt sets the "rotated_at" field if the given value is not nil.
func (_c *AccountEgressBindingCreate) SetNillableRotatedAt(v *time.Time) *AccountEgressBindingCreate {
	if v != nil {
		_c.SetRotatedAt(*v)
	}
	return _c
}

// SetAccount sets the "account" edge to the Account entity.
func (_c *AccountEgressBindingCreate) SetAccount(v *Account) *AccountEgressBindingCreate {
	return _c.SetAccountID(v.ID)
}

// SetPool sets the "pool" edge to the IPv6EgressPool entity.
func (_c *AccountEgressBindingCreate) SetPool(v *IPv6EgressPool) *AccountEgressBindingCreate {
	return _c.SetPoolID(v.ID)
}

// Mutation returns the AccountEgressBindingMutation object of the builder.
func (_c *AccountEgressBindingCreate) Mutation() *AccountEgressBindingMutation {
	return _c.mutation
}

// Save creates the AccountEgressBinding in the database.
func (_c *AccountEgressBindingCreate) Save(ctx context.Context) (*AccountEgressBinding, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccountEgressBindingCreate) SaveX(ctx context.Context) *AccountEgressBinding {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountEgressBindingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountEgressBindingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AccountEgressBindingCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := accountegressbinding.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := accountegressbinding.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := accountegressbinding.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := accountegressbinding.DefaultVersion
		_c.mutation.SetVersion(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccountEgressBindingCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AccountEgressBinding.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AccountEgressBinding.updated_at"`)}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "AccountEgressBinding.account_id"`)}
	}
	if _, ok := _c.mutation.PoolID(); !ok {
		return &ValidationError{Name: "pool_id", err: errors.New(`ent: missing required field "AccountEgressBinding.pool_id"`)}
	}
	if _, ok := _c.mutation.SourceIpv6(); !ok {
		return &ValidationError{Name: "source_ipv6", err: errors.New(`ent: missing required field "AccountEgressBinding.source_ipv6"`)}
	}
	if v, ok := _c.mutation.SourceIpv6(); ok {
		if err := accountegressbinding.SourceIpv6Validator(v); err != nil {
			return &ValidationError{Name: "source_ipv6", err: fmt.Errorf(`ent: validator failed for field "AccountEgressBinding.source_ipv6": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "AccountEgressBinding.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := accountegressbinding.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AccountEgressBinding.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "AccountEgressBinding.version"`)}
	}
	if len(_c.mutation.AccountIDs()) == 0 {
		return &ValidationError{Name: "account", err: errors.New(`ent: missing required edge "AccountEgressBinding.account"`)}
	}
	if len(_c.mutation.PoolIDs()) == 0 {
		return &ValidationError{Name: "pool", err: errors.New(`ent: missing required edge "AccountEgressBinding.pool"`)}
	}
	return nil
}

func (_c *AccountEgressBindingCreate) sqlSave(ctx context.Context) (*AccountEgressBinding, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AccountEgressBindingCreate) createSpec() (*AccountEgressBinding, *sqlgraph.CreateSpec) {
	var (
		_node = &AccountEgressBinding{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(accountegressbinding.Table, sqlgraph.NewFieldSpec(accountegressbinding.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(accountegressbinding.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(accountegressbinding.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.SourceIpv6(); ok {
		_spec.SetField(accountegressbinding.FieldSourceIpv6, field.TypeString, value)
		_node.SourceIpv6 = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(accountegressbinding.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(accountegressbinding.FieldVersion, field.TypeInt64, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.RotatedAt(); ok {
		_spec.SetField(accountegressbinding.FieldRotatedAt, field.TypeTime, value)
		_node.RotatedAt = &value
	}
	if nodes := _c.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   accountegressbinding.AccountTable,
			Columns: []string{accountegressbinding.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AccountID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PoolIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accountegressbinding.PoolTable,
			Columns: []string{accountegressbinding.PoolColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ipv6egresspool.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PoolID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountEgressBinding.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountEgressBindingUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountEgressBindingCreate) OnConflict(opts ...sql.ConflictOption) *AccountEgressBindingUpsertOne {
	_c.conflict = opts
	return &AccountEgressBindingUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountEgressBinding.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountEgressBindingCreate) OnConflictColumns(columns ...string) *AccountEgressBindingUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountEgressBindingUpsertOne{
		create: _c,
	}
}

type (
	// AccountEgressBindingUpsertOne is the builder for "upsert"-ing
	//  one AccountEgressBinding node.
	AccountEgressBindingUpsertOne struct {
		create *AccountEgressBindingCreate
	}

	// AccountEgressBindingUpsert is the "OnConflict" setter.
	AccountEgressBindingUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountEgressBindingUpsert) SetUpdatedAt(v time.Time) *AccountEgressBindingUpsert {
	u.Set(accountegressbinding.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountEgressBindingUpsert) UpdateUpdatedAt() *AccountEgressBindingUpsert {
	u.SetExcluded(accountegressbinding.FieldUpdatedAt)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *AccountEgressBindingUpsert) SetAccountID(v int64) *AccountEgressBindingUpsert {
	u.Set(accountegressbinding.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountEgressBindingUpsert) UpdateAccountID() *AccountEgressBindingUpsert {
	u.SetExcluded(accountegressbinding.FieldAccountID)
	return u
}

// SetPoolID sets the "pool_id" field.
func (u *AccountEgressBindingUpsert) SetPoolID(v int64) *AccountEgressBindingUpsert {
	u.Set(accountegressbinding.FieldPoolID, v)
	return u
}

// UpdatePoolID sets the "pool_id" field to the value that was provided on create.
func (u *AccountEgressBindingUpsert) UpdatePoolID() *AccountEgressBindingUpsert {
	u.SetExcluded(accountegressbinding.FieldPoolID)
	return u
}

// SetSourceIpv6 sets the "source_ipv6" field.
func (u *AccountEgressBindingUpsert) SetSourceIpv6(v string) *AccountEgressBindingUpsert {
	u.Set(accountegressbinding.FieldSourceIpv6, v)
	return u
}

// UpdateSourceIpv6 sets the "source_ipv6" field to the value that was provided on create.
func (u *AccountEgressBindingUpsert) UpdateSourceIpv6() *AccountEgressBindingUpsert {
	u.SetExcluded(accountegressbinding.FieldSourceIpv6)
	return u
}

// SetStatus sets the "status" field.
func (u *AccountEgressBindingUpsert) SetStatus(v string) *AccountEgressBindingUpsert {
	u.Set(accountegressbinding.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AccountEgressBindingUpsert) UpdateStatus() *AccountEgressBindingUpsert {
	u.SetExcluded(accountegressbinding.FieldStatus)
	return u
}

// SetVersion sets the "version" field.
func (u *AccountEgressBindingUpsert) SetVersion(v int64) *AccountEgressBindingUpsert {
	u.Set(accountegressbinding.FieldVersion, v)
	return u
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *AccountEgressBindingUpsert) UpdateVersion() *AccountEgressBindingUpsert {
	u.SetExcluded(accountegressbinding.FieldVersion)
	return u
}

// AddVersion adds v to the "version" field.
func (u *AccountEgressBindingUpsert) AddVersion(v int64) *AccountEgressBindingUpsert {
	u.Add(accountegressbinding.FieldVersion, v)
	return u
}

// SetRotatedAt sets the "rotated_at" field.
func (u *AccountEgressBindingUpsert) SetRotatedAt(v time.Time) *AccountEgressBindingUpsert {
	u.Set(accountegressbinding.FieldRotatedAt, v)
	return u
}

// UpdateRotatedAt sets the "rotated_at" field to the value that was provided on create.
func (u *AccountEgressBindingUpsert) UpdateRotatedAt() *AccountEgressBindingUpsert {
	u.SetExcluded(accountegressbinding.FieldRotatedAt)
	return u
}

// ClearRotatedAt clears the value of the "rotated_at" field.
func (u *AccountEgressBindingUpsert) ClearRotatedAt() *AccountEgressBindingUpsert {
	u.SetNull(accountegressbinding.FieldRotatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AccountEgressBinding.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountEgressBindingUpsertOne) UpdateNewValues() *AccountEgressBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(accountegressbinding.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountEgressBinding.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AccountEgressBindingUpsertOne) Ignore() *AccountEgressBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountEgressBindingUpsertOne) DoNothing() *AccountEgressBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountEgressBindingCreate.OnConflict
// documentation for more info.
func (u *AccountEgressBindingUpsertOne) Update(set func(*AccountEgressBindingUpsert)) *AccountEgressBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountEgressBindingUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountEgressBindingUpsertOne) SetUpdatedAt(v time.Time) *AccountEgressBindingUpsertOne {
	return u.Update(func(s *AccountEgressBindingUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountEgressBindingUpsertOne) UpdateUpdatedAt() *AccountEgressBindingUpsertOne {
	return u.Update(func(s *AccountEgressBindingUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAccountID sets the "account_id" field.
func (u *AccountEgressBindingUpsertOne) SetAccountID(v int64) *AccountEgressBindingUpsertOne {
	return u.Update(func(s *AccountEgressBindingUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountEgressBindingUpsertOne) UpdateAccountID() *AccountEgressBindingUpsertOne {
	return u.Update(func(s *AccountEgressBindingUpsert) {
		s.UpdateAccountID()
	})
}

// SetPoolID sets the "pool_id" field.
func (u *AccountEgressBindingUpsertOne) SetPoolID(v int64) *AccountEgressBindingUpsertOne {
	return u.Update(func(s *AccountEgressBindingUpsert) {
		s.SetPoolID(v)
	})
}

// UpdatePoolID sets the "pool_id" field to the value that was provided on create.
func (u *AccountEgressBindingUpsertOne) UpdatePoolID() *AccountEgressBindingUpsertOne {
	return u.Update(func(s *AccountEgressBindingUpsert) {
		s.UpdatePoolID()
	})
}

// SetSourceIpv6 sets the "source_ipv6" field.
func (u *AccountEgressBindingUpsertOne) SetSourceIpv6(v string) *AccountEgressBindingUpsertOne {
	return u.Update(func(s *AccountEgressBindingUpsert) {
		s.SetSourceIpv6(v)
	})
}

// UpdateSourceIpv6 sets the "source_ipv6" field to the value that was provided on create.
func (u *AccountEgressBindingUpsertOne) UpdateSourceIpv6() *AccountEgressBindingUpsertOne {
	return u.Update(func(s *AccountEgressBindingUpsert) {
		s.UpdateSourceIpv6()
	})
}

// SetStatus sets the "status" field.
func (u *AccountEgressBindingUpsertOne) SetStatus(v string) *AccountEgressBindingUpsertOne {
	return u.Update(func(s *AccountEgressBindingUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AccountEgressBindingUpsertOne) UpdateStatus() *AccountEgressBindingUpsertOne {
	return u.Update(func(s *AccountEgressBindingUpsert) {
		s.UpdateStatus()
	})
}

// SetVersion sets the "version" field.
func (u *AccountEgressBindingUpsertOne) SetVersion(v int64) *AccountEgressBindingUpsertOne {
	return u.Update(func(s *AccountEgressBindingUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *AccountEgressBindingUpsertOne) AddVersion(v int64) *AccountEgressBindingUpsertOne {
	return u.Update(func(s *AccountEgressBindingUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *AccountEgressBindingUpsertOne) UpdateVersion() *AccountEgressBindingUpsertOne {
	return u.Update(func(s *AccountEgressBindingUpsert) {
		s.UpdateVersion()
	})
}

// SetRotatedAt sets the "rotated_at" field.
func (u *AccountEgressBindingUpsertOne) SetRotatedAt(v time.Time) *AccountEgressBindingUpsertOne {
	return u.Update(func(s *AccountEgressBindingUpsert) {
		s.SetRotatedAt(v)
	})
}

// UpdateRotatedAt sets the "rotated_at" field to the value that was provided on create.
func (u *AccountEgressBindingUpsertOne) UpdateRotatedAt() *AccountEgressBindingUpsertOne {
	return u.Update(func(s *AccountEgressBindingUpsert) {
		s.UpdateRotatedAt()
	})
}

// ClearRotatedAt clears the value of the "rotated_at" field.
func (u *AccountEgressBindingUpsertOne) ClearRotatedAt() *AccountEgressBindingUpsertOne {
	return u.Update(func(s *AccountEgressBindingUpsert) {
		s.ClearRotatedAt()
	})
}

// Exec executes the query.
func (u *AccountEgressBindingUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountEgressBindingCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountEgressBindingUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AccountEgressBindingUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AccountEgressBindingUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AccountEgressBindingCreateBulk is the builder for creating many AccountEgressBinding entities in bulk.
type AccountEgressBindingCreateBulk struct {
	config
	err      error
	builders []*AccountEgressBindingCreate
	conflict []sql.ConflictOption
}

// Save creates the AccountEgressBinding entities in the database.
func (_c *AccountEgressBindingCreateBulk) Save(ctx context.Context) ([]*AccountEgressBinding, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AccountEgressBinding, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccountEgressBindingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccountEgressBindingCreateBulk) SaveX(ctx context.Context) []*AccountEgressBinding {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountEgressBindingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountEgressBindingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountEgressBinding.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountEgressBindingUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountEgressBindingCreateBulk) OnConflict(opts ...sql.ConflictOption) *AccountEgressBindingUpsertBulk {
	_c.conflict = opts
	return &AccountEgressBindingUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountEgressBinding.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountEgressBindingCreateBulk) OnConflictColumns(columns ...string) *AccountEgressBindingUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountEgressBindingUpsertBulk{
		create: _c,
	}
}

// AccountEgressBindingUpsertBulk is the builder for "upsert"-ing
// a bulk of AccountEgressBinding nodes.
type AccountEgressBindingUpsertBulk struct {
	create *AccountEgressBindingCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AccountEgressBinding.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountEgressBindingUpsertBulk) UpdateNewValues() *AccountEgressBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(accountegressbinding.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountEgressBinding.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AccountEgressBindingUpsertBulk) Ignore() *AccountEgressBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountEgressBindingUpsertBulk) DoNothing() *AccountEgressBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountEgressBindingCreateBulk.OnConflict
// documentation for more info.
func (u *AccountEgressBindingUpsertBulk) Update(set func(*AccountEgressBindingUpsert)) *AccountEgressBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountEgressBindingUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountEgressBindingUpsertBulk) SetUpdatedAt(v time.Time) *AccountEgressBindingUpsertBulk {
	return u.Update(func(s *AccountEgressBindingUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountEgressBindingUpsertBulk) UpdateUpdatedAt() *AccountEgressBindingUpsertBulk {
	return u.Update(func(s *AccountEgressBindingUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAccountID sets the "account_id" field.
func (u *AccountEgressBindingUpsertBulk) SetAccountID(v int64) *AccountEgressBindingUpsertBulk {
	return u.Update(func(s *AccountEgressBindingUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountEgressBindingUpsertBulk) UpdateAccountID() *AccountEgressBindingUpsertBulk {
	return u.Update(func(s *AccountEgressBindingUpsert) {
		s.UpdateAccountID()
	})
}

// SetPoolID sets the "pool_id" field.
func (u *AccountEgressBindingUpsertBulk) SetPoolID(v int64) *AccountEgressBindingUpsertBulk {
	return u.Update(func(s *AccountEgressBindingUpsert) {
		s.SetPoolID(v)
	})
}

// UpdatePoolID sets the "pool_id" field to the value that was provided on create.
func (u *AccountEgressBindingUpsertBulk) UpdatePoolID() *AccountEgressBindingUpsertBulk {
	return u.Update(func(s *AccountEgressBindingUpsert) {
		s.UpdatePoolID()
	})
}

// SetSourceIpv6 sets the "source_ipv6" field.
func (u *AccountEgressBindingUpsertBulk) SetSourceIpv6(v string) *AccountEgressBindingUpsertBulk {
	return u.Update(func(s *AccountEgressBindingUpsert) {
		s.SetSourceIpv6(v)
	})
}

// UpdateSourceIpv6 sets the "source_ipv6" field to the value that was provided on create.
func (u *AccountEgressBindingUpsertBulk) UpdateSourceIpv6() *AccountEgressBindingUpsertBulk {
	return u.Update(func(s *AccountEgressBindingUpsert) {
		s.UpdateSourceIpv6()
	})
}

// SetStatus sets the "status" field.
func (u *AccountEgressBindingUpsertBulk) SetStatus(v string) *AccountEgressBindingUpsertBulk {
	return u.Update(func(s *AccountEgressBindingUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AccountEgressBindingUpsertBulk) UpdateStatus() *AccountEgressBindingUpsertBulk {
	return u.Update(func(s *AccountEgressBindingUpsert) {
		s.UpdateStatus()
	})
}

// SetVersion sets the "version" field.
func (u *AccountEgressBindingUpsertBulk) SetVersion(v int64) *AccountEgressBindingUpsertBulk {
	return u.Update(func(s *AccountEgressBindingUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *AccountEgressBindingUpsertBulk) AddVersion(v int64) *AccountEgressBindingUpsertBulk {
	return u.Update(func(s *AccountEgressBindingUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *AccountEgressBindingUpsertBulk) UpdateVersion() *AccountEgressBindingUpsertBulk {
	return u.Update(func(s *AccountEgressBindingUpsert) {
		s.UpdateVersion()
	})
}

// SetRotatedAt sets the "rotated_at" field.
func (u *AccountEgressBindingUpsertBulk) SetRotatedAt(v time.Time) *AccountEgressBindingUpsertBulk {
	return u.Update(func(s *AccountEgressBindingUpsert) {
		s.SetRotatedAt(v)
	})
}

// UpdateRotatedAt sets the "rotated_at" field to the value that was provided on create.
func (u *AccountEgressBindingUpsertBulk) UpdateRotatedAt() *AccountEgressBindingUpsertBulk {
	return u.Update(func(s *AccountEgressBindingUpsert) {
		s.UpdateRotatedAt()
	})
}

// ClearRotatedAt clears the value of the "rotated_at" field.
func (u *AccountEgressBindingUpsertBulk) ClearRotatedAt() *AccountEgressBindingUpsertBulk {
	return u.Update(func(s *AccountEgressBindingUpsert) {
		s.ClearRotatedAt()
	})
}

// Exec executes the query.
func (u *AccountEgressBindingUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AccountEgressBindingCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountEgressBindingCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountEgressBindingUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
