// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/chatasset"
	"github.com/Wei-Shaw/sub2api/ent/chatmessage"
	"github.com/Wei-Shaw/sub2api/ent/chatmessageasset"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ChatMessageAssetUpdate is the builder for updating ChatMessageAsset entities.
type ChatMessageAssetUpdate struct {
	config
	hooks    []Hook
	mutation *ChatMessageAssetMutation
}

// Where appends a list predicates to the ChatMessageAssetUpdate builder.
func (_u *ChatMessageAssetUpdate) Where(ps ...predicate.ChatMessageAsset) *ChatMessageAssetUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetMessageID sets the "message_id" field.
func (_u *ChatMessageAssetUpdate) SetMessageID(v int64) *ChatMessageAssetUpdate {
	_u.mutation.SetMessageID(v)
	return _u
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (_u *ChatMessageAssetUpdate) SetNillableMessageID(v *int64) *ChatMessageAssetUpdate {
	if v != nil {
		_u.SetMessageID(*v)
	}
	return _u
}

// SetAssetID sets the "asset_id" field.
func (_u *ChatMessageAssetUpdate) SetAssetID(v int64) *ChatMessageAssetUpdate {
	_u.mutation.SetAssetID(v)
	return _u
}

// SetNillableAssetID sets the "asset_id" field if the given value is not nil.
func (_u *ChatMessageAssetUpdate) SetNillableAssetID(v *int64) *ChatMessageAssetUpdate {
	if v != nil {
		_u.SetAssetID(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *ChatMessageAssetUpdate) SetSortOrder(v int) *ChatMessageAssetUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *ChatMessageAssetUpdate) SetNillableSortOrder(v *int) *ChatMessageAssetUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *ChatMessageAssetUpdate) AddSortOrder(v int) *ChatMessageAssetUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetMessage sets the "message" edge to the ChatMessage entity.
func (_u *ChatMessageAssetUpdate) SetMessage(v *ChatMessage) *ChatMessageAssetUpdate {
	return _u.SetMessageID(v.ID)
}

// SetAsset sets the "asset" edge to the ChatAsset entity.
func (_u *ChatMessageAssetUpdate) SetAsset(v *ChatAsset) *ChatMessageAssetUpdate {
	return _u.SetAssetID(v.ID)
}

// Mutation returns the ChatMessageAssetMutation object of the builder.
func (_u *ChatMessageAssetUpdate) Mutation() *ChatMessageAssetMutation {
	return _u.mutation
}

// ClearMessage clears the "message" edge to the ChatMessage entity.
func (_u *ChatMessageAssetUpdate) ClearMessage() *ChatMessageAssetUpdate {
	_u.mutation.ClearMessage()
	return _u
}

// ClearAsset clears the "asset" edge to the ChatAsset entity.
func (_u *ChatMessageAssetUpdate) ClearAsset() *ChatMessageAssetUpdate {
	_u.mutation.ClearAsset()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ChatMessageAssetUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChatMessageAssetUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ChatMessageAssetUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChatMessageAssetUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChatMessageAssetUpdate) check() error {
	if _u.mutation.MessageCleared() && len(_u.mutation.MessageIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChatMessageAsset.message"`)
	}
	if _u.mutation.AssetCleared() && len(_u.mutation.AssetIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChatMessageAsset.asset"`)
	}
	return nil
}

func (_u *ChatMessageAssetUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(chatmessageasset.Table, chatmessageasset.Columns, sqlgraph.NewFieldSpec(chatmessageasset.FieldMessageID, field.TypeInt64), sqlgraph.NewFieldSpec(chatmessageasset.FieldAssetID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(chatmessageasset.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(chatmessageasset.FieldSortOrder, field.TypeInt, value)
	}
	if _u.mutation.MessageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   chatmessageasset.MessageTable,
			Columns: []string{chatmessageasset.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatmessage.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   chatmessageasset.MessageTable,
			Columns: []string{chatmessageasset.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AssetCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   chatmessageasset.AssetTable,
			Columns: []string{chatmessageasset.AssetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatasset.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   chatmessageasset.AssetTable,
			Columns: []string{chatmessageasset.AssetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatasset.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chatmessageasset.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ChatMessageAssetUpdateOne is the builder for updating a single ChatMessageAsset entity.
type ChatMessageAssetUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChatMessageAssetMutation
}

// SetMessageID sets the "message_id" field.
func (_u *ChatMessageAssetUpdateOne) SetMessageID(v int64) *ChatMessageAssetUpdateOne {
	_u.mutation.SetMessageID(v)
	return _u
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (_u *ChatMessageAssetUpdateOne) SetNillableMessageID(v *int64) *ChatMessageAssetUpdateOne {
	if v != nil {
		_u.SetMessageID(*v)
	}
	return _u
}

// SetAssetID sets the "asset_id" field.
func (_u *ChatMessageAssetUpdateOne) SetAssetID(v int64) *ChatMessageAssetUpdateOne {
	_u.mutation.SetAssetID(v)
	return _u
}

// SetNillableAssetID sets the "asset_id" field if the given value is not nil.
func (_u *ChatMessageAssetUpdateOne) SetNillableAssetID(v *int64) *ChatMessageAssetUpdateOne {
	if v != nil {
		_u.SetAssetID(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *ChatMessageAssetUpdateOne) SetSortOrder(v int) *ChatMessageAssetUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *ChatMessageAssetUpdateOne) SetNillableSortOrder(v *int) *ChatMessageAssetUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *ChatMessageAssetUpdateOne) AddSortOrder(v int) *ChatMessageAssetUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetMessage sets the "message" edge to the ChatMessage entity.
func (_u *ChatMessageAssetUpdateOne) SetMessage(v *ChatMessage) *ChatMessageAssetUpdateOne {
	return _u.SetMessageID(v.ID)
}

// SetAsset sets the "asset" edge to the ChatAsset entity.
func (_u *ChatMessageAssetUpdateOne) SetAsset(v *ChatAsset) *ChatMessageAssetUpdateOne {
	return _u.SetAssetID(v.ID)
}

// Mutation returns the ChatMessageAssetMutation object of the builder.
func (_u *ChatMessageAssetUpdateOne) Mutation() *ChatMessageAssetMutation {
	return _u.mutation
}

// ClearMessage clears the "message" edge to the ChatMessage entity.
func (_u *ChatMessageAssetUpdateOne) ClearMessage() *ChatMessageAssetUpdateOne {
	_u.mutation.ClearMessage()
	return _u
}

// ClearAsset clears the "asset" edge to the ChatAsset entity.
func (_u *ChatMessageAssetUpdateOne) ClearAsset() *ChatMessageAssetUpdateOne {
	_u.mutation.ClearAsset()
	return _u
}

// Where appends a list predicates to the ChatMessageAssetUpdate builder.
func (_u *ChatMessageAssetUpdateOne) Where(ps ...predicate.ChatMessageAsset) *ChatMessageAssetUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ChatMessageAssetUpdateOne) Select(field string, fields ...string) *ChatMessageAssetUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ChatMessageAsset entity.
func (_u *ChatMessageAssetUpdateOne) Save(ctx context.Context) (*ChatMessageAsset, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChatMessageAssetUpdateOne) SaveX(ctx context.Context) *ChatMessageAsset {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ChatMessageAssetUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChatMessageAssetUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChatMessageAssetUpdateOne) check() error {
	if _u.mutation.MessageCleared() && len(_u.mutation.MessageIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChatMessageAsset.message"`)
	}
	if _u.mutation.AssetCleared() && len(_u.mutation.AssetIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChatMessageAsset.asset"`)
	}
	return nil
}

func (_u *ChatMessageAssetUpdateOne) sqlSave(ctx context.Context) (_node *ChatMessageAsset, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(chatmessageasset.Table, chatmessageasset.Columns, sqlgraph.NewFieldSpec(chatmessageasset.FieldMessageID, field.TypeInt64), sqlgraph.NewFieldSpec(chatmessageasset.FieldAssetID, field.TypeInt64))
	if id, ok := _u.mutation.MessageID(); !ok {
		return nil, &ValidationError{Name: "message_id", err: errors.New(`ent: missing "ChatMessageAsset.message_id" for update`)}
	} else {
		_spec.Node.CompositeID[0].Value = id
	}
	if id, ok := _u.mutation.AssetID(); !ok {
		return nil, &ValidationError{Name: "asset_id", err: errors.New(`ent: missing "ChatMessageAsset.asset_id" for update`)}
	} else {
		_spec.Node.CompositeID[1].Value = id
	}
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, len(fields))
		for i, f := range fields {
			if !chatmessageasset.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			_spec.Node.Columns[i] = f
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(chatmessageasset.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(chatmessageasset.FieldSortOrder, field.TypeInt, value)
	}
	if _u.mutation.MessageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   chatmessageasset.MessageTable,
			Columns: []string{chatmessageasset.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatmessage.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   chatmessageasset.MessageTable,
			Columns: []string{chatmessageasset.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AssetCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   chatmessageasset.AssetTable,
			Columns: []string{chatmessageasset.AssetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatasset.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   chatmessageasset.AssetTable,
			Columns: []string{chatmessageasset.AssetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatasset.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ChatMessageAsset{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chatmessageasset.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
