// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/chatquickreply"
)

// ChatQuickReplyCreate is the builder for creating a ChatQuickReply entity.
type ChatQuickReplyCreate struct {
	config
	mutation *ChatQuickReplyMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetAdminID sets the "admin_id" field.
func (_c *ChatQuickReplyCreate) SetAdminID(v int64) *ChatQuickReplyCreate {
	_c.mutation.SetAdminID(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *ChatQuickReplyCreate) SetTitle(v string) *ChatQuickReplyCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *ChatQuickReplyCreate) SetContent(v string) *ChatQuickReplyCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *ChatQuickReplyCreate) SetSortOrder(v int) *ChatQuickReplyCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *ChatQuickReplyCreate) SetNillableSortOrder(v *int) *ChatQuickReplyCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ChatQuickReplyCreate) SetCreatedAt(v time.Time) *ChatQuickReplyCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ChatQuickReplyCreate) SetNillableCreatedAt(v *time.Time) *ChatQuickReplyCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ChatQuickReplyCreate) SetUpdatedAt(v time.Time) *ChatQuickReplyCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ChatQuickReplyCreate) SetNillableUpdatedAt(v *time.Time) *ChatQuickReplyCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the ChatQuickReplyMutation object of the builder.
func (_c *ChatQuickReplyCreate) Mutation() *ChatQuickReplyMutation {
	return _c.mutation
}

// Save creates the ChatQuickReply in the database.
func (_c *ChatQuickReplyCreate) Save(ctx context.Context) (*ChatQuickReply, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChatQuickReplyCreate) SaveX(ctx context.Context) *ChatQuickReply {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChatQuickReplyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChatQuickReplyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ChatQuickReplyCreate) defaults() {
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := chatquickreply.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := chatquickreply.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := chatquickreply.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChatQuickReplyCreate) check() error {
	if _, ok := _c.mutation.AdminID(); !ok {
		return &ValidationError{Name: "admin_id", err: errors.New(`ent: missing required field "ChatQuickReply.admin_id"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "ChatQuickReply.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := chatquickreply.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "ChatQuickReply.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "ChatQuickReply.content"`)}
	}
	if v, ok := _c.mutation.Content(); ok {
		if err := chatquickreply.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "ChatQuickReply.content": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "ChatQuickReply.sort_order"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ChatQuickReply.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ChatQuickReply.updated_at"`)}
	}
	return nil
}

func (_c *ChatQuickReplyCreate) sqlSave(ctx context.Context) (*ChatQuickReply, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChatQuickReplyCreate) createSpec() (*ChatQuickReply, *sqlgraph.CreateSpec) {
	var (
		_node = &ChatQuickReply{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(chatquickreply.Table, sqlgraph.NewFieldSpec(chatquickreply.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.AdminID(); ok {
		_spec.SetField(chatquickreply.FieldAdminID, field.TypeInt64, value)
		_node.AdminID = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(chatquickreply.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(chatquickreply.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(chatquickreply.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(chatquickreply.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(chatquickreply.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ChatQuickReply.Create().
//		SetAdminID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChatQuickReplyUpsert) {
//			SetAdminID(v+v).
//		}).
//		Exec(ctx)
func (_c *ChatQuickReplyCreate) OnConflict(opts ...sql.ConflictOption) *ChatQuickReplyUpsertOne {
	_c.conflict = opts
	return &ChatQuickReplyUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ChatQuickReply.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChatQuickReplyCreate) OnConflictColumns(columns ...string) *ChatQuickReplyUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChatQuickReplyUpsertOne{
		create: _c,
	}
}

type (
	// ChatQuickReplyUpsertOne is the builder for "upsert"-ing
	//  one ChatQuickReply node.
	ChatQuickReplyUpsertOne struct {
		create *ChatQuickReplyCreate
	}

	// ChatQuickReplyUpsert is the "OnConflict" setter.
	ChatQuickReplyUpsert struct {
		*sql.UpdateSet
	}
)

// SetAdminID sets the "admin_id" field.
func (u *ChatQuickReplyUpsert) SetAdminID(v int64) *ChatQuickReplyUpsert {
	u.Set(chatquickreply.FieldAdminID, v)
	return u
}

// UpdateAdminID sets the "admin_id" field to the value that was provided on create.
func (u *ChatQuickReplyUpsert) UpdateAdminID() *ChatQuickReplyUpsert {
	u.SetExcluded(chatquickreply.FieldAdminID)
	return u
}

// AddAdminID adds v to the "admin_id" field.
func (u *ChatQuickReplyUpsert) AddAdminID(v int64) *ChatQuickReplyUpsert {
	u.Add(chatquickreply.FieldAdminID, v)
	return u
}

// SetTitle sets the "title" field.
func (u *ChatQuickReplyUpsert) SetTitle(v string) *ChatQuickReplyUpsert {
	u.Set(chatquickreply.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *ChatQuickReplyUpsert) UpdateTitle() *ChatQuickReplyUpsert {
	u.SetExcluded(chatquickreply.FieldTitle)
	return u
}

// SetContent sets the "content" field.
func (u *ChatQuickReplyUpsert) SetContent(v string) *ChatQuickReplyUpsert {
	u.Set(chatquickreply.FieldContent, v)
	return u
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *ChatQuickReplyUpsert) UpdateContent() *ChatQuickReplyUpsert {
	u.SetExcluded(chatquickreply.FieldContent)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *ChatQuickReplyUpsert) SetSortOrder(v int) *ChatQuickReplyUpsert {
	u.Set(chatquickreply.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *ChatQuickReplyUpsert) UpdateSortOrder() *ChatQuickReplyUpsert {
	u.SetExcluded(chatquickreply.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *ChatQuickReplyUpsert) AddSortOrder(v int) *ChatQuickReplyUpsert {
	u.Add(chatquickreply.FieldSortOrder, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ChatQuickReplyUpsert) SetUpdatedAt(v time.Time) *ChatQuickReplyUpsert {
	u.Set(chatquickreply.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChatQuickReplyUpsert) UpdateUpdatedAt() *ChatQuickReplyUpsert {
	u.SetExcluded(chatquickreply.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ChatQuickReply.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ChatQuickReplyUpsertOne) UpdateNewValues() *ChatQuickReplyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(chatquickreply.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ChatQuickReply.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ChatQuickReplyUpsertOne) Ignore() *ChatQuickReplyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChatQuickReplyUpsertOne) DoNothing() *ChatQuickReplyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChatQuickReplyCreate.OnConflict
// documentation for more info.
func (u *ChatQuickReplyUpsertOne) Update(set func(*ChatQuickReplyUpsert)) *ChatQuickReplyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChatQuickReplyUpsert{UpdateSet: update})
	}))
	return u
}

// SetAdminID sets the "admin_id" field.
func (u *ChatQuickReplyUpsertOne) SetAdminID(v int64) *ChatQuickReplyUpsertOne {
	return u.Update(func(s *ChatQuickReplyUpsert) {
		s.SetAdminID(v)
	})
}

// AddAdminID adds v to the "admin_id" field.
func (u *ChatQuickReplyUpsertOne) AddAdminID(v int64) *ChatQuickReplyUpsertOne {
	return u.Update(func(s *ChatQuickReplyUpsert) {
		s.AddAdminID(v)
	})
}

// UpdateAdminID sets the "admin_id" field to the value that was provided on create.
func (u *ChatQuickReplyUpsertOne) UpdateAdminID() *ChatQuickReplyUpsertOne {
	return u.Update(func(s *ChatQuickReplyUpsert) {
		s.UpdateAdminID()
	})
}

// SetTitle sets the "title" field.
func (u *ChatQuickReplyUpsertOne) SetTitle(v string) *ChatQuickReplyUpsertOne {
	return u.Update(func(s *ChatQuickReplyUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *ChatQuickReplyUpsertOne) UpdateTitle() *ChatQuickReplyUpsertOne {
	return u.Update(func(s *ChatQuickReplyUpsert) {
		s.UpdateTitle()
	})
}

// SetContent sets the "content" field.
func (u *ChatQuickReplyUpsertOne) SetContent(v string) *ChatQuickReplyUpsertOne {
	return u.Update(func(s *ChatQuickReplyUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *ChatQuickReplyUpsertOne) UpdateContent() *ChatQuickReplyUpsertOne {
	return u.Update(func(s *ChatQuickReplyUpsert) {
		s.UpdateContent()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *ChatQuickReplyUpsertOne) SetSortOrder(v int) *ChatQuickReplyUpsertOne {
	return u.Update(func(s *ChatQuickReplyUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *ChatQuickReplyUpsertOne) AddSortOrder(v int) *ChatQuickReplyUpsertOne {
	return u.Update(func(s *ChatQuickReplyUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *ChatQuickReplyUpsertOne) UpdateSortOrder() *ChatQuickReplyUpsertOne {
	return u.Update(func(s *ChatQuickReplyUpsert) {
		s.UpdateSortOrder()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ChatQuickReplyUpsertOne) SetUpdatedAt(v time.Time) *ChatQuickReplyUpsertOne {
	return u.Update(func(s *ChatQuickReplyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChatQuickReplyUpsertOne) UpdateUpdatedAt() *ChatQuickReplyUpsertOne {
	return u.Update(func(s *ChatQuickReplyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ChatQuickReplyUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChatQuickReplyCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChatQuickReplyUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ChatQuickReplyUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ChatQuickReplyUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ChatQuickReplyCreateBulk is the builder for creating many ChatQuickReply entities in bulk.
type ChatQuickReplyCreateBulk struct {
	config
	err      error
	builders []*ChatQuickReplyCreate
	conflict []sql.ConflictOption
}

// Save creates the ChatQuickReply entities in the database.
func (_c *ChatQuickReplyCreateBulk) Save(ctx context.Context) ([]*ChatQuickReply, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ChatQuickReply, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChatQuickReplyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChatQuickReplyCreateBulk) SaveX(ctx context.Context) []*ChatQuickReply {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChatQuickReplyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChatQuickReplyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ChatQuickReply.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChatQuickReplyUpsert) {
//			SetAdminID(v+v).
//		}).
//		Exec(ctx)
func (_c *ChatQuickReplyCreateBulk) OnConflict(opts ...sql.ConflictOption) *ChatQuickReplyUpsertBulk {
	_c.conflict = opts
	return &ChatQuickReplyUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ChatQuickReply.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChatQuickReplyCreateBulk) OnConflictColumns(columns ...string) *ChatQuickReplyUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChatQuickReplyUpsertBulk{
		create: _c,
	}
}

// ChatQuickReplyUpsertBulk is the builder for "upsert"-ing
// a bulk of ChatQuickReply nodes.
type ChatQuickReplyUpsertBulk struct {
	create *ChatQuickReplyCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ChatQuickReply.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ChatQuickReplyUpsertBulk) UpdateNewValues() *ChatQuickReplyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(chatquickreply.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ChatQuickReply.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ChatQuickReplyUpsertBulk) Ignore() *ChatQuickReplyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChatQuickReplyUpsertBulk) DoNothing() *ChatQuickReplyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChatQuickReplyCreateBulk.OnConflict
// documentation for more info.
func (u *ChatQuickReplyUpsertBulk) Update(set func(*ChatQuickReplyUpsert)) *ChatQuickReplyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChatQuickReplyUpsert{UpdateSet: update})
	}))
	return u
}

// SetAdminID sets the "admin_id" field.
func (u *ChatQuickReplyUpsertBulk) SetAdminID(v int64) *ChatQuickReplyUpsertBulk {
	return u.Update(func(s *ChatQuickReplyUpsert) {
		s.SetAdminID(v)
	})
}

// AddAdminID adds v to the "admin_id" field.
func (u *ChatQuickReplyUpsertBulk) AddAdminID(v int64) *ChatQuickReplyUpsertBulk {
	return u.Update(func(s *ChatQuickReplyUpsert) {
		s.AddAdminID(v)
	})
}

// UpdateAdminID sets the "admin_id" field to the value that was provided on create.
func (u *ChatQuickReplyUpsertBulk) UpdateAdminID() *ChatQuickReplyUpsertBulk {
	return u.Update(func(s *ChatQuickReplyUpsert) {
		s.UpdateAdminID()
	})
}

// SetTitle sets the "title" field.
func (u *ChatQuickReplyUpsertBulk) SetTitle(v string) *ChatQuickReplyUpsertBulk {
	return u.Update(func(s *ChatQuickReplyUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *ChatQuickReplyUpsertBulk) UpdateTitle() *ChatQuickReplyUpsertBulk {
	return u.Update(func(s *ChatQuickReplyUpsert) {
		s.UpdateTitle()
	})
}

// SetContent sets the "content" field.
func (u *ChatQuickReplyUpsertBulk) SetContent(v string) *ChatQuickReplyUpsertBulk {
	return u.Update(func(s *ChatQuickReplyUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *ChatQuickReplyUpsertBulk) UpdateContent() *ChatQuickReplyUpsertBulk {
	return u.Update(func(s *ChatQuickReplyUpsert) {
		s.UpdateContent()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *ChatQuickReplyUpsertBulk) SetSortOrder(v int) *ChatQuickReplyUpsertBulk {
	return u.Update(func(s *ChatQuickReplyUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *ChatQuickReplyUpsertBulk) AddSortOrder(v int) *ChatQuickReplyUpsertBulk {
	return u.Update(func(s *ChatQuickReplyUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *ChatQuickReplyUpsertBulk) UpdateSortOrder() *ChatQuickReplyUpsertBulk {
	return u.Update(func(s *ChatQuickReplyUpsert) {
		s.UpdateSortOrder()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ChatQuickReplyUpsertBulk) SetUpdatedAt(v time.Time) *ChatQuickReplyUpsertBulk {
	return u.Update(func(s *ChatQuickReplyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChatQuickReplyUpsertBulk) UpdateUpdatedAt() *ChatQuickReplyUpsertBulk {
	return u.Update(func(s *ChatQuickReplyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ChatQuickReplyUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ChatQuickReplyCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChatQuickReplyCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChatQuickReplyUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
