// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/chatasset"
	"github.com/Wei-Shaw/sub2api/ent/chatmessage"
	"github.com/Wei-Shaw/sub2api/ent/chatmessageasset"
)

// ChatMessageAsset is the model entity for the ChatMessageAsset schema.
type ChatMessageAsset struct {
	config `json:"-"`
	// MessageID holds the value of the "message_id" field.
	MessageID int64 `json:"message_id,omitempty"`
	// AssetID holds the value of the "asset_id" field.
	AssetID int64 `json:"asset_id,omitempty"`
	// SortOrder holds the value of the "sort_order" field.
	SortOrder int `json:"sort_order,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ChatMessageAssetQuery when eager-loading is set.
	Edges        ChatMessageAssetEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ChatMessageAssetEdges holds the relations/edges for other nodes in the graph.
type ChatMessageAssetEdges struct {
	// Message holds the value of the message edge.
	Message *ChatMessage `json:"message,omitempty"`
	// Asset holds the value of the asset edge.
	Asset *ChatAsset `json:"asset,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// MessageOrErr returns the Message value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ChatMessageAssetEdges) MessageOrErr() (*ChatMessage, error) {
	if e.Message != nil {
		return e.Message, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: chatmessage.Label}
	}
	return nil, &NotLoadedError{edge: "message"}
}

// AssetOrErr returns the Asset value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ChatMessageAssetEdges) AssetOrErr() (*ChatAsset, error) {
	if e.Asset != nil {
		return e.Asset, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: chatasset.Label}
	}
	return nil, &NotLoadedError{edge: "asset"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ChatMessageAsset) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case chatmessageasset.FieldMessageID, chatmessageasset.FieldAssetID, chatmessageasset.FieldSortOrder:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ChatMessageAsset fields.
func (_m *ChatMessageAsset) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case chatmessageasset.FieldMessageID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field message_id", values[i])
			} else if value.Valid {
				_m.MessageID = value.Int64
			}
		case chatmessageasset.FieldAssetID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field asset_id", values[i])
			} else if value.Valid {
				_m.AssetID = value.Int64
			}
		case chatmessageasset.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				_m.SortOrder = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ChatMessageAsset.
// This includes values selected through modifiers, order, etc.
func (_m *ChatMessageAsset) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryMessage queries the "message" edge of the ChatMessageAsset entity.
func (_m *ChatMessageAsset) QueryMessage() *ChatMessageQuery {
	return NewChatMessageAssetClient(_m.config).QueryMessage(_m)
}

// QueryAsset queries the "asset" edge of the ChatMessageAsset entity.
func (_m *ChatMessageAsset) QueryAsset() *ChatAssetQuery {
	return NewChatMessageAssetClient(_m.config).QueryAsset(_m)
}

// Update returns a builder for updating this ChatMessageAsset.
// Note that you need to call ChatMessageAsset.Unwrap() before calling this method if this ChatMessageAsset
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ChatMessageAsset) Update() *ChatMessageAssetUpdateOne {
	return NewChatMessageAssetClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ChatMessageAsset entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ChatMessageAsset) Unwrap() *ChatMessageAsset {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ChatMessageAsset is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ChatMessageAsset) String() string {
	var builder strings.Builder
	builder.WriteString("ChatMessageAsset(")
	builder.WriteString("message_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.MessageID))
	builder.WriteString(", ")
	builder.WriteString("asset_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AssetID))
	builder.WriteString(", ")
	builder.WriteString("sort_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortOrder))
	builder.WriteByte(')')
	return builder.String()
}

// ChatMessageAssets is a parsable slice of ChatMessageAsset.
type ChatMessageAssets []*ChatMessageAsset
