// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/chatconversation"
	"github.com/Wei-Shaw/sub2api/ent/chatmessage"
)

// ChatMessage is the model entity for the ChatMessage schema.
type ChatMessage struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// ConversationID holds the value of the "conversation_id" field.
	ConversationID int64 `json:"conversation_id,omitempty"`
	// 发送者角色：user=会话所属用户，admin=任意管理员客服
	SenderType chatmessage.SenderType `json:"sender_type,omitempty"`
	// 发送者用户ID（管理员发送时为该管理员的用户ID）
	SenderID int64 `json:"sender_id,omitempty"`
	// Content holds the value of the "content" field.
	Content string `json:"content,omitempty"`
	// Kind holds the value of the "kind" field.
	Kind chatmessage.Kind `json:"kind,omitempty"`
	// ReplyToID holds the value of the "reply_to_id" field.
	ReplyToID *int64 `json:"reply_to_id,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata json.RawMessage `json:"metadata,omitempty"`
	// IdempotencyKey holds the value of the "idempotency_key" field.
	IdempotencyKey *string `json:"idempotency_key,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ChatMessageQuery when eager-loading is set.
	Edges        ChatMessageEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ChatMessageEdges holds the relations/edges for other nodes in the graph.
type ChatMessageEdges struct {
	// Conversation holds the value of the conversation edge.
	Conversation *ChatConversation `json:"conversation,omitempty"`
	// Assets holds the value of the assets edge.
	Assets []*ChatAsset `json:"assets,omitempty"`
	// MessageAssets holds the value of the message_assets edge.
	MessageAssets []*ChatMessageAsset `json:"message_assets,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// ConversationOrErr returns the Conversation value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ChatMessageEdges) ConversationOrErr() (*ChatConversation, error) {
	if e.Conversation != nil {
		return e.Conversation, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: chatconversation.Label}
	}
	return nil, &NotLoadedError{edge: "conversation"}
}

// AssetsOrErr returns the Assets value or an error if the edge
// was not loaded in eager-loading.
func (e ChatMessageEdges) AssetsOrErr() ([]*ChatAsset, error) {
	if e.loadedTypes[1] {
		return e.Assets, nil
	}
	return nil, &NotLoadedError{edge: "assets"}
}

// MessageAssetsOrErr returns the MessageAssets value or an error if the edge
// was not loaded in eager-loading.
func (e ChatMessageEdges) MessageAssetsOrErr() ([]*ChatMessageAsset, error) {
	if e.loadedTypes[2] {
		return e.MessageAssets, nil
	}
	return nil, &NotLoadedError{edge: "message_assets"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ChatMessage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case chatmessage.FieldMetadata:
			values[i] = new([]byte)
		case chatmessage.FieldID, chatmessage.FieldConversationID, chatmessage.FieldSenderID, chatmessage.FieldReplyToID:
			values[i] = new(sql.NullInt64)
		case chatmessage.FieldSenderType, chatmessage.FieldContent, chatmessage.FieldKind, chatmessage.FieldIdempotencyKey:
			values[i] = new(sql.NullString)
		case chatmessage.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ChatMessage fields.
func (_m *ChatMessage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case chatmessage.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case chatmessage.FieldConversationID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field conversation_id", values[i])
			} else if value.Valid {
				_m.ConversationID = value.Int64
			}
		case chatmessage.FieldSenderType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sender_type", values[i])
			} else if value.Valid {
				_m.SenderType = chatmessage.SenderType(value.String)
			}
		case chatmessage.FieldSenderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sender_id", values[i])
			} else if value.Valid {
				_m.SenderID = value.Int64
			}
		case chatmessage.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				_m.Content = value.String
			}
		case chatmessage.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				_m.Kind = chatmessage.Kind(value.String)
			}
		case chatmessage.FieldReplyToID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field reply_to_id", values[i])
			} else if value.Valid {
				_m.ReplyToID = new(int64)
				*_m.ReplyToID = value.Int64
			}
		case chatmessage.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case chatmessage.FieldIdempotencyKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field idempotency_key", values[i])
			} else if value.Valid {
				_m.IdempotencyKey = new(string)
				*_m.IdempotencyKey = value.String
			}
		case chatmessage.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ChatMessage.
// This includes values selected through modifiers, order, etc.
func (_m *ChatMessage) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryConversation queries the "conversation" edge of the ChatMessage entity.
func (_m *ChatMessage) QueryConversation() *ChatConversationQuery {
	return NewChatMessageClient(_m.config).QueryConversation(_m)
}

// QueryAssets queries the "assets" edge of the ChatMessage entity.
func (_m *ChatMessage) QueryAssets() *ChatAssetQuery {
	return NewChatMessageClient(_m.config).QueryAssets(_m)
}

// QueryMessageAssets queries the "message_assets" edge of the ChatMessage entity.
func (_m *ChatMessage) QueryMessageAssets() *ChatMessageAssetQuery {
	return NewChatMessageClient(_m.config).QueryMessageAssets(_m)
}

// Update returns a builder for updating this ChatMessage.
// Note that you need to call ChatMessage.Unwrap() before calling this method if this ChatMessage
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ChatMessage) Update() *ChatMessageUpdateOne {
	return NewChatMessageClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ChatMessage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ChatMessage) Unwrap() *ChatMessage {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ChatMessage is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ChatMessage) String() string {
	var builder strings.Builder
	builder.WriteString("ChatMessage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("conversation_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConversationID))
	builder.WriteString(", ")
	builder.WriteString("sender_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.SenderType))
	builder.WriteString(", ")
	builder.WriteString("sender_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SenderID))
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(_m.Content)
	builder.WriteString(", ")
	builder.WriteString("kind=")
	builder.WriteString(fmt.Sprintf("%v", _m.Kind))
	builder.WriteString(", ")
	if v := _m.ReplyToID; v != nil {
		builder.WriteString("reply_to_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	if v := _m.IdempotencyKey; v != nil {
		builder.WriteString("idempotency_key=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ChatMessages is a parsable slice of ChatMessage.
type ChatMessages []*ChatMessage
