// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/chatasset"
	"github.com/Wei-Shaw/sub2api/ent/chatmessage"
	"github.com/Wei-Shaw/sub2api/ent/chatmessageasset"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ChatMessageAssetQuery is the builder for querying ChatMessageAsset entities.
type ChatMessageAssetQuery struct {
	config
	ctx         *QueryContext
	order       []chatmessageasset.OrderOption
	inters      []Interceptor
	predicates  []predicate.ChatMessageAsset
	withMessage *ChatMessageQuery
	withAsset   *ChatAssetQuery
	modifiers   []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ChatMessageAssetQuery builder.
func (_q *ChatMessageAssetQuery) Where(ps ...predicate.ChatMessageAsset) *ChatMessageAssetQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ChatMessageAssetQuery) Limit(limit int) *ChatMessageAssetQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ChatMessageAssetQuery) Offset(offset int) *ChatMessageAssetQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ChatMessageAssetQuery) Unique(unique bool) *ChatMessageAssetQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ChatMessageAssetQuery) Order(o ...chatmessageasset.OrderOption) *ChatMessageAssetQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryMessage chains the current query on the "message" edge.
func (_q *ChatMessageAssetQuery) QueryMessage() *ChatMessageQuery {
	query := (&ChatMessageClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(chatmessageasset.Table, chatmessageasset.MessageColumn, selector),
			sqlgraph.To(chatmessage.Table, chatmessage.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, chatmessageasset.MessageTable, chatmessageasset.MessageColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAsset chains the current query on the "asset" edge.
func (_q *ChatMessageAssetQuery) QueryAsset() *ChatAssetQuery {
	query := (&ChatAssetClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(chatmessageasset.Table, chatmessageasset.AssetColumn, selector),
			sqlgraph.To(chatasset.Table, chatasset.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, chatmessageasset.AssetTable, chatmessageasset.AssetColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ChatMessageAsset entity from the query.
// Returns a *NotFoundError when no ChatMessageAsset was found.
func (_q *ChatMessageAssetQuery) First(ctx context.Context) (*ChatMessageAsset, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{chatmessageasset.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ChatMessageAssetQuery) FirstX(ctx context.Context) *ChatMessageAsset {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// Only returns a single ChatMessageAsset entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ChatMessageAsset entity is found.
// Returns a *NotFoundError when no ChatMessageAsset entities are found.
func (_q *ChatMessageAssetQuery) Only(ctx context.Context) (*ChatMessageAsset, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{chatmessageasset.Label}
	default:
		return nil, &NotSingularError{chatmessageasset.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ChatMessageAssetQuery) OnlyX(ctx context.Context) *ChatMessageAsset {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// All executes the query and returns a list of ChatMessageAssets.
func (_q *ChatMessageAssetQuery) All(ctx context.Context) ([]*ChatMessageAsset, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ChatMessageAsset, *ChatMessageAssetQuery]()
	return withInterceptors[[]*ChatMessageAsset](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ChatMessageAssetQuery) AllX(ctx context.Context) []*ChatMessageAsset {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// Count returns the count of the given query.
func (_q *ChatMessageAssetQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ChatMessageAssetQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ChatMessageAssetQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ChatMessageAssetQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.First(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ChatMessageAssetQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ChatMessageAssetQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ChatMessageAssetQuery) Clone() *ChatMessageAssetQuery {
	if _q == nil {
		return nil
	}
	return &ChatMessageAssetQuery{
		config:      _q.config,
		ctx:         _q.ctx.Clone(),
		order:       append([]chatmessageasset.OrderOption{}, _q.order...),
		inters:      append([]Interceptor{}, _q.inters...),
		predicates:  append([]predicate.ChatMessageAsset{}, _q.predicates...),
		withMessage: _q.withMessage.Clone(),
		withAsset:   _q.withAsset.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithMessage tells the query-builder to eager-load the nodes that are connected to
// the "message" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ChatMessageAssetQuery) WithMessage(opts ...func(*ChatMessageQuery)) *ChatMessageAssetQuery {
	query := (&ChatMessageClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withMessage = query
	return _q
}

// WithAsset tells the query-builder to eager-load the nodes that are connected to
// the "asset" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ChatMessageAssetQuery) WithAsset(opts ...func(*ChatAssetQuery)) *ChatMessageAssetQuery {
	query := (&ChatAssetClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAsset = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		MessageID int64 `json:"message_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ChatMessageAsset.Query().
//		GroupBy(chatmessageasset.FieldMessageID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ChatMessageAssetQuery) GroupBy(field string, fields ...string) *ChatMessageAssetGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ChatMessageAssetGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = chatmessageasset.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		MessageID int64 `json:"message_id,omitempty"`
//	}
//
//	client.ChatMessageAsset.Query().
//		Select(chatmessageasset.FieldMessageID).
//		Scan(ctx, &v)
func (_q *ChatMessageAssetQuery) Select(fields ...string) *ChatMessageAssetSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ChatMessageAssetSelect{ChatMessageAssetQuery: _q}
	sbuild.label = chatmessageasset.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ChatMessageAssetSelect configured with the given aggregations.
func (_q *ChatMessageAssetQuery) Aggregate(fns ...AggregateFunc) *ChatMessageAssetSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ChatMessageAssetQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !chatmessageasset.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ChatMessageAssetQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ChatMessageAsset, error) {
	var (
		nodes       = []*ChatMessageAsset{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withMessage != nil,
			_q.withAsset != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ChatMessageAsset).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ChatMessageAsset{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withMessage; query != nil {
		if err := _q.loadMessage(ctx, query, nodes, nil,
			func(n *ChatMessageAsset, e *ChatMessage) { n.Edges.Message = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withAsset; query != nil {
		if err := _q.loadAsset(ctx, query, nodes, nil,
			func(n *ChatMessageAsset, e *ChatAsset) { n.Edges.Asset = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ChatMessageAssetQuery) loadMessage(ctx context.Context, query *ChatMessageQuery, nodes []*ChatMessageAsset, init func(*ChatMessageAsset), assign func(*ChatMessageAsset, *ChatMessage)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*ChatMessageAsset)
	for i := range nodes {
		fk := nodes[i].MessageID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(chatmessage.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "message_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ChatMessageAssetQuery) loadAsset(ctx context.Context, query *ChatAssetQuery, nodes []*ChatMessageAsset, init func(*ChatMessageAsset), assign func(*ChatMessageAsset, *ChatAsset)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*ChatMessageAsset)
	for i := range nodes {
		fk := nodes[i].AssetID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(chatasset.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "asset_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *ChatMessageAssetQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Unique = false
	_spec.Node.Columns = nil
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ChatMessageAssetQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(chatmessageasset.Table, chatmessageasset.Columns, nil)
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		for i := range fields {
			_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
		}
		if _q.withMessage != nil {
			_spec.Node.AddColumnOnce(chatmessageasset.FieldMessageID)
		}
		if _q.withAsset != nil {
			_spec.Node.AddColumnOnce(chatmessageasset.FieldAssetID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ChatMessageAssetQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(chatmessageasset.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = chatmessageasset.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *ChatMessageAssetQuery) ForUpdate(opts ...sql.LockOption) *ChatMessageAssetQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *ChatMessageAssetQuery) ForShare(opts ...sql.LockOption) *ChatMessageAssetQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// ChatMessageAssetGroupBy is the group-by builder for ChatMessageAsset entities.
type ChatMessageAssetGroupBy struct {
	selector
	build *ChatMessageAssetQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ChatMessageAssetGroupBy) Aggregate(fns ...AggregateFunc) *ChatMessageAssetGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ChatMessageAssetGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ChatMessageAssetQuery, *ChatMessageAssetGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ChatMessageAssetGroupBy) sqlScan(ctx context.Context, root *ChatMessageAssetQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ChatMessageAssetSelect is the builder for selecting fields of ChatMessageAsset entities.
type ChatMessageAssetSelect struct {
	*ChatMessageAssetQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ChatMessageAssetSelect) Aggregate(fns ...AggregateFunc) *ChatMessageAssetSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ChatMessageAssetSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ChatMessageAssetQuery, *ChatMessageAssetSelect](ctx, _s.ChatMessageAssetQuery, _s, _s.inters, v)
}

func (_s *ChatMessageAssetSelect) sqlScan(ctx context.Context, root *ChatMessageAssetQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
