// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/chatasset"
)

// ChatAsset is the model entity for the ChatAsset schema.
type ChatAsset struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Scope holds the value of the "scope" field.
	Scope chatasset.Scope `json:"scope,omitempty"`
	// ConversationID holds the value of the "conversation_id" field.
	ConversationID *int64 `json:"conversation_id,omitempty"`
	// UploadedBy holds the value of the "uploaded_by" field.
	UploadedBy *int64 `json:"uploaded_by,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// MimeType holds the value of the "mime_type" field.
	MimeType string `json:"mime_type,omitempty"`
	// Size holds the value of the "size" field.
	Size int `json:"size,omitempty"`
	// Data holds the value of the "data" field.
	Data []byte `json:"-"`
	// Collection holds the value of the "collection" field.
	Collection string `json:"collection,omitempty"`
	// CatalogVisible holds the value of the "catalog_visible" field.
	CatalogVisible bool `json:"catalog_visible,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ChatAssetQuery when eager-loading is set.
	Edges        ChatAssetEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ChatAssetEdges holds the relations/edges for other nodes in the graph.
type ChatAssetEdges struct {
	// Messages holds the value of the messages edge.
	Messages []*ChatMessage `json:"messages,omitempty"`
	// MessageAssets holds the value of the message_assets edge.
	MessageAssets []*ChatMessageAsset `json:"message_assets,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// MessagesOrErr returns the Messages value or an error if the edge
// was not loaded in eager-loading.
func (e ChatAssetEdges) MessagesOrErr() ([]*ChatMessage, error) {
	if e.loadedTypes[0] {
		return e.Messages, nil
	}
	return nil, &NotLoadedError{edge: "messages"}
}

// MessageAssetsOrErr returns the MessageAssets value or an error if the edge
// was not loaded in eager-loading.
func (e ChatAssetEdges) MessageAssetsOrErr() ([]*ChatMessageAsset, error) {
	if e.loadedTypes[1] {
		return e.MessageAssets, nil
	}
	return nil, &NotLoadedError{edge: "message_assets"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ChatAsset) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case chatasset.FieldData:
			values[i] = new([]byte)
		case chatasset.FieldCatalogVisible:
			values[i] = new(sql.NullBool)
		case chatasset.FieldID, chatasset.FieldConversationID, chatasset.FieldUploadedBy, chatasset.FieldSize:
			values[i] = new(sql.NullInt64)
		case chatasset.FieldScope, chatasset.FieldName, chatasset.FieldMimeType, chatasset.FieldCollection:
			values[i] = new(sql.NullString)
		case chatasset.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ChatAsset fields.
func (_m *ChatAsset) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case chatasset.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case chatasset.FieldScope:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field scope", values[i])
			} else if value.Valid {
				_m.Scope = chatasset.Scope(value.String)
			}
		case chatasset.FieldConversationID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field conversation_id", values[i])
			} else if value.Valid {
				_m.ConversationID = new(int64)
				*_m.ConversationID = value.Int64
			}
		case chatasset.FieldUploadedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field uploaded_by", values[i])
			} else if value.Valid {
				_m.UploadedBy = new(int64)
				*_m.UploadedBy = value.Int64
			}
		case chatasset.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case chatasset.FieldMimeType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mime_type", values[i])
			} else if value.Valid {
				_m.MimeType = value.String
			}
		case chatasset.FieldSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field size", values[i])
			} else if value.Valid {
				_m.Size = int(value.Int64)
			}
		case chatasset.FieldData:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field data", values[i])
			} else if value != nil {
				_m.Data = *value
			}
		case chatasset.FieldCollection:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field collection", values[i])
			} else if value.Valid {
				_m.Collection = value.String
			}
		case chatasset.FieldCatalogVisible:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field catalog_visible", values[i])
			} else if value.Valid {
				_m.CatalogVisible = value.Bool
			}
		case chatasset.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ChatAsset.
// This includes values selected through modifiers, order, etc.
func (_m *ChatAsset) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryMessages queries the "messages" edge of the ChatAsset entity.
func (_m *ChatAsset) QueryMessages() *ChatMessageQuery {
	return NewChatAssetClient(_m.config).QueryMessages(_m)
}

// QueryMessageAssets queries the "message_assets" edge of the ChatAsset entity.
func (_m *ChatAsset) QueryMessageAssets() *ChatMessageAssetQuery {
	return NewChatAssetClient(_m.config).QueryMessageAssets(_m)
}

// Update returns a builder for updating this ChatAsset.
// Note that you need to call ChatAsset.Unwrap() before calling this method if this ChatAsset
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ChatAsset) Update() *ChatAssetUpdateOne {
	return NewChatAssetClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ChatAsset entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ChatAsset) Unwrap() *ChatAsset {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ChatAsset is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ChatAsset) String() string {
	var builder strings.Builder
	builder.WriteString("ChatAsset(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("scope=")
	builder.WriteString(fmt.Sprintf("%v", _m.Scope))
	builder.WriteString(", ")
	if v := _m.ConversationID; v != nil {
		builder.WriteString("conversation_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UploadedBy; v != nil {
		builder.WriteString("uploaded_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("mime_type=")
	builder.WriteString(_m.MimeType)
	builder.WriteString(", ")
	builder.WriteString("size=")
	builder.WriteString(fmt.Sprintf("%v", _m.Size))
	builder.WriteString(", ")
	builder.WriteString("data=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("collection=")
	builder.WriteString(_m.Collection)
	builder.WriteString(", ")
	builder.WriteString("catalog_visible=")
	builder.WriteString(fmt.Sprintf("%v", _m.CatalogVisible))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ChatAssets is a parsable slice of ChatAsset.
type ChatAssets []*ChatAsset
