// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/chatasset"
	"github.com/Wei-Shaw/sub2api/ent/chatmessage"
)

// ChatAssetCreate is the builder for creating a ChatAsset entity.
type ChatAssetCreate struct {
	config
	mutation *ChatAssetMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetScope sets the "scope" field.
func (_c *ChatAssetCreate) SetScope(v chatasset.Scope) *ChatAssetCreate {
	_c.mutation.SetScope(v)
	return _c
}

// SetConversationID sets the "conversation_id" field.
func (_c *ChatAssetCreate) SetConversationID(v int64) *ChatAssetCreate {
	_c.mutation.SetConversationID(v)
	return _c
}

// SetNillableConversationID sets the "conversation_id" field if the given value is not nil.
func (_c *ChatAssetCreate) SetNillableConversationID(v *int64) *ChatAssetCreate {
	if v != nil {
		_c.SetConversationID(*v)
	}
	return _c
}

// SetUploadedBy sets the "uploaded_by" field.
func (_c *ChatAssetCreate) SetUploadedBy(v int64) *ChatAssetCreate {
	_c.mutation.SetUploadedBy(v)
	return _c
}

// SetNillableUploadedBy sets the "uploaded_by" field if the given value is not nil.
func (_c *ChatAssetCreate) SetNillableUploadedBy(v *int64) *ChatAssetCreate {
	if v != nil {
		_c.SetUploadedBy(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *ChatAssetCreate) SetName(v string) *ChatAssetCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetMimeType sets the "mime_type" field.
func (_c *ChatAssetCreate) SetMimeType(v string) *ChatAssetCreate {
	_c.mutation.SetMimeType(v)
	return _c
}

// SetSize sets the "size" field.
func (_c *ChatAssetCreate) SetSize(v int) *ChatAssetCreate {
	_c.mutation.SetSize(v)
	return _c
}

// SetData sets the "data" field.
func (_c *ChatAssetCreate) SetData(v []byte) *ChatAssetCreate {
	_c.mutation.SetData(v)
	return _c
}

// SetCollection sets the "collection" field.
func (_c *ChatAssetCreate) SetCollection(v string) *ChatAssetCreate {
	_c.mutation.SetCollection(v)
	return _c
}

// SetNillableCollection sets the "collection" field if the given value is not nil.
func (_c *ChatAssetCreate) SetNillableCollection(v *string) *ChatAssetCreate {
	if v != nil {
		_c.SetCollection(*v)
	}
	return _c
}

// SetCatalogVisible sets the "catalog_visible" field.
func (_c *ChatAssetCreate) SetCatalogVisible(v bool) *ChatAssetCreate {
	_c.mutation.SetCatalogVisible(v)
	return _c
}

// SetNillableCatalogVisible sets the "catalog_visible" field if the given value is not nil.
func (_c *ChatAssetCreate) SetNillableCatalogVisible(v *bool) *ChatAssetCreate {
	if v != nil {
		_c.SetCatalogVisible(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ChatAssetCreate) SetCreatedAt(v time.Time) *ChatAssetCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ChatAssetCreate) SetNillableCreatedAt(v *time.Time) *ChatAssetCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// AddMessageIDs adds the "messages" edge to the ChatMessage entity by IDs.
func (_c *ChatAssetCreate) AddMessageIDs(ids ...int64) *ChatAssetCreate {
	_c.mutation.AddMessageIDs(ids...)
	return _c
}

// AddMessages adds the "messages" edges to the ChatMessage entity.
func (_c *ChatAssetCreate) AddMessages(v ...*ChatMessage) *ChatAssetCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMessageIDs(ids...)
}

// Mutation returns the ChatAssetMutation object of the builder.
func (_c *ChatAssetCreate) Mutation() *ChatAssetMutation {
	return _c.mutation
}

// Save creates the ChatAsset in the database.
func (_c *ChatAssetCreate) Save(ctx context.Context) (*ChatAsset, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChatAssetCreate) SaveX(ctx context.Context) *ChatAsset {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChatAssetCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChatAssetCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ChatAssetCreate) defaults() {
	if _, ok := _c.mutation.Collection(); !ok {
		v := chatasset.DefaultCollection
		_c.mutation.SetCollection(v)
	}
	if _, ok := _c.mutation.CatalogVisible(); !ok {
		v := chatasset.DefaultCatalogVisible
		_c.mutation.SetCatalogVisible(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := chatasset.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChatAssetCreate) check() error {
	if _, ok := _c.mutation.Scope(); !ok {
		return &ValidationError{Name: "scope", err: errors.New(`ent: missing required field "ChatAsset.scope"`)}
	}
	if v, ok := _c.mutation.Scope(); ok {
		if err := chatasset.ScopeValidator(v); err != nil {
			return &ValidationError{Name: "scope", err: fmt.Errorf(`ent: validator failed for field "ChatAsset.scope": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ChatAsset.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := chatasset.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ChatAsset.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MimeType(); !ok {
		return &ValidationError{Name: "mime_type", err: errors.New(`ent: missing required field "ChatAsset.mime_type"`)}
	}
	if v, ok := _c.mutation.MimeType(); ok {
		if err := chatasset.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "ChatAsset.mime_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Size(); !ok {
		return &ValidationError{Name: "size", err: errors.New(`ent: missing required field "ChatAsset.size"`)}
	}
	if _, ok := _c.mutation.Data(); !ok {
		return &ValidationError{Name: "data", err: errors.New(`ent: missing required field "ChatAsset.data"`)}
	}
	if _, ok := _c.mutation.Collection(); !ok {
		return &ValidationError{Name: "collection", err: errors.New(`ent: missing required field "ChatAsset.collection"`)}
	}
	if v, ok := _c.mutation.Collection(); ok {
		if err := chatasset.CollectionValidator(v); err != nil {
			return &ValidationError{Name: "collection", err: fmt.Errorf(`ent: validator failed for field "ChatAsset.collection": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CatalogVisible(); !ok {
		return &ValidationError{Name: "catalog_visible", err: errors.New(`ent: missing required field "ChatAsset.catalog_visible"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ChatAsset.created_at"`)}
	}
	return nil
}

func (_c *ChatAssetCreate) sqlSave(ctx context.Context) (*ChatAsset, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChatAssetCreate) createSpec() (*ChatAsset, *sqlgraph.CreateSpec) {
	var (
		_node = &ChatAsset{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(chatasset.Table, sqlgraph.NewFieldSpec(chatasset.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Scope(); ok {
		_spec.SetField(chatasset.FieldScope, field.TypeEnum, value)
		_node.Scope = value
	}
	if value, ok := _c.mutation.ConversationID(); ok {
		_spec.SetField(chatasset.FieldConversationID, field.TypeInt64, value)
		_node.ConversationID = &value
	}
	if value, ok := _c.mutation.UploadedBy(); ok {
		_spec.SetField(chatasset.FieldUploadedBy, field.TypeInt64, value)
		_node.UploadedBy = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(chatasset.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.MimeType(); ok {
		_spec.SetField(chatasset.FieldMimeType, field.TypeString, value)
		_node.MimeType = value
	}
	if value, ok := _c.mutation.Size(); ok {
		_spec.SetField(chatasset.FieldSize, field.TypeInt, value)
		_node.Size = value
	}
	if value, ok := _c.mutation.Data(); ok {
		_spec.SetField(chatasset.FieldData, field.TypeBytes, value)
		_node.Data = value
	}
	if value, ok := _c.mutation.Collection(); ok {
		_spec.SetField(chatasset.FieldCollection, field.TypeString, value)
		_node.Collection = value
	}
	if value, ok := _c.mutation.CatalogVisible(); ok {
		_spec.SetField(chatasset.FieldCatalogVisible, field.TypeBool, value)
		_node.CatalogVisible = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(chatasset.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   chatasset.MessagesTable,
			Columns: chatasset.MessagesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ChatMessageAssetCreate{config: _c.config, mutation: newChatMessageAssetMutation(_c.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ChatAsset.Create().
//		SetScope(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChatAssetUpsert) {
//			SetScope(v+v).
//		}).
//		Exec(ctx)
func (_c *ChatAssetCreate) OnConflict(opts ...sql.ConflictOption) *ChatAssetUpsertOne {
	_c.conflict = opts
	return &ChatAssetUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ChatAsset.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChatAssetCreate) OnConflictColumns(columns ...string) *ChatAssetUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChatAssetUpsertOne{
		create: _c,
	}
}

type (
	// ChatAssetUpsertOne is the builder for "upsert"-ing
	//  one ChatAsset node.
	ChatAssetUpsertOne struct {
		create *ChatAssetCreate
	}

	// ChatAssetUpsert is the "OnConflict" setter.
	ChatAssetUpsert struct {
		*sql.UpdateSet
	}
)

// SetScope sets the "scope" field.
func (u *ChatAssetUpsert) SetScope(v chatasset.Scope) *ChatAssetUpsert {
	u.Set(chatasset.FieldScope, v)
	return u
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *ChatAssetUpsert) UpdateScope() *ChatAssetUpsert {
	u.SetExcluded(chatasset.FieldScope)
	return u
}

// SetConversationID sets the "conversation_id" field.
func (u *ChatAssetUpsert) SetConversationID(v int64) *ChatAssetUpsert {
	u.Set(chatasset.FieldConversationID, v)
	return u
}

// UpdateConversationID sets the "conversation_id" field to the value that was provided on create.
func (u *ChatAssetUpsert) UpdateConversationID() *ChatAssetUpsert {
	u.SetExcluded(chatasset.FieldConversationID)
	return u
}

// AddConversationID adds v to the "conversation_id" field.
func (u *ChatAssetUpsert) AddConversationID(v int64) *ChatAssetUpsert {
	u.Add(chatasset.FieldConversationID, v)
	return u
}

// ClearConversationID clears the value of the "conversation_id" field.
func (u *ChatAssetUpsert) ClearConversationID() *ChatAssetUpsert {
	u.SetNull(chatasset.FieldConversationID)
	return u
}

// SetUploadedBy sets the "uploaded_by" field.
func (u *ChatAssetUpsert) SetUploadedBy(v int64) *ChatAssetUpsert {
	u.Set(chatasset.FieldUploadedBy, v)
	return u
}

// UpdateUploadedBy sets the "uploaded_by" field to the value that was provided on create.
func (u *ChatAssetUpsert) UpdateUploadedBy() *ChatAssetUpsert {
	u.SetExcluded(chatasset.FieldUploadedBy)
	return u
}

// AddUploadedBy adds v to the "uploaded_by" field.
func (u *ChatAssetUpsert) AddUploadedBy(v int64) *ChatAssetUpsert {
	u.Add(chatasset.FieldUploadedBy, v)
	return u
}

// ClearUploadedBy clears the value of the "uploaded_by" field.
func (u *ChatAssetUpsert) ClearUploadedBy() *ChatAssetUpsert {
	u.SetNull(chatasset.FieldUploadedBy)
	return u
}

// SetName sets the "name" field.
func (u *ChatAssetUpsert) SetName(v string) *ChatAssetUpsert {
	u.Set(chatasset.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ChatAssetUpsert) UpdateName() *ChatAssetUpsert {
	u.SetExcluded(chatasset.FieldName)
	return u
}

// SetMimeType sets the "mime_type" field.
func (u *ChatAssetUpsert) SetMimeType(v string) *ChatAssetUpsert {
	u.Set(chatasset.FieldMimeType, v)
	return u
}

// UpdateMimeType sets the "mime_type" field to the value that was provided on create.
func (u *ChatAssetUpsert) UpdateMimeType() *ChatAssetUpsert {
	u.SetExcluded(chatasset.FieldMimeType)
	return u
}

// SetSize sets the "size" field.
func (u *ChatAssetUpsert) SetSize(v int) *ChatAssetUpsert {
	u.Set(chatasset.FieldSize, v)
	return u
}

// UpdateSize sets the "size" field to the value that was provided on create.
func (u *ChatAssetUpsert) UpdateSize() *ChatAssetUpsert {
	u.SetExcluded(chatasset.FieldSize)
	return u
}

// AddSize adds v to the "size" field.
func (u *ChatAssetUpsert) AddSize(v int) *ChatAssetUpsert {
	u.Add(chatasset.FieldSize, v)
	return u
}

// SetData sets the "data" field.
func (u *ChatAssetUpsert) SetData(v []byte) *ChatAssetUpsert {
	u.Set(chatasset.FieldData, v)
	return u
}

// UpdateData sets the "data" field to the value that was provided on create.
func (u *ChatAssetUpsert) UpdateData() *ChatAssetUpsert {
	u.SetExcluded(chatasset.FieldData)
	return u
}

// SetCollection sets the "collection" field.
func (u *ChatAssetUpsert) SetCollection(v string) *ChatAssetUpsert {
	u.Set(chatasset.FieldCollection, v)
	return u
}

// UpdateCollection sets the "collection" field to the value that was provided on create.
func (u *ChatAssetUpsert) UpdateCollection() *ChatAssetUpsert {
	u.SetExcluded(chatasset.FieldCollection)
	return u
}

// SetCatalogVisible sets the "catalog_visible" field.
func (u *ChatAssetUpsert) SetCatalogVisible(v bool) *ChatAssetUpsert {
	u.Set(chatasset.FieldCatalogVisible, v)
	return u
}

// UpdateCatalogVisible sets the "catalog_visible" field to the value that was provided on create.
func (u *ChatAssetUpsert) UpdateCatalogVisible() *ChatAssetUpsert {
	u.SetExcluded(chatasset.FieldCatalogVisible)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ChatAsset.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ChatAssetUpsertOne) UpdateNewValues() *ChatAssetUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(chatasset.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ChatAsset.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ChatAssetUpsertOne) Ignore() *ChatAssetUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChatAssetUpsertOne) DoNothing() *ChatAssetUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChatAssetCreate.OnConflict
// documentation for more info.
func (u *ChatAssetUpsertOne) Update(set func(*ChatAssetUpsert)) *ChatAssetUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChatAssetUpsert{UpdateSet: update})
	}))
	return u
}

// SetScope sets the "scope" field.
func (u *ChatAssetUpsertOne) SetScope(v chatasset.Scope) *ChatAssetUpsertOne {
	return u.Update(func(s *ChatAssetUpsert) {
		s.SetScope(v)
	})
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *ChatAssetUpsertOne) UpdateScope() *ChatAssetUpsertOne {
	return u.Update(func(s *ChatAssetUpsert) {
		s.UpdateScope()
	})
}

// SetConversationID sets the "conversation_id" field.
func (u *ChatAssetUpsertOne) SetConversationID(v int64) *ChatAssetUpsertOne {
	return u.Update(func(s *ChatAssetUpsert) {
		s.SetConversationID(v)
	})
}

// AddConversationID adds v to the "conversation_id" field.
func (u *ChatAssetUpsertOne) AddConversationID(v int64) *ChatAssetUpsertOne {
	return u.Update(func(s *ChatAssetUpsert) {
		s.AddConversationID(v)
	})
}

// UpdateConversationID sets the "conversation_id" field to the value that was provided on create.
func (u *ChatAssetUpsertOne) UpdateConversationID() *ChatAssetUpsertOne {
	return u.Update(func(s *ChatAssetUpsert) {
		s.UpdateConversationID()
	})
}

// ClearConversationID clears the value of the "conversation_id" field.
func (u *ChatAssetUpsertOne) ClearConversationID() *ChatAssetUpsertOne {
	return u.Update(func(s *ChatAssetUpsert) {
		s.ClearConversationID()
	})
}

// SetUploadedBy sets the "uploaded_by" field.
func (u *ChatAssetUpsertOne) SetUploadedBy(v int64) *ChatAssetUpsertOne {
	return u.Update(func(s *ChatAssetUpsert) {
		s.SetUploadedBy(v)
	})
}

// AddUploadedBy adds v to the "uploaded_by" field.
func (u *ChatAssetUpsertOne) AddUploadedBy(v int64) *ChatAssetUpsertOne {
	return u.Update(func(s *ChatAssetUpsert) {
		s.AddUploadedBy(v)
	})
}

// UpdateUploadedBy sets the "uploaded_by" field to the value that was provided on create.
func (u *ChatAssetUpsertOne) UpdateUploadedBy() *ChatAssetUpsertOne {
	return u.Update(func(s *ChatAssetUpsert) {
		s.UpdateUploadedBy()
	})
}

// ClearUploadedBy clears the value of the "uploaded_by" field.
func (u *ChatAssetUpsertOne) ClearUploadedBy() *ChatAssetUpsertOne {
	return u.Update(func(s *ChatAssetUpsert) {
		s.ClearUploadedBy()
	})
}

// SetName sets the "name" field.
func (u *ChatAssetUpsertOne) SetName(v string) *ChatAssetUpsertOne {
	return u.Update(func(s *ChatAssetUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ChatAssetUpsertOne) UpdateName() *ChatAssetUpsertOne {
	return u.Update(func(s *ChatAssetUpsert) {
		s.UpdateName()
	})
}

// SetMimeType sets the "mime_type" field.
func (u *ChatAssetUpsertOne) SetMimeType(v string) *ChatAssetUpsertOne {
	return u.Update(func(s *ChatAssetUpsert) {
		s.SetMimeType(v)
	})
}

// UpdateMimeType sets the "mime_type" field to the value that was provided on create.
func (u *ChatAssetUpsertOne) UpdateMimeType() *ChatAssetUpsertOne {
	return u.Update(func(s *ChatAssetUpsert) {
		s.UpdateMimeType()
	})
}

// SetSize sets the "size" field.
func (u *ChatAssetUpsertOne) SetSize(v int) *ChatAssetUpsertOne {
	return u.Update(func(s *ChatAssetUpsert) {
		s.SetSize(v)
	})
}

// AddSize adds v to the "size" field.
func (u *ChatAssetUpsertOne) AddSize(v int) *ChatAssetUpsertOne {
	return u.Update(func(s *ChatAssetUpsert) {
		s.AddSize(v)
	})
}

// UpdateSize sets the "size" field to the value that was provided on create.
func (u *ChatAssetUpsertOne) UpdateSize() *ChatAssetUpsertOne {
	return u.Update(func(s *ChatAssetUpsert) {
		s.UpdateSize()
	})
}

// SetData sets the "data" field.
func (u *ChatAssetUpsertOne) SetData(v []byte) *ChatAssetUpsertOne {
	return u.Update(func(s *ChatAssetUpsert) {
		s.SetData(v)
	})
}

// UpdateData sets the "data" field to the value that was provided on create.
func (u *ChatAssetUpsertOne) UpdateData() *ChatAssetUpsertOne {
	return u.Update(func(s *ChatAssetUpsert) {
		s.UpdateData()
	})
}

// SetCollection sets the "collection" field.
func (u *ChatAssetUpsertOne) SetCollection(v string) *ChatAssetUpsertOne {
	return u.Update(func(s *ChatAssetUpsert) {
		s.SetCollection(v)
	})
}

// UpdateCollection sets the "collection" field to the value that was provided on create.
func (u *ChatAssetUpsertOne) UpdateCollection() *ChatAssetUpsertOne {
	return u.Update(func(s *ChatAssetUpsert) {
		s.UpdateCollection()
	})
}

// SetCatalogVisible sets the "catalog_visible" field.
func (u *ChatAssetUpsertOne) SetCatalogVisible(v bool) *ChatAssetUpsertOne {
	return u.Update(func(s *ChatAssetUpsert) {
		s.SetCatalogVisible(v)
	})
}

// UpdateCatalogVisible sets the "catalog_visible" field to the value that was provided on create.
func (u *ChatAssetUpsertOne) UpdateCatalogVisible() *ChatAssetUpsertOne {
	return u.Update(func(s *ChatAssetUpsert) {
		s.UpdateCatalogVisible()
	})
}

// Exec executes the query.
func (u *ChatAssetUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChatAssetCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChatAssetUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ChatAssetUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ChatAssetUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ChatAssetCreateBulk is the builder for creating many ChatAsset entities in bulk.
type ChatAssetCreateBulk struct {
	config
	err      error
	builders []*ChatAssetCreate
	conflict []sql.ConflictOption
}

// Save creates the ChatAsset entities in the database.
func (_c *ChatAssetCreateBulk) Save(ctx context.Context) ([]*ChatAsset, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ChatAsset, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChatAssetMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChatAssetCreateBulk) SaveX(ctx context.Context) []*ChatAsset {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChatAssetCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChatAssetCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ChatAsset.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChatAssetUpsert) {
//			SetScope(v+v).
//		}).
//		Exec(ctx)
func (_c *ChatAssetCreateBulk) OnConflict(opts ...sql.ConflictOption) *ChatAssetUpsertBulk {
	_c.conflict = opts
	return &ChatAssetUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ChatAsset.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChatAssetCreateBulk) OnConflictColumns(columns ...string) *ChatAssetUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChatAssetUpsertBulk{
		create: _c,
	}
}

// ChatAssetUpsertBulk is the builder for "upsert"-ing
// a bulk of ChatAsset nodes.
type ChatAssetUpsertBulk struct {
	create *ChatAssetCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ChatAsset.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ChatAssetUpsertBulk) UpdateNewValues() *ChatAssetUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(chatasset.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ChatAsset.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ChatAssetUpsertBulk) Ignore() *ChatAssetUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChatAssetUpsertBulk) DoNothing() *ChatAssetUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChatAssetCreateBulk.OnConflict
// documentation for more info.
func (u *ChatAssetUpsertBulk) Update(set func(*ChatAssetUpsert)) *ChatAssetUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChatAssetUpsert{UpdateSet: update})
	}))
	return u
}

// SetScope sets the "scope" field.
func (u *ChatAssetUpsertBulk) SetScope(v chatasset.Scope) *ChatAssetUpsertBulk {
	return u.Update(func(s *ChatAssetUpsert) {
		s.SetScope(v)
	})
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *ChatAssetUpsertBulk) UpdateScope() *ChatAssetUpsertBulk {
	return u.Update(func(s *ChatAssetUpsert) {
		s.UpdateScope()
	})
}

// SetConversationID sets the "conversation_id" field.
func (u *ChatAssetUpsertBulk) SetConversationID(v int64) *ChatAssetUpsertBulk {
	return u.Update(func(s *ChatAssetUpsert) {
		s.SetConversationID(v)
	})
}

// AddConversationID adds v to the "conversation_id" field.
func (u *ChatAssetUpsertBulk) AddConversationID(v int64) *ChatAssetUpsertBulk {
	return u.Update(func(s *ChatAssetUpsert) {
		s.AddConversationID(v)
	})
}

// UpdateConversationID sets the "conversation_id" field to the value that was provided on create.
func (u *ChatAssetUpsertBulk) UpdateConversationID() *ChatAssetUpsertBulk {
	return u.Update(func(s *ChatAssetUpsert) {
		s.UpdateConversationID()
	})
}

// ClearConversationID clears the value of the "conversation_id" field.
func (u *ChatAssetUpsertBulk) ClearConversationID() *ChatAssetUpsertBulk {
	return u.Update(func(s *ChatAssetUpsert) {
		s.ClearConversationID()
	})
}

// SetUploadedBy sets the "uploaded_by" field.
func (u *ChatAssetUpsertBulk) SetUploadedBy(v int64) *ChatAssetUpsertBulk {
	return u.Update(func(s *ChatAssetUpsert) {
		s.SetUploadedBy(v)
	})
}

// AddUploadedBy adds v to the "uploaded_by" field.
func (u *ChatAssetUpsertBulk) AddUploadedBy(v int64) *ChatAssetUpsertBulk {
	return u.Update(func(s *ChatAssetUpsert) {
		s.AddUploadedBy(v)
	})
}

// UpdateUploadedBy sets the "uploaded_by" field to the value that was provided on create.
func (u *ChatAssetUpsertBulk) UpdateUploadedBy() *ChatAssetUpsertBulk {
	return u.Update(func(s *ChatAssetUpsert) {
		s.UpdateUploadedBy()
	})
}

// ClearUploadedBy clears the value of the "uploaded_by" field.
func (u *ChatAssetUpsertBulk) ClearUploadedBy() *ChatAssetUpsertBulk {
	return u.Update(func(s *ChatAssetUpsert) {
		s.ClearUploadedBy()
	})
}

// SetName sets the "name" field.
func (u *ChatAssetUpsertBulk) SetName(v string) *ChatAssetUpsertBulk {
	return u.Update(func(s *ChatAssetUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ChatAssetUpsertBulk) UpdateName() *ChatAssetUpsertBulk {
	return u.Update(func(s *ChatAssetUpsert) {
		s.UpdateName()
	})
}

// SetMimeType sets the "mime_type" field.
func (u *ChatAssetUpsertBulk) SetMimeType(v string) *ChatAssetUpsertBulk {
	return u.Update(func(s *ChatAssetUpsert) {
		s.SetMimeType(v)
	})
}

// UpdateMimeType sets the "mime_type" field to the value that was provided on create.
func (u *ChatAssetUpsertBulk) UpdateMimeType() *ChatAssetUpsertBulk {
	return u.Update(func(s *ChatAssetUpsert) {
		s.UpdateMimeType()
	})
}

// SetSize sets the "size" field.
func (u *ChatAssetUpsertBulk) SetSize(v int) *ChatAssetUpsertBulk {
	return u.Update(func(s *ChatAssetUpsert) {
		s.SetSize(v)
	})
}

// AddSize adds v to the "size" field.
func (u *ChatAssetUpsertBulk) AddSize(v int) *ChatAssetUpsertBulk {
	return u.Update(func(s *ChatAssetUpsert) {
		s.AddSize(v)
	})
}

// UpdateSize sets the "size" field to the value that was provided on create.
func (u *ChatAssetUpsertBulk) UpdateSize() *ChatAssetUpsertBulk {
	return u.Update(func(s *ChatAssetUpsert) {
		s.UpdateSize()
	})
}

// SetData sets the "data" field.
func (u *ChatAssetUpsertBulk) SetData(v []byte) *ChatAssetUpsertBulk {
	return u.Update(func(s *ChatAssetUpsert) {
		s.SetData(v)
	})
}

// UpdateData sets the "data" field to the value that was provided on create.
func (u *ChatAssetUpsertBulk) UpdateData() *ChatAssetUpsertBulk {
	return u.Update(func(s *ChatAssetUpsert) {
		s.UpdateData()
	})
}

// SetCollection sets the "collection" field.
func (u *ChatAssetUpsertBulk) SetCollection(v string) *ChatAssetUpsertBulk {
	return u.Update(func(s *ChatAssetUpsert) {
		s.SetCollection(v)
	})
}

// UpdateCollection sets the "collection" field to the value that was provided on create.
func (u *ChatAssetUpsertBulk) UpdateCollection() *ChatAssetUpsertBulk {
	return u.Update(func(s *ChatAssetUpsert) {
		s.UpdateCollection()
	})
}

// SetCatalogVisible sets the "catalog_visible" field.
func (u *ChatAssetUpsertBulk) SetCatalogVisible(v bool) *ChatAssetUpsertBulk {
	return u.Update(func(s *ChatAssetUpsert) {
		s.SetCatalogVisible(v)
	})
}

// UpdateCatalogVisible sets the "catalog_visible" field to the value that was provided on create.
func (u *ChatAssetUpsertBulk) UpdateCatalogVisible() *ChatAssetUpsertBulk {
	return u.Update(func(s *ChatAssetUpsert) {
		s.UpdateCatalogVisible()
	})
}

// Exec executes the query.
func (u *ChatAssetUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ChatAssetCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChatAssetCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChatAssetUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
