// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/chatasset"
	"github.com/Wei-Shaw/sub2api/ent/chatconversation"
	"github.com/Wei-Shaw/sub2api/ent/chatmessage"
)

// ChatMessageCreate is the builder for creating a ChatMessage entity.
type ChatMessageCreate struct {
	config
	mutation *ChatMessageMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetConversationID sets the "conversation_id" field.
func (_c *ChatMessageCreate) SetConversationID(v int64) *ChatMessageCreate {
	_c.mutation.SetConversationID(v)
	return _c
}

// SetSenderType sets the "sender_type" field.
func (_c *ChatMessageCreate) SetSenderType(v chatmessage.SenderType) *ChatMessageCreate {
	_c.mutation.SetSenderType(v)
	return _c
}

// SetSenderID sets the "sender_id" field.
func (_c *ChatMessageCreate) SetSenderID(v int64) *ChatMessageCreate {
	_c.mutation.SetSenderID(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *ChatMessageCreate) SetContent(v string) *ChatMessageCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetKind sets the "kind" field.
func (_c *ChatMessageCreate) SetKind(v chatmessage.Kind) *ChatMessageCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_c *ChatMessageCreate) SetNillableKind(v *chatmessage.Kind) *ChatMessageCreate {
	if v != nil {
		_c.SetKind(*v)
	}
	return _c
}

// SetReplyToID sets the "reply_to_id" field.
func (_c *ChatMessageCreate) SetReplyToID(v int64) *ChatMessageCreate {
	_c.mutation.SetReplyToID(v)
	return _c
}

// SetNillableReplyToID sets the "reply_to_id" field if the given value is not nil.
func (_c *ChatMessageCreate) SetNillableReplyToID(v *int64) *ChatMessageCreate {
	if v != nil {
		_c.SetReplyToID(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *ChatMessageCreate) SetMetadata(v json.RawMessage) *ChatMessageCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_c *ChatMessageCreate) SetIdempotencyKey(v string) *ChatMessageCreate {
	_c.mutation.SetIdempotencyKey(v)
	return _c
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (_c *ChatMessageCreate) SetNillableIdempotencyKey(v *string) *ChatMessageCreate {
	if v != nil {
		_c.SetIdempotencyKey(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ChatMessageCreate) SetCreatedAt(v time.Time) *ChatMessageCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ChatMessageCreate) SetNillableCreatedAt(v *time.Time) *ChatMessageCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetConversation sets the "conversation" edge to the ChatConversation entity.
func (_c *ChatMessageCreate) SetConversation(v *ChatConversation) *ChatMessageCreate {
	return _c.SetConversationID(v.ID)
}

// AddAssetIDs adds the "assets" edge to the ChatAsset entity by IDs.
func (_c *ChatMessageCreate) AddAssetIDs(ids ...int64) *ChatMessageCreate {
	_c.mutation.AddAssetIDs(ids...)
	return _c
}

// AddAssets adds the "assets" edges to the ChatAsset entity.
func (_c *ChatMessageCreate) AddAssets(v ...*ChatAsset) *ChatMessageCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAssetIDs(ids...)
}

// Mutation returns the ChatMessageMutation object of the builder.
func (_c *ChatMessageCreate) Mutation() *ChatMessageMutation {
	return _c.mutation
}

// Save creates the ChatMessage in the database.
func (_c *ChatMessageCreate) Save(ctx context.Context) (*ChatMessage, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChatMessageCreate) SaveX(ctx context.Context) *ChatMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChatMessageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChatMessageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ChatMessageCreate) defaults() {
	if _, ok := _c.mutation.Kind(); !ok {
		v := chatmessage.DefaultKind
		_c.mutation.SetKind(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := chatmessage.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChatMessageCreate) check() error {
	if _, ok := _c.mutation.ConversationID(); !ok {
		return &ValidationError{Name: "conversation_id", err: errors.New(`ent: missing required field "ChatMessage.conversation_id"`)}
	}
	if _, ok := _c.mutation.SenderType(); !ok {
		return &ValidationError{Name: "sender_type", err: errors.New(`ent: missing required field "ChatMessage.sender_type"`)}
	}
	if v, ok := _c.mutation.SenderType(); ok {
		if err := chatmessage.SenderTypeValidator(v); err != nil {
			return &ValidationError{Name: "sender_type", err: fmt.Errorf(`ent: validator failed for field "ChatMessage.sender_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SenderID(); !ok {
		return &ValidationError{Name: "sender_id", err: errors.New(`ent: missing required field "ChatMessage.sender_id"`)}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "ChatMessage.content"`)}
	}
	if v, ok := _c.mutation.Content(); ok {
		if err := chatmessage.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "ChatMessage.content": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "ChatMessage.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := chatmessage.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "ChatMessage.kind": %w`, err)}
		}
	}
	if v, ok := _c.mutation.IdempotencyKey(); ok {
		if err := chatmessage.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`ent: validator failed for field "ChatMessage.idempotency_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ChatMessage.created_at"`)}
	}
	if len(_c.mutation.ConversationIDs()) == 0 {
		return &ValidationError{Name: "conversation", err: errors.New(`ent: missing required edge "ChatMessage.conversation"`)}
	}
	return nil
}

func (_c *ChatMessageCreate) sqlSave(ctx context.Context) (*ChatMessage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChatMessageCreate) createSpec() (*ChatMessage, *sqlgraph.CreateSpec) {
	var (
		_node = &ChatMessage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(chatmessage.Table, sqlgraph.NewFieldSpec(chatmessage.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.SenderType(); ok {
		_spec.SetField(chatmessage.FieldSenderType, field.TypeEnum, value)
		_node.SenderType = value
	}
	if value, ok := _c.mutation.SenderID(); ok {
		_spec.SetField(chatmessage.FieldSenderID, field.TypeInt64, value)
		_node.SenderID = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(chatmessage.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(chatmessage.FieldKind, field.TypeEnum, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.ReplyToID(); ok {
		_spec.SetField(chatmessage.FieldReplyToID, field.TypeInt64, value)
		_node.ReplyToID = &value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(chatmessage.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.IdempotencyKey(); ok {
		_spec.SetField(chatmessage.FieldIdempotencyKey, field.TypeString, value)
		_node.IdempotencyKey = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(chatmessage.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.ConversationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatmessage.ConversationTable,
			Columns: []string{chatmessage.ConversationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatconversation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ConversationID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AssetsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   chatmessage.AssetsTable,
			Columns: chatmessage.AssetsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatasset.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ChatMessageAssetCreate{config: _c.config, mutation: newChatMessageAssetMutation(_c.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ChatMessage.Create().
//		SetConversationID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChatMessageUpsert) {
//			SetConversationID(v+v).
//		}).
//		Exec(ctx)
func (_c *ChatMessageCreate) OnConflict(opts ...sql.ConflictOption) *ChatMessageUpsertOne {
	_c.conflict = opts
	return &ChatMessageUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ChatMessage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChatMessageCreate) OnConflictColumns(columns ...string) *ChatMessageUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChatMessageUpsertOne{
		create: _c,
	}
}

type (
	// ChatMessageUpsertOne is the builder for "upsert"-ing
	//  one ChatMessage node.
	ChatMessageUpsertOne struct {
		create *ChatMessageCreate
	}

	// ChatMessageUpsert is the "OnConflict" setter.
	ChatMessageUpsert struct {
		*sql.UpdateSet
	}
)

// SetConversationID sets the "conversation_id" field.
func (u *ChatMessageUpsert) SetConversationID(v int64) *ChatMessageUpsert {
	u.Set(chatmessage.FieldConversationID, v)
	return u
}

// UpdateConversationID sets the "conversation_id" field to the value that was provided on create.
func (u *ChatMessageUpsert) UpdateConversationID() *ChatMessageUpsert {
	u.SetExcluded(chatmessage.FieldConversationID)
	return u
}

// SetSenderType sets the "sender_type" field.
func (u *ChatMessageUpsert) SetSenderType(v chatmessage.SenderType) *ChatMessageUpsert {
	u.Set(chatmessage.FieldSenderType, v)
	return u
}

// UpdateSenderType sets the "sender_type" field to the value that was provided on create.
func (u *ChatMessageUpsert) UpdateSenderType() *ChatMessageUpsert {
	u.SetExcluded(chatmessage.FieldSenderType)
	return u
}

// SetSenderID sets the "sender_id" field.
func (u *ChatMessageUpsert) SetSenderID(v int64) *ChatMessageUpsert {
	u.Set(chatmessage.FieldSenderID, v)
	return u
}

// UpdateSenderID sets the "sender_id" field to the value that was provided on create.
func (u *ChatMessageUpsert) UpdateSenderID() *ChatMessageUpsert {
	u.SetExcluded(chatmessage.FieldSenderID)
	return u
}

// AddSenderID adds v to the "sender_id" field.
func (u *ChatMessageUpsert) AddSenderID(v int64) *ChatMessageUpsert {
	u.Add(chatmessage.FieldSenderID, v)
	return u
}

// SetContent sets the "content" field.
func (u *ChatMessageUpsert) SetContent(v string) *ChatMessageUpsert {
	u.Set(chatmessage.FieldContent, v)
	return u
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *ChatMessageUpsert) UpdateContent() *ChatMessageUpsert {
	u.SetExcluded(chatmessage.FieldContent)
	return u
}

// SetKind sets the "kind" field.
func (u *ChatMessageUpsert) SetKind(v chatmessage.Kind) *ChatMessageUpsert {
	u.Set(chatmessage.FieldKind, v)
	return u
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *ChatMessageUpsert) UpdateKind() *ChatMessageUpsert {
	u.SetExcluded(chatmessage.FieldKind)
	return u
}

// SetReplyToID sets the "reply_to_id" field.
func (u *ChatMessageUpsert) SetReplyToID(v int64) *ChatMessageUpsert {
	u.Set(chatmessage.FieldReplyToID, v)
	return u
}

// UpdateReplyToID sets the "reply_to_id" field to the value that was provided on create.
func (u *ChatMessageUpsert) UpdateReplyToID() *ChatMessageUpsert {
	u.SetExcluded(chatmessage.FieldReplyToID)
	return u
}

// AddReplyToID adds v to the "reply_to_id" field.
func (u *ChatMessageUpsert) AddReplyToID(v int64) *ChatMessageUpsert {
	u.Add(chatmessage.FieldReplyToID, v)
	return u
}

// ClearReplyToID clears the value of the "reply_to_id" field.
func (u *ChatMessageUpsert) ClearReplyToID() *ChatMessageUpsert {
	u.SetNull(chatmessage.FieldReplyToID)
	return u
}

// SetMetadata sets the "metadata" field.
func (u *ChatMessageUpsert) SetMetadata(v json.RawMessage) *ChatMessageUpsert {
	u.Set(chatmessage.FieldMetadata, v)
	return u
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *ChatMessageUpsert) UpdateMetadata() *ChatMessageUpsert {
	u.SetExcluded(chatmessage.FieldMetadata)
	return u
}

// ClearMetadata clears the value of the "metadata" field.
func (u *ChatMessageUpsert) ClearMetadata() *ChatMessageUpsert {
	u.SetNull(chatmessage.FieldMetadata)
	return u
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (u *ChatMessageUpsert) SetIdempotencyKey(v string) *ChatMessageUpsert {
	u.Set(chatmessage.FieldIdempotencyKey, v)
	return u
}

// UpdateIdempotencyKey sets the "idempotency_key" field to the value that was provided on create.
func (u *ChatMessageUpsert) UpdateIdempotencyKey() *ChatMessageUpsert {
	u.SetExcluded(chatmessage.FieldIdempotencyKey)
	return u
}

// ClearIdempotencyKey clears the value of the "idempotency_key" field.
func (u *ChatMessageUpsert) ClearIdempotencyKey() *ChatMessageUpsert {
	u.SetNull(chatmessage.FieldIdempotencyKey)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ChatMessage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ChatMessageUpsertOne) UpdateNewValues() *ChatMessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(chatmessage.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ChatMessage.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ChatMessageUpsertOne) Ignore() *ChatMessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChatMessageUpsertOne) DoNothing() *ChatMessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChatMessageCreate.OnConflict
// documentation for more info.
func (u *ChatMessageUpsertOne) Update(set func(*ChatMessageUpsert)) *ChatMessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChatMessageUpsert{UpdateSet: update})
	}))
	return u
}

// SetConversationID sets the "conversation_id" field.
func (u *ChatMessageUpsertOne) SetConversationID(v int64) *ChatMessageUpsertOne {
	return u.Update(func(s *ChatMessageUpsert) {
		s.SetConversationID(v)
	})
}

// UpdateConversationID sets the "conversation_id" field to the value that was provided on create.
func (u *ChatMessageUpsertOne) UpdateConversationID() *ChatMessageUpsertOne {
	return u.Update(func(s *ChatMessageUpsert) {
		s.UpdateConversationID()
	})
}

// SetSenderType sets the "sender_type" field.
func (u *ChatMessageUpsertOne) SetSenderType(v chatmessage.SenderType) *ChatMessageUpsertOne {
	return u.Update(func(s *ChatMessageUpsert) {
		s.SetSenderType(v)
	})
}

// UpdateSenderType sets the "sender_type" field to the value that was provided on create.
func (u *ChatMessageUpsertOne) UpdateSenderType() *ChatMessageUpsertOne {
	return u.Update(func(s *ChatMessageUpsert) {
		s.UpdateSenderType()
	})
}

// SetSenderID sets the "sender_id" field.
func (u *ChatMessageUpsertOne) SetSenderID(v int64) *ChatMessageUpsertOne {
	return u.Update(func(s *ChatMessageUpsert) {
		s.SetSenderID(v)
	})
}

// AddSenderID adds v to the "sender_id" field.
func (u *ChatMessageUpsertOne) AddSenderID(v int64) *ChatMessageUpsertOne {
	return u.Update(func(s *ChatMessageUpsert) {
		s.AddSenderID(v)
	})
}

// UpdateSenderID sets the "sender_id" field to the value that was provided on create.
func (u *ChatMessageUpsertOne) UpdateSenderID() *ChatMessageUpsertOne {
	return u.Update(func(s *ChatMessageUpsert) {
		s.UpdateSenderID()
	})
}

// SetContent sets the "content" field.
func (u *ChatMessageUpsertOne) SetContent(v string) *ChatMessageUpsertOne {
	return u.Update(func(s *ChatMessageUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *ChatMessageUpsertOne) UpdateContent() *ChatMessageUpsertOne {
	return u.Update(func(s *ChatMessageUpsert) {
		s.UpdateContent()
	})
}

// SetKind sets the "kind" field.
func (u *ChatMessageUpsertOne) SetKind(v chatmessage.Kind) *ChatMessageUpsertOne {
	return u.Update(func(s *ChatMessageUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *ChatMessageUpsertOne) UpdateKind() *ChatMessageUpsertOne {
	return u.Update(func(s *ChatMessageUpsert) {
		s.UpdateKind()
	})
}

// SetReplyToID sets the "reply_to_id" field.
func (u *ChatMessageUpsertOne) SetReplyToID(v int64) *ChatMessageUpsertOne {
	return u.Update(func(s *ChatMessageUpsert) {
		s.SetReplyToID(v)
	})
}

// AddReplyToID adds v to the "reply_to_id" field.
func (u *ChatMessageUpsertOne) AddReplyToID(v int64) *ChatMessageUpsertOne {
	return u.Update(func(s *ChatMessageUpsert) {
		s.AddReplyToID(v)
	})
}

// UpdateReplyToID sets the "reply_to_id" field to the value that was provided on create.
func (u *ChatMessageUpsertOne) UpdateReplyToID() *ChatMessageUpsertOne {
	return u.Update(func(s *ChatMessageUpsert) {
		s.UpdateReplyToID()
	})
}

// ClearReplyToID clears the value of the "reply_to_id" field.
func (u *ChatMessageUpsertOne) ClearReplyToID() *ChatMessageUpsertOne {
	return u.Update(func(s *ChatMessageUpsert) {
		s.ClearReplyToID()
	})
}

// SetMetadata sets the "metadata" field.
func (u *ChatMessageUpsertOne) SetMetadata(v json.RawMessage) *ChatMessageUpsertOne {
	return u.Update(func(s *ChatMessageUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *ChatMessageUpsertOne) UpdateMetadata() *ChatMessageUpsertOne {
	return u.Update(func(s *ChatMessageUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *ChatMessageUpsertOne) ClearMetadata() *ChatMessageUpsertOne {
	return u.Update(func(s *ChatMessageUpsert) {
		s.ClearMetadata()
	})
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (u *ChatMessageUpsertOne) SetIdempotencyKey(v string) *ChatMessageUpsertOne {
	return u.Update(func(s *ChatMessageUpsert) {
		s.SetIdempotencyKey(v)
	})
}

// UpdateIdempotencyKey sets the "idempotency_key" field to the value that was provided on create.
func (u *ChatMessageUpsertOne) UpdateIdempotencyKey() *ChatMessageUpsertOne {
	return u.Update(func(s *ChatMessageUpsert) {
		s.UpdateIdempotencyKey()
	})
}

// ClearIdempotencyKey clears the value of the "idempotency_key" field.
func (u *ChatMessageUpsertOne) ClearIdempotencyKey() *ChatMessageUpsertOne {
	return u.Update(func(s *ChatMessageUpsert) {
		s.ClearIdempotencyKey()
	})
}

// Exec executes the query.
func (u *ChatMessageUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChatMessageCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChatMessageUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ChatMessageUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ChatMessageUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ChatMessageCreateBulk is the builder for creating many ChatMessage entities in bulk.
type ChatMessageCreateBulk struct {
	config
	err      error
	builders []*ChatMessageCreate
	conflict []sql.ConflictOption
}

// Save creates the ChatMessage entities in the database.
func (_c *ChatMessageCreateBulk) Save(ctx context.Context) ([]*ChatMessage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ChatMessage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChatMessageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChatMessageCreateBulk) SaveX(ctx context.Context) []*ChatMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChatMessageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChatMessageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ChatMessage.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChatMessageUpsert) {
//			SetConversationID(v+v).
//		}).
//		Exec(ctx)
func (_c *ChatMessageCreateBulk) OnConflict(opts ...sql.ConflictOption) *ChatMessageUpsertBulk {
	_c.conflict = opts
	return &ChatMessageUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ChatMessage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChatMessageCreateBulk) OnConflictColumns(columns ...string) *ChatMessageUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChatMessageUpsertBulk{
		create: _c,
	}
}

// ChatMessageUpsertBulk is the builder for "upsert"-ing
// a bulk of ChatMessage nodes.
type ChatMessageUpsertBulk struct {
	create *ChatMessageCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ChatMessage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ChatMessageUpsertBulk) UpdateNewValues() *ChatMessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(chatmessage.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ChatMessage.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ChatMessageUpsertBulk) Ignore() *ChatMessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChatMessageUpsertBulk) DoNothing() *ChatMessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChatMessageCreateBulk.OnConflict
// documentation for more info.
func (u *ChatMessageUpsertBulk) Update(set func(*ChatMessageUpsert)) *ChatMessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChatMessageUpsert{UpdateSet: update})
	}))
	return u
}

// SetConversationID sets the "conversation_id" field.
func (u *ChatMessageUpsertBulk) SetConversationID(v int64) *ChatMessageUpsertBulk {
	return u.Update(func(s *ChatMessageUpsert) {
		s.SetConversationID(v)
	})
}

// UpdateConversationID sets the "conversation_id" field to the value that was provided on create.
func (u *ChatMessageUpsertBulk) UpdateConversationID() *ChatMessageUpsertBulk {
	return u.Update(func(s *ChatMessageUpsert) {
		s.UpdateConversationID()
	})
}

// SetSenderType sets the "sender_type" field.
func (u *ChatMessageUpsertBulk) SetSenderType(v chatmessage.SenderType) *ChatMessageUpsertBulk {
	return u.Update(func(s *ChatMessageUpsert) {
		s.SetSenderType(v)
	})
}

// UpdateSenderType sets the "sender_type" field to the value that was provided on create.
func (u *ChatMessageUpsertBulk) UpdateSenderType() *ChatMessageUpsertBulk {
	return u.Update(func(s *ChatMessageUpsert) {
		s.UpdateSenderType()
	})
}

// SetSenderID sets the "sender_id" field.
func (u *ChatMessageUpsertBulk) SetSenderID(v int64) *ChatMessageUpsertBulk {
	return u.Update(func(s *ChatMessageUpsert) {
		s.SetSenderID(v)
	})
}

// AddSenderID adds v to the "sender_id" field.
func (u *ChatMessageUpsertBulk) AddSenderID(v int64) *ChatMessageUpsertBulk {
	return u.Update(func(s *ChatMessageUpsert) {
		s.AddSenderID(v)
	})
}

// UpdateSenderID sets the "sender_id" field to the value that was provided on create.
func (u *ChatMessageUpsertBulk) UpdateSenderID() *ChatMessageUpsertBulk {
	return u.Update(func(s *ChatMessageUpsert) {
		s.UpdateSenderID()
	})
}

// SetContent sets the "content" field.
func (u *ChatMessageUpsertBulk) SetContent(v string) *ChatMessageUpsertBulk {
	return u.Update(func(s *ChatMessageUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *ChatMessageUpsertBulk) UpdateContent() *ChatMessageUpsertBulk {
	return u.Update(func(s *ChatMessageUpsert) {
		s.UpdateContent()
	})
}

// SetKind sets the "kind" field.
func (u *ChatMessageUpsertBulk) SetKind(v chatmessage.Kind) *ChatMessageUpsertBulk {
	return u.Update(func(s *ChatMessageUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *ChatMessageUpsertBulk) UpdateKind() *ChatMessageUpsertBulk {
	return u.Update(func(s *ChatMessageUpsert) {
		s.UpdateKind()
	})
}

// SetReplyToID sets the "reply_to_id" field.
func (u *ChatMessageUpsertBulk) SetReplyToID(v int64) *ChatMessageUpsertBulk {
	return u.Update(func(s *ChatMessageUpsert) {
		s.SetReplyToID(v)
	})
}

// AddReplyToID adds v to the "reply_to_id" field.
func (u *ChatMessageUpsertBulk) AddReplyToID(v int64) *ChatMessageUpsertBulk {
	return u.Update(func(s *ChatMessageUpsert) {
		s.AddReplyToID(v)
	})
}

// UpdateReplyToID sets the "reply_to_id" field to the value that was provided on create.
func (u *ChatMessageUpsertBulk) UpdateReplyToID() *ChatMessageUpsertBulk {
	return u.Update(func(s *ChatMessageUpsert) {
		s.UpdateReplyToID()
	})
}

// ClearReplyToID clears the value of the "reply_to_id" field.
func (u *ChatMessageUpsertBulk) ClearReplyToID() *ChatMessageUpsertBulk {
	return u.Update(func(s *ChatMessageUpsert) {
		s.ClearReplyToID()
	})
}

// SetMetadata sets the "metadata" field.
func (u *ChatMessageUpsertBulk) SetMetadata(v json.RawMessage) *ChatMessageUpsertBulk {
	return u.Update(func(s *ChatMessageUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *ChatMessageUpsertBulk) UpdateMetadata() *ChatMessageUpsertBulk {
	return u.Update(func(s *ChatMessageUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *ChatMessageUpsertBulk) ClearMetadata() *ChatMessageUpsertBulk {
	return u.Update(func(s *ChatMessageUpsert) {
		s.ClearMetadata()
	})
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (u *ChatMessageUpsertBulk) SetIdempotencyKey(v string) *ChatMessageUpsertBulk {
	return u.Update(func(s *ChatMessageUpsert) {
		s.SetIdempotencyKey(v)
	})
}

// UpdateIdempotencyKey sets the "idempotency_key" field to the value that was provided on create.
func (u *ChatMessageUpsertBulk) UpdateIdempotencyKey() *ChatMessageUpsertBulk {
	return u.Update(func(s *ChatMessageUpsert) {
		s.UpdateIdempotencyKey()
	})
}

// ClearIdempotencyKey clears the value of the "idempotency_key" field.
func (u *ChatMessageUpsertBulk) ClearIdempotencyKey() *ChatMessageUpsertBulk {
	return u.Update(func(s *ChatMessageUpsert) {
		s.ClearIdempotencyKey()
	})
}

// Exec executes the query.
func (u *ChatMessageUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ChatMessageCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChatMessageCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChatMessageUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
