// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/chatasset"
	"github.com/Wei-Shaw/sub2api/ent/chatconversation"
	"github.com/Wei-Shaw/sub2api/ent/chatmessage"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ChatMessageUpdate is the builder for updating ChatMessage entities.
type ChatMessageUpdate struct {
	config
	hooks    []Hook
	mutation *ChatMessageMutation
}

// Where appends a list predicates to the ChatMessageUpdate builder.
func (_u *ChatMessageUpdate) Where(ps ...predicate.ChatMessage) *ChatMessageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetConversationID sets the "conversation_id" field.
func (_u *ChatMessageUpdate) SetConversationID(v int64) *ChatMessageUpdate {
	_u.mutation.SetConversationID(v)
	return _u
}

// SetNillableConversationID sets the "conversation_id" field if the given value is not nil.
func (_u *ChatMessageUpdate) SetNillableConversationID(v *int64) *ChatMessageUpdate {
	if v != nil {
		_u.SetConversationID(*v)
	}
	return _u
}

// SetSenderType sets the "sender_type" field.
func (_u *ChatMessageUpdate) SetSenderType(v chatmessage.SenderType) *ChatMessageUpdate {
	_u.mutation.SetSenderType(v)
	return _u
}

// SetNillableSenderType sets the "sender_type" field if the given value is not nil.
func (_u *ChatMessageUpdate) SetNillableSenderType(v *chatmessage.SenderType) *ChatMessageUpdate {
	if v != nil {
		_u.SetSenderType(*v)
	}
	return _u
}

// SetSenderID sets the "sender_id" field.
func (_u *ChatMessageUpdate) SetSenderID(v int64) *ChatMessageUpdate {
	_u.mutation.ResetSenderID()
	_u.mutation.SetSenderID(v)
	return _u
}

// SetNillableSenderID sets the "sender_id" field if the given value is not nil.
func (_u *ChatMessageUpdate) SetNillableSenderID(v *int64) *ChatMessageUpdate {
	if v != nil {
		_u.SetSenderID(*v)
	}
	return _u
}

// AddSenderID adds value to the "sender_id" field.
func (_u *ChatMessageUpdate) AddSenderID(v int64) *ChatMessageUpdate {
	_u.mutation.AddSenderID(v)
	return _u
}

// SetContent sets the "content" field.
func (_u *ChatMessageUpdate) SetContent(v string) *ChatMessageUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *ChatMessageUpdate) SetNillableContent(v *string) *ChatMessageUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *ChatMessageUpdate) SetKind(v chatmessage.Kind) *ChatMessageUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *ChatMessageUpdate) SetNillableKind(v *chatmessage.Kind) *ChatMessageUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetReplyToID sets the "reply_to_id" field.
func (_u *ChatMessageUpdate) SetReplyToID(v int64) *ChatMessageUpdate {
	_u.mutation.ResetReplyToID()
	_u.mutation.SetReplyToID(v)
	return _u
}

// SetNillableReplyToID sets the "reply_to_id" field if the given value is not nil.
func (_u *ChatMessageUpdate) SetNillableReplyToID(v *int64) *ChatMessageUpdate {
	if v != nil {
		_u.SetReplyToID(*v)
	}
	return _u
}

// AddReplyToID adds value to the "reply_to_id" field.
func (_u *ChatMessageUpdate) AddReplyToID(v int64) *ChatMessageUpdate {
	_u.mutation.AddReplyToID(v)
	return _u
}

// ClearReplyToID clears the value of the "reply_to_id" field.
func (_u *ChatMessageUpdate) ClearReplyToID() *ChatMessageUpdate {
	_u.mutation.ClearReplyToID()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *ChatMessageUpdate) SetMetadata(v json.RawMessage) *ChatMessageUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// AppendMetadata appends value to the "metadata" field.
func (_u *ChatMessageUpdate) AppendMetadata(v json.RawMessage) *ChatMessageUpdate {
	_u.mutation.AppendMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *ChatMessageUpdate) ClearMetadata() *ChatMessageUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_u *ChatMessageUpdate) SetIdempotencyKey(v string) *ChatMessageUpdate {
	_u.mutation.SetIdempotencyKey(v)
	return _u
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (_u *ChatMessageUpdate) SetNillableIdempotencyKey(v *string) *ChatMessageUpdate {
	if v != nil {
		_u.SetIdempotencyKey(*v)
	}
	return _u
}

// ClearIdempotencyKey clears the value of the "idempotency_key" field.
func (_u *ChatMessageUpdate) ClearIdempotencyKey() *ChatMessageUpdate {
	_u.mutation.ClearIdempotencyKey()
	return _u
}

// SetRecalledAt sets the "recalled_at" field.
func (_u *ChatMessageUpdate) SetRecalledAt(v time.Time) *ChatMessageUpdate {
	_u.mutation.SetRecalledAt(v)
	return _u
}

// SetNillableRecalledAt sets the "recalled_at" field if the given value is not nil.
func (_u *ChatMessageUpdate) SetNillableRecalledAt(v *time.Time) *ChatMessageUpdate {
	if v != nil {
		_u.SetRecalledAt(*v)
	}
	return _u
}

// ClearRecalledAt clears the value of the "recalled_at" field.
func (_u *ChatMessageUpdate) ClearRecalledAt() *ChatMessageUpdate {
	_u.mutation.ClearRecalledAt()
	return _u
}

// SetRecalledBy sets the "recalled_by" field.
func (_u *ChatMessageUpdate) SetRecalledBy(v int64) *ChatMessageUpdate {
	_u.mutation.ResetRecalledBy()
	_u.mutation.SetRecalledBy(v)
	return _u
}

// SetNillableRecalledBy sets the "recalled_by" field if the given value is not nil.
func (_u *ChatMessageUpdate) SetNillableRecalledBy(v *int64) *ChatMessageUpdate {
	if v != nil {
		_u.SetRecalledBy(*v)
	}
	return _u
}

// AddRecalledBy adds value to the "recalled_by" field.
func (_u *ChatMessageUpdate) AddRecalledBy(v int64) *ChatMessageUpdate {
	_u.mutation.AddRecalledBy(v)
	return _u
}

// ClearRecalledBy clears the value of the "recalled_by" field.
func (_u *ChatMessageUpdate) ClearRecalledBy() *ChatMessageUpdate {
	_u.mutation.ClearRecalledBy()
	return _u
}

// SetConversation sets the "conversation" edge to the ChatConversation entity.
func (_u *ChatMessageUpdate) SetConversation(v *ChatConversation) *ChatMessageUpdate {
	return _u.SetConversationID(v.ID)
}

// AddAssetIDs adds the "assets" edge to the ChatAsset entity by IDs.
func (_u *ChatMessageUpdate) AddAssetIDs(ids ...int64) *ChatMessageUpdate {
	_u.mutation.AddAssetIDs(ids...)
	return _u
}

// AddAssets adds the "assets" edges to the ChatAsset entity.
func (_u *ChatMessageUpdate) AddAssets(v ...*ChatAsset) *ChatMessageUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAssetIDs(ids...)
}

// Mutation returns the ChatMessageMutation object of the builder.
func (_u *ChatMessageUpdate) Mutation() *ChatMessageMutation {
	return _u.mutation
}

// ClearConversation clears the "conversation" edge to the ChatConversation entity.
func (_u *ChatMessageUpdate) ClearConversation() *ChatMessageUpdate {
	_u.mutation.ClearConversation()
	return _u
}

// ClearAssets clears all "assets" edges to the ChatAsset entity.
func (_u *ChatMessageUpdate) ClearAssets() *ChatMessageUpdate {
	_u.mutation.ClearAssets()
	return _u
}

// RemoveAssetIDs removes the "assets" edge to ChatAsset entities by IDs.
func (_u *ChatMessageUpdate) RemoveAssetIDs(ids ...int64) *ChatMessageUpdate {
	_u.mutation.RemoveAssetIDs(ids...)
	return _u
}

// RemoveAssets removes "assets" edges to ChatAsset entities.
func (_u *ChatMessageUpdate) RemoveAssets(v ...*ChatAsset) *ChatMessageUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAssetIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ChatMessageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChatMessageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ChatMessageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChatMessageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChatMessageUpdate) check() error {
	if v, ok := _u.mutation.SenderType(); ok {
		if err := chatmessage.SenderTypeValidator(v); err != nil {
			return &ValidationError{Name: "sender_type", err: fmt.Errorf(`ent: validator failed for field "ChatMessage.sender_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := chatmessage.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "ChatMessage.content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Kind(); ok {
		if err := chatmessage.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "ChatMessage.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IdempotencyKey(); ok {
		if err := chatmessage.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`ent: validator failed for field "ChatMessage.idempotency_key": %w`, err)}
		}
	}
	if _u.mutation.ConversationCleared() && len(_u.mutation.ConversationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChatMessage.conversation"`)
	}
	return nil
}

func (_u *ChatMessageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(chatmessage.Table, chatmessage.Columns, sqlgraph.NewFieldSpec(chatmessage.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SenderType(); ok {
		_spec.SetField(chatmessage.FieldSenderType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SenderID(); ok {
		_spec.SetField(chatmessage.FieldSenderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSenderID(); ok {
		_spec.AddField(chatmessage.FieldSenderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(chatmessage.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(chatmessage.FieldKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ReplyToID(); ok {
		_spec.SetField(chatmessage.FieldReplyToID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedReplyToID(); ok {
		_spec.AddField(chatmessage.FieldReplyToID, field.TypeInt64, value)
	}
	if _u.mutation.ReplyToIDCleared() {
		_spec.ClearField(chatmessage.FieldReplyToID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(chatmessage.FieldMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedMetadata(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, chatmessage.FieldMetadata, value)
		})
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(chatmessage.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.IdempotencyKey(); ok {
		_spec.SetField(chatmessage.FieldIdempotencyKey, field.TypeString, value)
	}
	if _u.mutation.IdempotencyKeyCleared() {
		_spec.ClearField(chatmessage.FieldIdempotencyKey, field.TypeString)
	}
	if value, ok := _u.mutation.RecalledAt(); ok {
		_spec.SetField(chatmessage.FieldRecalledAt, field.TypeTime, value)
	}
	if _u.mutation.RecalledAtCleared() {
		_spec.ClearField(chatmessage.FieldRecalledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RecalledBy(); ok {
		_spec.SetField(chatmessage.FieldRecalledBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRecalledBy(); ok {
		_spec.AddField(chatmessage.FieldRecalledBy, field.TypeInt64, value)
	}
	if _u.mutation.RecalledByCleared() {
		_spec.ClearField(chatmessage.FieldRecalledBy, field.TypeInt64)
	}
	if _u.mutation.ConversationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatmessage.ConversationTable,
			Columns: []string{chatmessage.ConversationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatconversation.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConversationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatmessage.ConversationTable,
			Columns: []string{chatmessage.ConversationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatconversation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AssetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   chatmessage.AssetsTable,
			Columns: chatmessage.AssetsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatasset.FieldID, field.TypeInt64),
			},
		}
		createE := &ChatMessageAssetCreate{config: _u.config, mutation: newChatMessageAssetMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAssetsIDs(); len(nodes) > 0 && !_u.mutation.AssetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   chatmessage.AssetsTable,
			Columns: chatmessage.AssetsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatasset.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ChatMessageAssetCreate{config: _u.config, mutation: newChatMessageAssetMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssetsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   chatmessage.AssetsTable,
			Columns: chatmessage.AssetsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatasset.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ChatMessageAssetCreate{config: _u.config, mutation: newChatMessageAssetMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chatmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ChatMessageUpdateOne is the builder for updating a single ChatMessage entity.
type ChatMessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChatMessageMutation
}

// SetConversationID sets the "conversation_id" field.
func (_u *ChatMessageUpdateOne) SetConversationID(v int64) *ChatMessageUpdateOne {
	_u.mutation.SetConversationID(v)
	return _u
}

// SetNillableConversationID sets the "conversation_id" field if the given value is not nil.
func (_u *ChatMessageUpdateOne) SetNillableConversationID(v *int64) *ChatMessageUpdateOne {
	if v != nil {
		_u.SetConversationID(*v)
	}
	return _u
}

// SetSenderType sets the "sender_type" field.
func (_u *ChatMessageUpdateOne) SetSenderType(v chatmessage.SenderType) *ChatMessageUpdateOne {
	_u.mutation.SetSenderType(v)
	return _u
}

// SetNillableSenderType sets the "sender_type" field if the given value is not nil.
func (_u *ChatMessageUpdateOne) SetNillableSenderType(v *chatmessage.SenderType) *ChatMessageUpdateOne {
	if v != nil {
		_u.SetSenderType(*v)
	}
	return _u
}

// SetSenderID sets the "sender_id" field.
func (_u *ChatMessageUpdateOne) SetSenderID(v int64) *ChatMessageUpdateOne {
	_u.mutation.ResetSenderID()
	_u.mutation.SetSenderID(v)
	return _u
}

// SetNillableSenderID sets the "sender_id" field if the given value is not nil.
func (_u *ChatMessageUpdateOne) SetNillableSenderID(v *int64) *ChatMessageUpdateOne {
	if v != nil {
		_u.SetSenderID(*v)
	}
	return _u
}

// AddSenderID adds value to the "sender_id" field.
func (_u *ChatMessageUpdateOne) AddSenderID(v int64) *ChatMessageUpdateOne {
	_u.mutation.AddSenderID(v)
	return _u
}

// SetContent sets the "content" field.
func (_u *ChatMessageUpdateOne) SetContent(v string) *ChatMessageUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *ChatMessageUpdateOne) SetNillableContent(v *string) *ChatMessageUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *ChatMessageUpdateOne) SetKind(v chatmessage.Kind) *ChatMessageUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *ChatMessageUpdateOne) SetNillableKind(v *chatmessage.Kind) *ChatMessageUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetReplyToID sets the "reply_to_id" field.
func (_u *ChatMessageUpdateOne) SetReplyToID(v int64) *ChatMessageUpdateOne {
	_u.mutation.ResetReplyToID()
	_u.mutation.SetReplyToID(v)
	return _u
}

// SetNillableReplyToID sets the "reply_to_id" field if the given value is not nil.
func (_u *ChatMessageUpdateOne) SetNillableReplyToID(v *int64) *ChatMessageUpdateOne {
	if v != nil {
		_u.SetReplyToID(*v)
	}
	return _u
}

// AddReplyToID adds value to the "reply_to_id" field.
func (_u *ChatMessageUpdateOne) AddReplyToID(v int64) *ChatMessageUpdateOne {
	_u.mutation.AddReplyToID(v)
	return _u
}

// ClearReplyToID clears the value of the "reply_to_id" field.
func (_u *ChatMessageUpdateOne) ClearReplyToID() *ChatMessageUpdateOne {
	_u.mutation.ClearReplyToID()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *ChatMessageUpdateOne) SetMetadata(v json.RawMessage) *ChatMessageUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// AppendMetadata appends value to the "metadata" field.
func (_u *ChatMessageUpdateOne) AppendMetadata(v json.RawMessage) *ChatMessageUpdateOne {
	_u.mutation.AppendMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *ChatMessageUpdateOne) ClearMetadata() *ChatMessageUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_u *ChatMessageUpdateOne) SetIdempotencyKey(v string) *ChatMessageUpdateOne {
	_u.mutation.SetIdempotencyKey(v)
	return _u
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (_u *ChatMessageUpdateOne) SetNillableIdempotencyKey(v *string) *ChatMessageUpdateOne {
	if v != nil {
		_u.SetIdempotencyKey(*v)
	}
	return _u
}

// ClearIdempotencyKey clears the value of the "idempotency_key" field.
func (_u *ChatMessageUpdateOne) ClearIdempotencyKey() *ChatMessageUpdateOne {
	_u.mutation.ClearIdempotencyKey()
	return _u
}

// SetRecalledAt sets the "recalled_at" field.
func (_u *ChatMessageUpdateOne) SetRecalledAt(v time.Time) *ChatMessageUpdateOne {
	_u.mutation.SetRecalledAt(v)
	return _u
}

// SetNillableRecalledAt sets the "recalled_at" field if the given value is not nil.
func (_u *ChatMessageUpdateOne) SetNillableRecalledAt(v *time.Time) *ChatMessageUpdateOne {
	if v != nil {
		_u.SetRecalledAt(*v)
	}
	return _u
}

// ClearRecalledAt clears the value of the "recalled_at" field.
func (_u *ChatMessageUpdateOne) ClearRecalledAt() *ChatMessageUpdateOne {
	_u.mutation.ClearRecalledAt()
	return _u
}

// SetRecalledBy sets the "recalled_by" field.
func (_u *ChatMessageUpdateOne) SetRecalledBy(v int64) *ChatMessageUpdateOne {
	_u.mutation.ResetRecalledBy()
	_u.mutation.SetRecalledBy(v)
	return _u
}

// SetNillableRecalledBy sets the "recalled_by" field if the given value is not nil.
func (_u *ChatMessageUpdateOne) SetNillableRecalledBy(v *int64) *ChatMessageUpdateOne {
	if v != nil {
		_u.SetRecalledBy(*v)
	}
	return _u
}

// AddRecalledBy adds value to the "recalled_by" field.
func (_u *ChatMessageUpdateOne) AddRecalledBy(v int64) *ChatMessageUpdateOne {
	_u.mutation.AddRecalledBy(v)
	return _u
}

// ClearRecalledBy clears the value of the "recalled_by" field.
func (_u *ChatMessageUpdateOne) ClearRecalledBy() *ChatMessageUpdateOne {
	_u.mutation.ClearRecalledBy()
	return _u
}

// SetConversation sets the "conversation" edge to the ChatConversation entity.
func (_u *ChatMessageUpdateOne) SetConversation(v *ChatConversation) *ChatMessageUpdateOne {
	return _u.SetConversationID(v.ID)
}

// AddAssetIDs adds the "assets" edge to the ChatAsset entity by IDs.
func (_u *ChatMessageUpdateOne) AddAssetIDs(ids ...int64) *ChatMessageUpdateOne {
	_u.mutation.AddAssetIDs(ids...)
	return _u
}

// AddAssets adds the "assets" edges to the ChatAsset entity.
func (_u *ChatMessageUpdateOne) AddAssets(v ...*ChatAsset) *ChatMessageUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAssetIDs(ids...)
}

// Mutation returns the ChatMessageMutation object of the builder.
func (_u *ChatMessageUpdateOne) Mutation() *ChatMessageMutation {
	return _u.mutation
}

// ClearConversation clears the "conversation" edge to the ChatConversation entity.
func (_u *ChatMessageUpdateOne) ClearConversation() *ChatMessageUpdateOne {
	_u.mutation.ClearConversation()
	return _u
}

// ClearAssets clears all "assets" edges to the ChatAsset entity.
func (_u *ChatMessageUpdateOne) ClearAssets() *ChatMessageUpdateOne {
	_u.mutation.ClearAssets()
	return _u
}

// RemoveAssetIDs removes the "assets" edge to ChatAsset entities by IDs.
func (_u *ChatMessageUpdateOne) RemoveAssetIDs(ids ...int64) *ChatMessageUpdateOne {
	_u.mutation.RemoveAssetIDs(ids...)
	return _u
}

// RemoveAssets removes "assets" edges to ChatAsset entities.
func (_u *ChatMessageUpdateOne) RemoveAssets(v ...*ChatAsset) *ChatMessageUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAssetIDs(ids...)
}

// Where appends a list predicates to the ChatMessageUpdate builder.
func (_u *ChatMessageUpdateOne) Where(ps ...predicate.ChatMessage) *ChatMessageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ChatMessageUpdateOne) Select(field string, fields ...string) *ChatMessageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ChatMessage entity.
func (_u *ChatMessageUpdateOne) Save(ctx context.Context) (*ChatMessage, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChatMessageUpdateOne) SaveX(ctx context.Context) *ChatMessage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ChatMessageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChatMessageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChatMessageUpdateOne) check() error {
	if v, ok := _u.mutation.SenderType(); ok {
		if err := chatmessage.SenderTypeValidator(v); err != nil {
			return &ValidationError{Name: "sender_type", err: fmt.Errorf(`ent: validator failed for field "ChatMessage.sender_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := chatmessage.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "ChatMessage.content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Kind(); ok {
		if err := chatmessage.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "ChatMessage.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IdempotencyKey(); ok {
		if err := chatmessage.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`ent: validator failed for field "ChatMessage.idempotency_key": %w`, err)}
		}
	}
	if _u.mutation.ConversationCleared() && len(_u.mutation.ConversationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChatMessage.conversation"`)
	}
	return nil
}

func (_u *ChatMessageUpdateOne) sqlSave(ctx context.Context) (_node *ChatMessage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(chatmessage.Table, chatmessage.Columns, sqlgraph.NewFieldSpec(chatmessage.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ChatMessage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, chatmessage.FieldID)
		for _, f := range fields {
			if !chatmessage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != chatmessage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SenderType(); ok {
		_spec.SetField(chatmessage.FieldSenderType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SenderID(); ok {
		_spec.SetField(chatmessage.FieldSenderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSenderID(); ok {
		_spec.AddField(chatmessage.FieldSenderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(chatmessage.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(chatmessage.FieldKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ReplyToID(); ok {
		_spec.SetField(chatmessage.FieldReplyToID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedReplyToID(); ok {
		_spec.AddField(chatmessage.FieldReplyToID, field.TypeInt64, value)
	}
	if _u.mutation.ReplyToIDCleared() {
		_spec.ClearField(chatmessage.FieldReplyToID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(chatmessage.FieldMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedMetadata(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, chatmessage.FieldMetadata, value)
		})
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(chatmessage.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.IdempotencyKey(); ok {
		_spec.SetField(chatmessage.FieldIdempotencyKey, field.TypeString, value)
	}
	if _u.mutation.IdempotencyKeyCleared() {
		_spec.ClearField(chatmessage.FieldIdempotencyKey, field.TypeString)
	}
	if value, ok := _u.mutation.RecalledAt(); ok {
		_spec.SetField(chatmessage.FieldRecalledAt, field.TypeTime, value)
	}
	if _u.mutation.RecalledAtCleared() {
		_spec.ClearField(chatmessage.FieldRecalledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RecalledBy(); ok {
		_spec.SetField(chatmessage.FieldRecalledBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRecalledBy(); ok {
		_spec.AddField(chatmessage.FieldRecalledBy, field.TypeInt64, value)
	}
	if _u.mutation.RecalledByCleared() {
		_spec.ClearField(chatmessage.FieldRecalledBy, field.TypeInt64)
	}
	if _u.mutation.ConversationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatmessage.ConversationTable,
			Columns: []string{chatmessage.ConversationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatconversation.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConversationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatmessage.ConversationTable,
			Columns: []string{chatmessage.ConversationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatconversation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AssetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   chatmessage.AssetsTable,
			Columns: chatmessage.AssetsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatasset.FieldID, field.TypeInt64),
			},
		}
		createE := &ChatMessageAssetCreate{config: _u.config, mutation: newChatMessageAssetMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAssetsIDs(); len(nodes) > 0 && !_u.mutation.AssetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   chatmessage.AssetsTable,
			Columns: chatmessage.AssetsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatasset.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ChatMessageAssetCreate{config: _u.config, mutation: newChatMessageAssetMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssetsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   chatmessage.AssetsTable,
			Columns: chatmessage.AssetsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatasset.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ChatMessageAssetCreate{config: _u.config, mutation: newChatMessageAssetMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ChatMessage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chatmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
