// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/chatconversation"
	"github.com/Wei-Shaw/sub2api/ent/chatmessage"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ChatConversationCreate is the builder for creating a ChatConversation entity.
type ChatConversationCreate struct {
	config
	mutation *ChatConversationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ChatConversationCreate) SetCreatedAt(v time.Time) *ChatConversationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ChatConversationCreate) SetNillableCreatedAt(v *time.Time) *ChatConversationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ChatConversationCreate) SetUpdatedAt(v time.Time) *ChatConversationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ChatConversationCreate) SetNillableUpdatedAt(v *time.Time) *ChatConversationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *ChatConversationCreate) SetUserID(v int64) *ChatConversationCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetLastMessageAt sets the "last_message_at" field.
func (_c *ChatConversationCreate) SetLastMessageAt(v time.Time) *ChatConversationCreate {
	_c.mutation.SetLastMessageAt(v)
	return _c
}

// SetNillableLastMessageAt sets the "last_message_at" field if the given value is not nil.
func (_c *ChatConversationCreate) SetNillableLastMessageAt(v *time.Time) *ChatConversationCreate {
	if v != nil {
		_c.SetLastMessageAt(*v)
	}
	return _c
}

// SetUnreadByUser sets the "unread_by_user" field.
func (_c *ChatConversationCreate) SetUnreadByUser(v int) *ChatConversationCreate {
	_c.mutation.SetUnreadByUser(v)
	return _c
}

// SetNillableUnreadByUser sets the "unread_by_user" field if the given value is not nil.
func (_c *ChatConversationCreate) SetNillableUnreadByUser(v *int) *ChatConversationCreate {
	if v != nil {
		_c.SetUnreadByUser(*v)
	}
	return _c
}

// SetUnreadByAdmin sets the "unread_by_admin" field.
func (_c *ChatConversationCreate) SetUnreadByAdmin(v int) *ChatConversationCreate {
	_c.mutation.SetUnreadByAdmin(v)
	return _c
}

// SetNillableUnreadByAdmin sets the "unread_by_admin" field if the given value is not nil.
func (_c *ChatConversationCreate) SetNillableUnreadByAdmin(v *int) *ChatConversationCreate {
	if v != nil {
		_c.SetUnreadByAdmin(*v)
	}
	return _c
}

// SetManuallyUnreadByAdmin sets the "manually_unread_by_admin" field.
func (_c *ChatConversationCreate) SetManuallyUnreadByAdmin(v bool) *ChatConversationCreate {
	_c.mutation.SetManuallyUnreadByAdmin(v)
	return _c
}

// SetNillableManuallyUnreadByAdmin sets the "manually_unread_by_admin" field if the given value is not nil.
func (_c *ChatConversationCreate) SetNillableManuallyUnreadByAdmin(v *bool) *ChatConversationCreate {
	if v != nil {
		_c.SetManuallyUnreadByAdmin(*v)
	}
	return _c
}

// SetLastReadByUserAt sets the "last_read_by_user_at" field.
func (_c *ChatConversationCreate) SetLastReadByUserAt(v time.Time) *ChatConversationCreate {
	_c.mutation.SetLastReadByUserAt(v)
	return _c
}

// SetNillableLastReadByUserAt sets the "last_read_by_user_at" field if the given value is not nil.
func (_c *ChatConversationCreate) SetNillableLastReadByUserAt(v *time.Time) *ChatConversationCreate {
	if v != nil {
		_c.SetLastReadByUserAt(*v)
	}
	return _c
}

// SetLastReadByAdminAt sets the "last_read_by_admin_at" field.
func (_c *ChatConversationCreate) SetLastReadByAdminAt(v time.Time) *ChatConversationCreate {
	_c.mutation.SetLastReadByAdminAt(v)
	return _c
}

// SetNillableLastReadByAdminAt sets the "last_read_by_admin_at" field if the given value is not nil.
func (_c *ChatConversationCreate) SetNillableLastReadByAdminAt(v *time.Time) *ChatConversationCreate {
	if v != nil {
		_c.SetLastReadByAdminAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *ChatConversationCreate) SetUser(v *User) *ChatConversationCreate {
	return _c.SetUserID(v.ID)
}

// AddMessageIDs adds the "messages" edge to the ChatMessage entity by IDs.
func (_c *ChatConversationCreate) AddMessageIDs(ids ...int64) *ChatConversationCreate {
	_c.mutation.AddMessageIDs(ids...)
	return _c
}

// AddMessages adds the "messages" edges to the ChatMessage entity.
func (_c *ChatConversationCreate) AddMessages(v ...*ChatMessage) *ChatConversationCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMessageIDs(ids...)
}

// Mutation returns the ChatConversationMutation object of the builder.
func (_c *ChatConversationCreate) Mutation() *ChatConversationMutation {
	return _c.mutation
}

// Save creates the ChatConversation in the database.
func (_c *ChatConversationCreate) Save(ctx context.Context) (*ChatConversation, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChatConversationCreate) SaveX(ctx context.Context) *ChatConversation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChatConversationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChatConversationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ChatConversationCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := chatconversation.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := chatconversation.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.UnreadByUser(); !ok {
		v := chatconversation.DefaultUnreadByUser
		_c.mutation.SetUnreadByUser(v)
	}
	if _, ok := _c.mutation.UnreadByAdmin(); !ok {
		v := chatconversation.DefaultUnreadByAdmin
		_c.mutation.SetUnreadByAdmin(v)
	}
	if _, ok := _c.mutation.ManuallyUnreadByAdmin(); !ok {
		v := chatconversation.DefaultManuallyUnreadByAdmin
		_c.mutation.SetManuallyUnreadByAdmin(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChatConversationCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ChatConversation.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ChatConversation.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "ChatConversation.user_id"`)}
	}
	if _, ok := _c.mutation.UnreadByUser(); !ok {
		return &ValidationError{Name: "unread_by_user", err: errors.New(`ent: missing required field "ChatConversation.unread_by_user"`)}
	}
	if _, ok := _c.mutation.UnreadByAdmin(); !ok {
		return &ValidationError{Name: "unread_by_admin", err: errors.New(`ent: missing required field "ChatConversation.unread_by_admin"`)}
	}
	if _, ok := _c.mutation.ManuallyUnreadByAdmin(); !ok {
		return &ValidationError{Name: "manually_unread_by_admin", err: errors.New(`ent: missing required field "ChatConversation.manually_unread_by_admin"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "ChatConversation.user"`)}
	}
	return nil
}

func (_c *ChatConversationCreate) sqlSave(ctx context.Context) (*ChatConversation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChatConversationCreate) createSpec() (*ChatConversation, *sqlgraph.CreateSpec) {
	var (
		_node = &ChatConversation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(chatconversation.Table, sqlgraph.NewFieldSpec(chatconversation.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(chatconversation.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(chatconversation.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.LastMessageAt(); ok {
		_spec.SetField(chatconversation.FieldLastMessageAt, field.TypeTime, value)
		_node.LastMessageAt = &value
	}
	if value, ok := _c.mutation.UnreadByUser(); ok {
		_spec.SetField(chatconversation.FieldUnreadByUser, field.TypeInt, value)
		_node.UnreadByUser = value
	}
	if value, ok := _c.mutation.UnreadByAdmin(); ok {
		_spec.SetField(chatconversation.FieldUnreadByAdmin, field.TypeInt, value)
		_node.UnreadByAdmin = value
	}
	if value, ok := _c.mutation.ManuallyUnreadByAdmin(); ok {
		_spec.SetField(chatconversation.FieldManuallyUnreadByAdmin, field.TypeBool, value)
		_node.ManuallyUnreadByAdmin = value
	}
	if value, ok := _c.mutation.LastReadByUserAt(); ok {
		_spec.SetField(chatconversation.FieldLastReadByUserAt, field.TypeTime, value)
		_node.LastReadByUserAt = &value
	}
	if value, ok := _c.mutation.LastReadByAdminAt(); ok {
		_spec.SetField(chatconversation.FieldLastReadByAdminAt, field.TypeTime, value)
		_node.LastReadByAdminAt = &value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   chatconversation.UserTable,
			Columns: []string{chatconversation.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatconversation.MessagesTable,
			Columns: []string{chatconversation.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ChatConversation.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChatConversationUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ChatConversationCreate) OnConflict(opts ...sql.ConflictOption) *ChatConversationUpsertOne {
	_c.conflict = opts
	return &ChatConversationUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ChatConversation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChatConversationCreate) OnConflictColumns(columns ...string) *ChatConversationUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChatConversationUpsertOne{
		create: _c,
	}
}

type (
	// ChatConversationUpsertOne is the builder for "upsert"-ing
	//  one ChatConversation node.
	ChatConversationUpsertOne struct {
		create *ChatConversationCreate
	}

	// ChatConversationUpsert is the "OnConflict" setter.
	ChatConversationUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ChatConversationUpsert) SetUpdatedAt(v time.Time) *ChatConversationUpsert {
	u.Set(chatconversation.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChatConversationUpsert) UpdateUpdatedAt() *ChatConversationUpsert {
	u.SetExcluded(chatconversation.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *ChatConversationUpsert) SetUserID(v int64) *ChatConversationUpsert {
	u.Set(chatconversation.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ChatConversationUpsert) UpdateUserID() *ChatConversationUpsert {
	u.SetExcluded(chatconversation.FieldUserID)
	return u
}

// SetLastMessageAt sets the "last_message_at" field.
func (u *ChatConversationUpsert) SetLastMessageAt(v time.Time) *ChatConversationUpsert {
	u.Set(chatconversation.FieldLastMessageAt, v)
	return u
}

// UpdateLastMessageAt sets the "last_message_at" field to the value that was provided on create.
func (u *ChatConversationUpsert) UpdateLastMessageAt() *ChatConversationUpsert {
	u.SetExcluded(chatconversation.FieldLastMessageAt)
	return u
}

// ClearLastMessageAt clears the value of the "last_message_at" field.
func (u *ChatConversationUpsert) ClearLastMessageAt() *ChatConversationUpsert {
	u.SetNull(chatconversation.FieldLastMessageAt)
	return u
}

// SetUnreadByUser sets the "unread_by_user" field.
func (u *ChatConversationUpsert) SetUnreadByUser(v int) *ChatConversationUpsert {
	u.Set(chatconversation.FieldUnreadByUser, v)
	return u
}

// UpdateUnreadByUser sets the "unread_by_user" field to the value that was provided on create.
func (u *ChatConversationUpsert) UpdateUnreadByUser() *ChatConversationUpsert {
	u.SetExcluded(chatconversation.FieldUnreadByUser)
	return u
}

// AddUnreadByUser adds v to the "unread_by_user" field.
func (u *ChatConversationUpsert) AddUnreadByUser(v int) *ChatConversationUpsert {
	u.Add(chatconversation.FieldUnreadByUser, v)
	return u
}

// SetUnreadByAdmin sets the "unread_by_admin" field.
func (u *ChatConversationUpsert) SetUnreadByAdmin(v int) *ChatConversationUpsert {
	u.Set(chatconversation.FieldUnreadByAdmin, v)
	return u
}

// UpdateUnreadByAdmin sets the "unread_by_admin" field to the value that was provided on create.
func (u *ChatConversationUpsert) UpdateUnreadByAdmin() *ChatConversationUpsert {
	u.SetExcluded(chatconversation.FieldUnreadByAdmin)
	return u
}

// AddUnreadByAdmin adds v to the "unread_by_admin" field.
func (u *ChatConversationUpsert) AddUnreadByAdmin(v int) *ChatConversationUpsert {
	u.Add(chatconversation.FieldUnreadByAdmin, v)
	return u
}

// SetManuallyUnreadByAdmin sets the "manually_unread_by_admin" field.
func (u *ChatConversationUpsert) SetManuallyUnreadByAdmin(v bool) *ChatConversationUpsert {
	u.Set(chatconversation.FieldManuallyUnreadByAdmin, v)
	return u
}

// UpdateManuallyUnreadByAdmin sets the "manually_unread_by_admin" field to the value that was provided on create.
func (u *ChatConversationUpsert) UpdateManuallyUnreadByAdmin() *ChatConversationUpsert {
	u.SetExcluded(chatconversation.FieldManuallyUnreadByAdmin)
	return u
}

// SetLastReadByUserAt sets the "last_read_by_user_at" field.
func (u *ChatConversationUpsert) SetLastReadByUserAt(v time.Time) *ChatConversationUpsert {
	u.Set(chatconversation.FieldLastReadByUserAt, v)
	return u
}

// UpdateLastReadByUserAt sets the "last_read_by_user_at" field to the value that was provided on create.
func (u *ChatConversationUpsert) UpdateLastReadByUserAt() *ChatConversationUpsert {
	u.SetExcluded(chatconversation.FieldLastReadByUserAt)
	return u
}

// ClearLastReadByUserAt clears the value of the "last_read_by_user_at" field.
func (u *ChatConversationUpsert) ClearLastReadByUserAt() *ChatConversationUpsert {
	u.SetNull(chatconversation.FieldLastReadByUserAt)
	return u
}

// SetLastReadByAdminAt sets the "last_read_by_admin_at" field.
func (u *ChatConversationUpsert) SetLastReadByAdminAt(v time.Time) *ChatConversationUpsert {
	u.Set(chatconversation.FieldLastReadByAdminAt, v)
	return u
}

// UpdateLastReadByAdminAt sets the "last_read_by_admin_at" field to the value that was provided on create.
func (u *ChatConversationUpsert) UpdateLastReadByAdminAt() *ChatConversationUpsert {
	u.SetExcluded(chatconversation.FieldLastReadByAdminAt)
	return u
}

// ClearLastReadByAdminAt clears the value of the "last_read_by_admin_at" field.
func (u *ChatConversationUpsert) ClearLastReadByAdminAt() *ChatConversationUpsert {
	u.SetNull(chatconversation.FieldLastReadByAdminAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ChatConversation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ChatConversationUpsertOne) UpdateNewValues() *ChatConversationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(chatconversation.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ChatConversation.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ChatConversationUpsertOne) Ignore() *ChatConversationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChatConversationUpsertOne) DoNothing() *ChatConversationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChatConversationCreate.OnConflict
// documentation for more info.
func (u *ChatConversationUpsertOne) Update(set func(*ChatConversationUpsert)) *ChatConversationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChatConversationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ChatConversationUpsertOne) SetUpdatedAt(v time.Time) *ChatConversationUpsertOne {
	return u.Update(func(s *ChatConversationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChatConversationUpsertOne) UpdateUpdatedAt() *ChatConversationUpsertOne {
	return u.Update(func(s *ChatConversationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *ChatConversationUpsertOne) SetUserID(v int64) *ChatConversationUpsertOne {
	return u.Update(func(s *ChatConversationUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ChatConversationUpsertOne) UpdateUserID() *ChatConversationUpsertOne {
	return u.Update(func(s *ChatConversationUpsert) {
		s.UpdateUserID()
	})
}

// SetLastMessageAt sets the "last_message_at" field.
func (u *ChatConversationUpsertOne) SetLastMessageAt(v time.Time) *ChatConversationUpsertOne {
	return u.Update(func(s *ChatConversationUpsert) {
		s.SetLastMessageAt(v)
	})
}

// UpdateLastMessageAt sets the "last_message_at" field to the value that was provided on create.
func (u *ChatConversationUpsertOne) UpdateLastMessageAt() *ChatConversationUpsertOne {
	return u.Update(func(s *ChatConversationUpsert) {
		s.UpdateLastMessageAt()
	})
}

// ClearLastMessageAt clears the value of the "last_message_at" field.
func (u *ChatConversationUpsertOne) ClearLastMessageAt() *ChatConversationUpsertOne {
	return u.Update(func(s *ChatConversationUpsert) {
		s.ClearLastMessageAt()
	})
}

// SetUnreadByUser sets the "unread_by_user" field.
func (u *ChatConversationUpsertOne) SetUnreadByUser(v int) *ChatConversationUpsertOne {
	return u.Update(func(s *ChatConversationUpsert) {
		s.SetUnreadByUser(v)
	})
}

// AddUnreadByUser adds v to the "unread_by_user" field.
func (u *ChatConversationUpsertOne) AddUnreadByUser(v int) *ChatConversationUpsertOne {
	return u.Update(func(s *ChatConversationUpsert) {
		s.AddUnreadByUser(v)
	})
}

// UpdateUnreadByUser sets the "unread_by_user" field to the value that was provided on create.
func (u *ChatConversationUpsertOne) UpdateUnreadByUser() *ChatConversationUpsertOne {
	return u.Update(func(s *ChatConversationUpsert) {
		s.UpdateUnreadByUser()
	})
}

// SetUnreadByAdmin sets the "unread_by_admin" field.
func (u *ChatConversationUpsertOne) SetUnreadByAdmin(v int) *ChatConversationUpsertOne {
	return u.Update(func(s *ChatConversationUpsert) {
		s.SetUnreadByAdmin(v)
	})
}

// AddUnreadByAdmin adds v to the "unread_by_admin" field.
func (u *ChatConversationUpsertOne) AddUnreadByAdmin(v int) *ChatConversationUpsertOne {
	return u.Update(func(s *ChatConversationUpsert) {
		s.AddUnreadByAdmin(v)
	})
}

// UpdateUnreadByAdmin sets the "unread_by_admin" field to the value that was provided on create.
func (u *ChatConversationUpsertOne) UpdateUnreadByAdmin() *ChatConversationUpsertOne {
	return u.Update(func(s *ChatConversationUpsert) {
		s.UpdateUnreadByAdmin()
	})
}

// SetManuallyUnreadByAdmin sets the "manually_unread_by_admin" field.
func (u *ChatConversationUpsertOne) SetManuallyUnreadByAdmin(v bool) *ChatConversationUpsertOne {
	return u.Update(func(s *ChatConversationUpsert) {
		s.SetManuallyUnreadByAdmin(v)
	})
}

// UpdateManuallyUnreadByAdmin sets the "manually_unread_by_admin" field to the value that was provided on create.
func (u *ChatConversationUpsertOne) UpdateManuallyUnreadByAdmin() *ChatConversationUpsertOne {
	return u.Update(func(s *ChatConversationUpsert) {
		s.UpdateManuallyUnreadByAdmin()
	})
}

// SetLastReadByUserAt sets the "last_read_by_user_at" field.
func (u *ChatConversationUpsertOne) SetLastReadByUserAt(v time.Time) *ChatConversationUpsertOne {
	return u.Update(func(s *ChatConversationUpsert) {
		s.SetLastReadByUserAt(v)
	})
}

// UpdateLastReadByUserAt sets the "last_read_by_user_at" field to the value that was provided on create.
func (u *ChatConversationUpsertOne) UpdateLastReadByUserAt() *ChatConversationUpsertOne {
	return u.Update(func(s *ChatConversationUpsert) {
		s.UpdateLastReadByUserAt()
	})
}

// ClearLastReadByUserAt clears the value of the "last_read_by_user_at" field.
func (u *ChatConversationUpsertOne) ClearLastReadByUserAt() *ChatConversationUpsertOne {
	return u.Update(func(s *ChatConversationUpsert) {
		s.ClearLastReadByUserAt()
	})
}

// SetLastReadByAdminAt sets the "last_read_by_admin_at" field.
func (u *ChatConversationUpsertOne) SetLastReadByAdminAt(v time.Time) *ChatConversationUpsertOne {
	return u.Update(func(s *ChatConversationUpsert) {
		s.SetLastReadByAdminAt(v)
	})
}

// UpdateLastReadByAdminAt sets the "last_read_by_admin_at" field to the value that was provided on create.
func (u *ChatConversationUpsertOne) UpdateLastReadByAdminAt() *ChatConversationUpsertOne {
	return u.Update(func(s *ChatConversationUpsert) {
		s.UpdateLastReadByAdminAt()
	})
}

// ClearLastReadByAdminAt clears the value of the "last_read_by_admin_at" field.
func (u *ChatConversationUpsertOne) ClearLastReadByAdminAt() *ChatConversationUpsertOne {
	return u.Update(func(s *ChatConversationUpsert) {
		s.ClearLastReadByAdminAt()
	})
}

// Exec executes the query.
func (u *ChatConversationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChatConversationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChatConversationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ChatConversationUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ChatConversationUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ChatConversationCreateBulk is the builder for creating many ChatConversation entities in bulk.
type ChatConversationCreateBulk struct {
	config
	err      error
	builders []*ChatConversationCreate
	conflict []sql.ConflictOption
}

// Save creates the ChatConversation entities in the database.
func (_c *ChatConversationCreateBulk) Save(ctx context.Context) ([]*ChatConversation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ChatConversation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChatConversationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChatConversationCreateBulk) SaveX(ctx context.Context) []*ChatConversation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChatConversationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChatConversationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ChatConversation.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChatConversationUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ChatConversationCreateBulk) OnConflict(opts ...sql.ConflictOption) *ChatConversationUpsertBulk {
	_c.conflict = opts
	return &ChatConversationUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ChatConversation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChatConversationCreateBulk) OnConflictColumns(columns ...string) *ChatConversationUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChatConversationUpsertBulk{
		create: _c,
	}
}

// ChatConversationUpsertBulk is the builder for "upsert"-ing
// a bulk of ChatConversation nodes.
type ChatConversationUpsertBulk struct {
	create *ChatConversationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ChatConversation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ChatConversationUpsertBulk) UpdateNewValues() *ChatConversationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(chatconversation.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ChatConversation.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ChatConversationUpsertBulk) Ignore() *ChatConversationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChatConversationUpsertBulk) DoNothing() *ChatConversationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChatConversationCreateBulk.OnConflict
// documentation for more info.
func (u *ChatConversationUpsertBulk) Update(set func(*ChatConversationUpsert)) *ChatConversationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChatConversationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ChatConversationUpsertBulk) SetUpdatedAt(v time.Time) *ChatConversationUpsertBulk {
	return u.Update(func(s *ChatConversationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChatConversationUpsertBulk) UpdateUpdatedAt() *ChatConversationUpsertBulk {
	return u.Update(func(s *ChatConversationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *ChatConversationUpsertBulk) SetUserID(v int64) *ChatConversationUpsertBulk {
	return u.Update(func(s *ChatConversationUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ChatConversationUpsertBulk) UpdateUserID() *ChatConversationUpsertBulk {
	return u.Update(func(s *ChatConversationUpsert) {
		s.UpdateUserID()
	})
}

// SetLastMessageAt sets the "last_message_at" field.
func (u *ChatConversationUpsertBulk) SetLastMessageAt(v time.Time) *ChatConversationUpsertBulk {
	return u.Update(func(s *ChatConversationUpsert) {
		s.SetLastMessageAt(v)
	})
}

// UpdateLastMessageAt sets the "last_message_at" field to the value that was provided on create.
func (u *ChatConversationUpsertBulk) UpdateLastMessageAt() *ChatConversationUpsertBulk {
	return u.Update(func(s *ChatConversationUpsert) {
		s.UpdateLastMessageAt()
	})
}

// ClearLastMessageAt clears the value of the "last_message_at" field.
func (u *ChatConversationUpsertBulk) ClearLastMessageAt() *ChatConversationUpsertBulk {
	return u.Update(func(s *ChatConversationUpsert) {
		s.ClearLastMessageAt()
	})
}

// SetUnreadByUser sets the "unread_by_user" field.
func (u *ChatConversationUpsertBulk) SetUnreadByUser(v int) *ChatConversationUpsertBulk {
	return u.Update(func(s *ChatConversationUpsert) {
		s.SetUnreadByUser(v)
	})
}

// AddUnreadByUser adds v to the "unread_by_user" field.
func (u *ChatConversationUpsertBulk) AddUnreadByUser(v int) *ChatConversationUpsertBulk {
	return u.Update(func(s *ChatConversationUpsert) {
		s.AddUnreadByUser(v)
	})
}

// UpdateUnreadByUser sets the "unread_by_user" field to the value that was provided on create.
func (u *ChatConversationUpsertBulk) UpdateUnreadByUser() *ChatConversationUpsertBulk {
	return u.Update(func(s *ChatConversationUpsert) {
		s.UpdateUnreadByUser()
	})
}

// SetUnreadByAdmin sets the "unread_by_admin" field.
func (u *ChatConversationUpsertBulk) SetUnreadByAdmin(v int) *ChatConversationUpsertBulk {
	return u.Update(func(s *ChatConversationUpsert) {
		s.SetUnreadByAdmin(v)
	})
}

// AddUnreadByAdmin adds v to the "unread_by_admin" field.
func (u *ChatConversationUpsertBulk) AddUnreadByAdmin(v int) *ChatConversationUpsertBulk {
	return u.Update(func(s *ChatConversationUpsert) {
		s.AddUnreadByAdmin(v)
	})
}

// UpdateUnreadByAdmin sets the "unread_by_admin" field to the value that was provided on create.
func (u *ChatConversationUpsertBulk) UpdateUnreadByAdmin() *ChatConversationUpsertBulk {
	return u.Update(func(s *ChatConversationUpsert) {
		s.UpdateUnreadByAdmin()
	})
}

// SetManuallyUnreadByAdmin sets the "manually_unread_by_admin" field.
func (u *ChatConversationUpsertBulk) SetManuallyUnreadByAdmin(v bool) *ChatConversationUpsertBulk {
	return u.Update(func(s *ChatConversationUpsert) {
		s.SetManuallyUnreadByAdmin(v)
	})
}

// UpdateManuallyUnreadByAdmin sets the "manually_unread_by_admin" field to the value that was provided on create.
func (u *ChatConversationUpsertBulk) UpdateManuallyUnreadByAdmin() *ChatConversationUpsertBulk {
	return u.Update(func(s *ChatConversationUpsert) {
		s.UpdateManuallyUnreadByAdmin()
	})
}

// SetLastReadByUserAt sets the "last_read_by_user_at" field.
func (u *ChatConversationUpsertBulk) SetLastReadByUserAt(v time.Time) *ChatConversationUpsertBulk {
	return u.Update(func(s *ChatConversationUpsert) {
		s.SetLastReadByUserAt(v)
	})
}

// UpdateLastReadByUserAt sets the "last_read_by_user_at" field to the value that was provided on create.
func (u *ChatConversationUpsertBulk) UpdateLastReadByUserAt() *ChatConversationUpsertBulk {
	return u.Update(func(s *ChatConversationUpsert) {
		s.UpdateLastReadByUserAt()
	})
}

// ClearLastReadByUserAt clears the value of the "last_read_by_user_at" field.
func (u *ChatConversationUpsertBulk) ClearLastReadByUserAt() *ChatConversationUpsertBulk {
	return u.Update(func(s *ChatConversationUpsert) {
		s.ClearLastReadByUserAt()
	})
}

// SetLastReadByAdminAt sets the "last_read_by_admin_at" field.
func (u *ChatConversationUpsertBulk) SetLastReadByAdminAt(v time.Time) *ChatConversationUpsertBulk {
	return u.Update(func(s *ChatConversationUpsert) {
		s.SetLastReadByAdminAt(v)
	})
}

// UpdateLastReadByAdminAt sets the "last_read_by_admin_at" field to the value that was provided on create.
func (u *ChatConversationUpsertBulk) UpdateLastReadByAdminAt() *ChatConversationUpsertBulk {
	return u.Update(func(s *ChatConversationUpsert) {
		s.UpdateLastReadByAdminAt()
	})
}

// ClearLastReadByAdminAt clears the value of the "last_read_by_admin_at" field.
func (u *ChatConversationUpsertBulk) ClearLastReadByAdminAt() *ChatConversationUpsertBulk {
	return u.Update(func(s *ChatConversationUpsert) {
		s.ClearLastReadByAdminAt()
	})
}

// Exec executes the query.
func (u *ChatConversationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ChatConversationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChatConversationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChatConversationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
