// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/chatasset"
	"github.com/Wei-Shaw/sub2api/ent/chatmessage"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ChatAssetUpdate is the builder for updating ChatAsset entities.
type ChatAssetUpdate struct {
	config
	hooks    []Hook
	mutation *ChatAssetMutation
}

// Where appends a list predicates to the ChatAssetUpdate builder.
func (_u *ChatAssetUpdate) Where(ps ...predicate.ChatAsset) *ChatAssetUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetScope sets the "scope" field.
func (_u *ChatAssetUpdate) SetScope(v chatasset.Scope) *ChatAssetUpdate {
	_u.mutation.SetScope(v)
	return _u
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_u *ChatAssetUpdate) SetNillableScope(v *chatasset.Scope) *ChatAssetUpdate {
	if v != nil {
		_u.SetScope(*v)
	}
	return _u
}

// SetConversationID sets the "conversation_id" field.
func (_u *ChatAssetUpdate) SetConversationID(v int64) *ChatAssetUpdate {
	_u.mutation.ResetConversationID()
	_u.mutation.SetConversationID(v)
	return _u
}

// SetNillableConversationID sets the "conversation_id" field if the given value is not nil.
func (_u *ChatAssetUpdate) SetNillableConversationID(v *int64) *ChatAssetUpdate {
	if v != nil {
		_u.SetConversationID(*v)
	}
	return _u
}

// AddConversationID adds value to the "conversation_id" field.
func (_u *ChatAssetUpdate) AddConversationID(v int64) *ChatAssetUpdate {
	_u.mutation.AddConversationID(v)
	return _u
}

// ClearConversationID clears the value of the "conversation_id" field.
func (_u *ChatAssetUpdate) ClearConversationID() *ChatAssetUpdate {
	_u.mutation.ClearConversationID()
	return _u
}

// SetUploadedBy sets the "uploaded_by" field.
func (_u *ChatAssetUpdate) SetUploadedBy(v int64) *ChatAssetUpdate {
	_u.mutation.ResetUploadedBy()
	_u.mutation.SetUploadedBy(v)
	return _u
}

// SetNillableUploadedBy sets the "uploaded_by" field if the given value is not nil.
func (_u *ChatAssetUpdate) SetNillableUploadedBy(v *int64) *ChatAssetUpdate {
	if v != nil {
		_u.SetUploadedBy(*v)
	}
	return _u
}

// AddUploadedBy adds value to the "uploaded_by" field.
func (_u *ChatAssetUpdate) AddUploadedBy(v int64) *ChatAssetUpdate {
	_u.mutation.AddUploadedBy(v)
	return _u
}

// ClearUploadedBy clears the value of the "uploaded_by" field.
func (_u *ChatAssetUpdate) ClearUploadedBy() *ChatAssetUpdate {
	_u.mutation.ClearUploadedBy()
	return _u
}

// SetName sets the "name" field.
func (_u *ChatAssetUpdate) SetName(v string) *ChatAssetUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ChatAssetUpdate) SetNillableName(v *string) *ChatAssetUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetMimeType sets the "mime_type" field.
func (_u *ChatAssetUpdate) SetMimeType(v string) *ChatAssetUpdate {
	_u.mutation.SetMimeType(v)
	return _u
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_u *ChatAssetUpdate) SetNillableMimeType(v *string) *ChatAssetUpdate {
	if v != nil {
		_u.SetMimeType(*v)
	}
	return _u
}

// SetSize sets the "size" field.
func (_u *ChatAssetUpdate) SetSize(v int) *ChatAssetUpdate {
	_u.mutation.ResetSize()
	_u.mutation.SetSize(v)
	return _u
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_u *ChatAssetUpdate) SetNillableSize(v *int) *ChatAssetUpdate {
	if v != nil {
		_u.SetSize(*v)
	}
	return _u
}

// AddSize adds value to the "size" field.
func (_u *ChatAssetUpdate) AddSize(v int) *ChatAssetUpdate {
	_u.mutation.AddSize(v)
	return _u
}

// SetData sets the "data" field.
func (_u *ChatAssetUpdate) SetData(v []byte) *ChatAssetUpdate {
	_u.mutation.SetData(v)
	return _u
}

// SetCollection sets the "collection" field.
func (_u *ChatAssetUpdate) SetCollection(v string) *ChatAssetUpdate {
	_u.mutation.SetCollection(v)
	return _u
}

// SetNillableCollection sets the "collection" field if the given value is not nil.
func (_u *ChatAssetUpdate) SetNillableCollection(v *string) *ChatAssetUpdate {
	if v != nil {
		_u.SetCollection(*v)
	}
	return _u
}

// SetCatalogVisible sets the "catalog_visible" field.
func (_u *ChatAssetUpdate) SetCatalogVisible(v bool) *ChatAssetUpdate {
	_u.mutation.SetCatalogVisible(v)
	return _u
}

// SetNillableCatalogVisible sets the "catalog_visible" field if the given value is not nil.
func (_u *ChatAssetUpdate) SetNillableCatalogVisible(v *bool) *ChatAssetUpdate {
	if v != nil {
		_u.SetCatalogVisible(*v)
	}
	return _u
}

// AddMessageIDs adds the "messages" edge to the ChatMessage entity by IDs.
func (_u *ChatAssetUpdate) AddMessageIDs(ids ...int64) *ChatAssetUpdate {
	_u.mutation.AddMessageIDs(ids...)
	return _u
}

// AddMessages adds the "messages" edges to the ChatMessage entity.
func (_u *ChatAssetUpdate) AddMessages(v ...*ChatMessage) *ChatAssetUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMessageIDs(ids...)
}

// Mutation returns the ChatAssetMutation object of the builder.
func (_u *ChatAssetUpdate) Mutation() *ChatAssetMutation {
	return _u.mutation
}

// ClearMessages clears all "messages" edges to the ChatMessage entity.
func (_u *ChatAssetUpdate) ClearMessages() *ChatAssetUpdate {
	_u.mutation.ClearMessages()
	return _u
}

// RemoveMessageIDs removes the "messages" edge to ChatMessage entities by IDs.
func (_u *ChatAssetUpdate) RemoveMessageIDs(ids ...int64) *ChatAssetUpdate {
	_u.mutation.RemoveMessageIDs(ids...)
	return _u
}

// RemoveMessages removes "messages" edges to ChatMessage entities.
func (_u *ChatAssetUpdate) RemoveMessages(v ...*ChatMessage) *ChatAssetUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMessageIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ChatAssetUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChatAssetUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ChatAssetUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChatAssetUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChatAssetUpdate) check() error {
	if v, ok := _u.mutation.Scope(); ok {
		if err := chatasset.ScopeValidator(v); err != nil {
			return &ValidationError{Name: "scope", err: fmt.Errorf(`ent: validator failed for field "ChatAsset.scope": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := chatasset.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ChatAsset.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MimeType(); ok {
		if err := chatasset.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "ChatAsset.mime_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Collection(); ok {
		if err := chatasset.CollectionValidator(v); err != nil {
			return &ValidationError{Name: "collection", err: fmt.Errorf(`ent: validator failed for field "ChatAsset.collection": %w`, err)}
		}
	}
	return nil
}

func (_u *ChatAssetUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(chatasset.Table, chatasset.Columns, sqlgraph.NewFieldSpec(chatasset.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Scope(); ok {
		_spec.SetField(chatasset.FieldScope, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ConversationID(); ok {
		_spec.SetField(chatasset.FieldConversationID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedConversationID(); ok {
		_spec.AddField(chatasset.FieldConversationID, field.TypeInt64, value)
	}
	if _u.mutation.ConversationIDCleared() {
		_spec.ClearField(chatasset.FieldConversationID, field.TypeInt64)
	}
	if value, ok := _u.mutation.UploadedBy(); ok {
		_spec.SetField(chatasset.FieldUploadedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUploadedBy(); ok {
		_spec.AddField(chatasset.FieldUploadedBy, field.TypeInt64, value)
	}
	if _u.mutation.UploadedByCleared() {
		_spec.ClearField(chatasset.FieldUploadedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(chatasset.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.MimeType(); ok {
		_spec.SetField(chatasset.FieldMimeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Size(); ok {
		_spec.SetField(chatasset.FieldSize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSize(); ok {
		_spec.AddField(chatasset.FieldSize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Data(); ok {
		_spec.SetField(chatasset.FieldData, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.Collection(); ok {
		_spec.SetField(chatasset.FieldCollection, field.TypeString, value)
	}
	if value, ok := _u.mutation.CatalogVisible(); ok {
		_spec.SetField(chatasset.FieldCatalogVisible, field.TypeBool, value)
	}
	if _u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   chatasset.MessagesTable,
			Columns: chatasset.MessagesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatmessage.FieldID, field.TypeInt64),
			},
		}
		createE := &ChatMessageAssetCreate{config: _u.config, mutation: newChatMessageAssetMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMessagesIDs(); len(nodes) > 0 && !_u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   chatasset.MessagesTable,
			Columns: chatasset.MessagesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ChatMessageAssetCreate{config: _u.config, mutation: newChatMessageAssetMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   chatasset.MessagesTable,
			Columns: chatasset.MessagesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ChatMessageAssetCreate{config: _u.config, mutation: newChatMessageAssetMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chatasset.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ChatAssetUpdateOne is the builder for updating a single ChatAsset entity.
type ChatAssetUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChatAssetMutation
}

// SetScope sets the "scope" field.
func (_u *ChatAssetUpdateOne) SetScope(v chatasset.Scope) *ChatAssetUpdateOne {
	_u.mutation.SetScope(v)
	return _u
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_u *ChatAssetUpdateOne) SetNillableScope(v *chatasset.Scope) *ChatAssetUpdateOne {
	if v != nil {
		_u.SetScope(*v)
	}
	return _u
}

// SetConversationID sets the "conversation_id" field.
func (_u *ChatAssetUpdateOne) SetConversationID(v int64) *ChatAssetUpdateOne {
	_u.mutation.ResetConversationID()
	_u.mutation.SetConversationID(v)
	return _u
}

// SetNillableConversationID sets the "conversation_id" field if the given value is not nil.
func (_u *ChatAssetUpdateOne) SetNillableConversationID(v *int64) *ChatAssetUpdateOne {
	if v != nil {
		_u.SetConversationID(*v)
	}
	return _u
}

// AddConversationID adds value to the "conversation_id" field.
func (_u *ChatAssetUpdateOne) AddConversationID(v int64) *ChatAssetUpdateOne {
	_u.mutation.AddConversationID(v)
	return _u
}

// ClearConversationID clears the value of the "conversation_id" field.
func (_u *ChatAssetUpdateOne) ClearConversationID() *ChatAssetUpdateOne {
	_u.mutation.ClearConversationID()
	return _u
}

// SetUploadedBy sets the "uploaded_by" field.
func (_u *ChatAssetUpdateOne) SetUploadedBy(v int64) *ChatAssetUpdateOne {
	_u.mutation.ResetUploadedBy()
	_u.mutation.SetUploadedBy(v)
	return _u
}

// SetNillableUploadedBy sets the "uploaded_by" field if the given value is not nil.
func (_u *ChatAssetUpdateOne) SetNillableUploadedBy(v *int64) *ChatAssetUpdateOne {
	if v != nil {
		_u.SetUploadedBy(*v)
	}
	return _u
}

// AddUploadedBy adds value to the "uploaded_by" field.
func (_u *ChatAssetUpdateOne) AddUploadedBy(v int64) *ChatAssetUpdateOne {
	_u.mutation.AddUploadedBy(v)
	return _u
}

// ClearUploadedBy clears the value of the "uploaded_by" field.
func (_u *ChatAssetUpdateOne) ClearUploadedBy() *ChatAssetUpdateOne {
	_u.mutation.ClearUploadedBy()
	return _u
}

// SetName sets the "name" field.
func (_u *ChatAssetUpdateOne) SetName(v string) *ChatAssetUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ChatAssetUpdateOne) SetNillableName(v *string) *ChatAssetUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetMimeType sets the "mime_type" field.
func (_u *ChatAssetUpdateOne) SetMimeType(v string) *ChatAssetUpdateOne {
	_u.mutation.SetMimeType(v)
	return _u
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_u *ChatAssetUpdateOne) SetNillableMimeType(v *string) *ChatAssetUpdateOne {
	if v != nil {
		_u.SetMimeType(*v)
	}
	return _u
}

// SetSize sets the "size" field.
func (_u *ChatAssetUpdateOne) SetSize(v int) *ChatAssetUpdateOne {
	_u.mutation.ResetSize()
	_u.mutation.SetSize(v)
	return _u
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_u *ChatAssetUpdateOne) SetNillableSize(v *int) *ChatAssetUpdateOne {
	if v != nil {
		_u.SetSize(*v)
	}
	return _u
}

// AddSize adds value to the "size" field.
func (_u *ChatAssetUpdateOne) AddSize(v int) *ChatAssetUpdateOne {
	_u.mutation.AddSize(v)
	return _u
}

// SetData sets the "data" field.
func (_u *ChatAssetUpdateOne) SetData(v []byte) *ChatAssetUpdateOne {
	_u.mutation.SetData(v)
	return _u
}

// SetCollection sets the "collection" field.
func (_u *ChatAssetUpdateOne) SetCollection(v string) *ChatAssetUpdateOne {
	_u.mutation.SetCollection(v)
	return _u
}

// SetNillableCollection sets the "collection" field if the given value is not nil.
func (_u *ChatAssetUpdateOne) SetNillableCollection(v *string) *ChatAssetUpdateOne {
	if v != nil {
		_u.SetCollection(*v)
	}
	return _u
}

// SetCatalogVisible sets the "catalog_visible" field.
func (_u *ChatAssetUpdateOne) SetCatalogVisible(v bool) *ChatAssetUpdateOne {
	_u.mutation.SetCatalogVisible(v)
	return _u
}

// SetNillableCatalogVisible sets the "catalog_visible" field if the given value is not nil.
func (_u *ChatAssetUpdateOne) SetNillableCatalogVisible(v *bool) *ChatAssetUpdateOne {
	if v != nil {
		_u.SetCatalogVisible(*v)
	}
	return _u
}

// AddMessageIDs adds the "messages" edge to the ChatMessage entity by IDs.
func (_u *ChatAssetUpdateOne) AddMessageIDs(ids ...int64) *ChatAssetUpdateOne {
	_u.mutation.AddMessageIDs(ids...)
	return _u
}

// AddMessages adds the "messages" edges to the ChatMessage entity.
func (_u *ChatAssetUpdateOne) AddMessages(v ...*ChatMessage) *ChatAssetUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMessageIDs(ids...)
}

// Mutation returns the ChatAssetMutation object of the builder.
func (_u *ChatAssetUpdateOne) Mutation() *ChatAssetMutation {
	return _u.mutation
}

// ClearMessages clears all "messages" edges to the ChatMessage entity.
func (_u *ChatAssetUpdateOne) ClearMessages() *ChatAssetUpdateOne {
	_u.mutation.ClearMessages()
	return _u
}

// RemoveMessageIDs removes the "messages" edge to ChatMessage entities by IDs.
func (_u *ChatAssetUpdateOne) RemoveMessageIDs(ids ...int64) *ChatAssetUpdateOne {
	_u.mutation.RemoveMessageIDs(ids...)
	return _u
}

// RemoveMessages removes "messages" edges to ChatMessage entities.
func (_u *ChatAssetUpdateOne) RemoveMessages(v ...*ChatMessage) *ChatAssetUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMessageIDs(ids...)
}

// Where appends a list predicates to the ChatAssetUpdate builder.
func (_u *ChatAssetUpdateOne) Where(ps ...predicate.ChatAsset) *ChatAssetUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ChatAssetUpdateOne) Select(field string, fields ...string) *ChatAssetUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ChatAsset entity.
func (_u *ChatAssetUpdateOne) Save(ctx context.Context) (*ChatAsset, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChatAssetUpdateOne) SaveX(ctx context.Context) *ChatAsset {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ChatAssetUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChatAssetUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChatAssetUpdateOne) check() error {
	if v, ok := _u.mutation.Scope(); ok {
		if err := chatasset.ScopeValidator(v); err != nil {
			return &ValidationError{Name: "scope", err: fmt.Errorf(`ent: validator failed for field "ChatAsset.scope": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := chatasset.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ChatAsset.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MimeType(); ok {
		if err := chatasset.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "ChatAsset.mime_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Collection(); ok {
		if err := chatasset.CollectionValidator(v); err != nil {
			return &ValidationError{Name: "collection", err: fmt.Errorf(`ent: validator failed for field "ChatAsset.collection": %w`, err)}
		}
	}
	return nil
}

func (_u *ChatAssetUpdateOne) sqlSave(ctx context.Context) (_node *ChatAsset, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(chatasset.Table, chatasset.Columns, sqlgraph.NewFieldSpec(chatasset.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ChatAsset.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, chatasset.FieldID)
		for _, f := range fields {
			if !chatasset.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != chatasset.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Scope(); ok {
		_spec.SetField(chatasset.FieldScope, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ConversationID(); ok {
		_spec.SetField(chatasset.FieldConversationID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedConversationID(); ok {
		_spec.AddField(chatasset.FieldConversationID, field.TypeInt64, value)
	}
	if _u.mutation.ConversationIDCleared() {
		_spec.ClearField(chatasset.FieldConversationID, field.TypeInt64)
	}
	if value, ok := _u.mutation.UploadedBy(); ok {
		_spec.SetField(chatasset.FieldUploadedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUploadedBy(); ok {
		_spec.AddField(chatasset.FieldUploadedBy, field.TypeInt64, value)
	}
	if _u.mutation.UploadedByCleared() {
		_spec.ClearField(chatasset.FieldUploadedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(chatasset.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.MimeType(); ok {
		_spec.SetField(chatasset.FieldMimeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Size(); ok {
		_spec.SetField(chatasset.FieldSize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSize(); ok {
		_spec.AddField(chatasset.FieldSize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Data(); ok {
		_spec.SetField(chatasset.FieldData, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.Collection(); ok {
		_spec.SetField(chatasset.FieldCollection, field.TypeString, value)
	}
	if value, ok := _u.mutation.CatalogVisible(); ok {
		_spec.SetField(chatasset.FieldCatalogVisible, field.TypeBool, value)
	}
	if _u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   chatasset.MessagesTable,
			Columns: chatasset.MessagesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatmessage.FieldID, field.TypeInt64),
			},
		}
		createE := &ChatMessageAssetCreate{config: _u.config, mutation: newChatMessageAssetMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMessagesIDs(); len(nodes) > 0 && !_u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   chatasset.MessagesTable,
			Columns: chatasset.MessagesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ChatMessageAssetCreate{config: _u.config, mutation: newChatMessageAssetMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   chatasset.MessagesTable,
			Columns: chatasset.MessagesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ChatMessageAssetCreate{config: _u.config, mutation: newChatMessageAssetMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ChatAsset{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chatasset.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
