// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/accountegressbinding"
	"github.com/Wei-Shaw/sub2api/ent/ipv6egresspool"
)

// IPv6EgressPoolCreate is the builder for creating a IPv6EgressPool entity.
type IPv6EgressPoolCreate struct {
	config
	mutation *IPv6EgressPoolMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *IPv6EgressPoolCreate) SetCreatedAt(v time.Time) *IPv6EgressPoolCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *IPv6EgressPoolCreate) SetNillableCreatedAt(v *time.Time) *IPv6EgressPoolCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *IPv6EgressPoolCreate) SetUpdatedAt(v time.Time) *IPv6EgressPoolCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *IPv6EgressPoolCreate) SetNillableUpdatedAt(v *time.Time) *IPv6EgressPoolCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *IPv6EgressPoolCreate) SetName(v string) *IPv6EgressPoolCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetCidr sets the "cidr" field.
func (_c *IPv6EgressPoolCreate) SetCidr(v string) *IPv6EgressPoolCreate {
	_c.mutation.SetCidr(v)
	return _c
}

// SetNodeID sets the "node_id" field.
func (_c *IPv6EgressPoolCreate) SetNodeID(v string) *IPv6EgressPoolCreate {
	_c.mutation.SetNodeID(v)
	return _c
}

// SetNillableNodeID sets the "node_id" field if the given value is not nil.
func (_c *IPv6EgressPoolCreate) SetNillableNodeID(v *string) *IPv6EgressPoolCreate {
	if v != nil {
		_c.SetNodeID(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *IPv6EgressPoolCreate) SetStatus(v string) *IPv6EgressPoolCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *IPv6EgressPoolCreate) SetNillableStatus(v *string) *IPv6EgressPoolCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetIsDefault sets the "is_default" field.
func (_c *IPv6EgressPoolCreate) SetIsDefault(v bool) *IPv6EgressPoolCreate {
	_c.mutation.SetIsDefault(v)
	return _c
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_c *IPv6EgressPoolCreate) SetNillableIsDefault(v *bool) *IPv6EgressPoolCreate {
	if v != nil {
		_c.SetIsDefault(*v)
	}
	return _c
}

// SetAllocationVersion sets the "allocation_version" field.
func (_c *IPv6EgressPoolCreate) SetAllocationVersion(v int64) *IPv6EgressPoolCreate {
	_c.mutation.SetAllocationVersion(v)
	return _c
}

// SetNillableAllocationVersion sets the "allocation_version" field if the given value is not nil.
func (_c *IPv6EgressPoolCreate) SetNillableAllocationVersion(v *int64) *IPv6EgressPoolCreate {
	if v != nil {
		_c.SetAllocationVersion(*v)
	}
	return _c
}

// AddBindingIDs adds the "bindings" edge to the AccountEgressBinding entity by IDs.
func (_c *IPv6EgressPoolCreate) AddBindingIDs(ids ...int64) *IPv6EgressPoolCreate {
	_c.mutation.AddBindingIDs(ids...)
	return _c
}

// AddBindings adds the "bindings" edges to the AccountEgressBinding entity.
func (_c *IPv6EgressPoolCreate) AddBindings(v ...*AccountEgressBinding) *IPv6EgressPoolCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddBindingIDs(ids...)
}

// Mutation returns the IPv6EgressPoolMutation object of the builder.
func (_c *IPv6EgressPoolCreate) Mutation() *IPv6EgressPoolMutation {
	return _c.mutation
}

// Save creates the IPv6EgressPool in the database.
func (_c *IPv6EgressPoolCreate) Save(ctx context.Context) (*IPv6EgressPool, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *IPv6EgressPoolCreate) SaveX(ctx context.Context) *IPv6EgressPool {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IPv6EgressPoolCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IPv6EgressPoolCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *IPv6EgressPoolCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := ipv6egresspool.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := ipv6egresspool.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := ipv6egresspool.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.IsDefault(); !ok {
		v := ipv6egresspool.DefaultIsDefault
		_c.mutation.SetIsDefault(v)
	}
	if _, ok := _c.mutation.AllocationVersion(); !ok {
		v := ipv6egresspool.DefaultAllocationVersion
		_c.mutation.SetAllocationVersion(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *IPv6EgressPoolCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "IPv6EgressPool.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "IPv6EgressPool.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "IPv6EgressPool.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := ipv6egresspool.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "IPv6EgressPool.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Cidr(); !ok {
		return &ValidationError{Name: "cidr", err: errors.New(`ent: missing required field "IPv6EgressPool.cidr"`)}
	}
	if v, ok := _c.mutation.Cidr(); ok {
		if err := ipv6egresspool.CidrValidator(v); err != nil {
			return &ValidationError{Name: "cidr", err: fmt.Errorf(`ent: validator failed for field "IPv6EgressPool.cidr": %w`, err)}
		}
	}
	if v, ok := _c.mutation.NodeID(); ok {
		if err := ipv6egresspool.NodeIDValidator(v); err != nil {
			return &ValidationError{Name: "node_id", err: fmt.Errorf(`ent: validator failed for field "IPv6EgressPool.node_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "IPv6EgressPool.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := ipv6egresspool.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "IPv6EgressPool.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsDefault(); !ok {
		return &ValidationError{Name: "is_default", err: errors.New(`ent: missing required field "IPv6EgressPool.is_default"`)}
	}
	if _, ok := _c.mutation.AllocationVersion(); !ok {
		return &ValidationError{Name: "allocation_version", err: errors.New(`ent: missing required field "IPv6EgressPool.allocation_version"`)}
	}
	return nil
}

func (_c *IPv6EgressPoolCreate) sqlSave(ctx context.Context) (*IPv6EgressPool, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *IPv6EgressPoolCreate) createSpec() (*IPv6EgressPool, *sqlgraph.CreateSpec) {
	var (
		_node = &IPv6EgressPool{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(ipv6egresspool.Table, sqlgraph.NewFieldSpec(ipv6egresspool.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(ipv6egresspool.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(ipv6egresspool.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(ipv6egresspool.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Cidr(); ok {
		_spec.SetField(ipv6egresspool.FieldCidr, field.TypeString, value)
		_node.Cidr = value
	}
	if value, ok := _c.mutation.NodeID(); ok {
		_spec.SetField(ipv6egresspool.FieldNodeID, field.TypeString, value)
		_node.NodeID = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(ipv6egresspool.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.IsDefault(); ok {
		_spec.SetField(ipv6egresspool.FieldIsDefault, field.TypeBool, value)
		_node.IsDefault = value
	}
	if value, ok := _c.mutation.AllocationVersion(); ok {
		_spec.SetField(ipv6egresspool.FieldAllocationVersion, field.TypeInt64, value)
		_node.AllocationVersion = value
	}
	if nodes := _c.mutation.BindingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ipv6egresspool.BindingsTable,
			Columns: []string{ipv6egresspool.BindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accountegressbinding.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.IPv6EgressPool.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.IPv6EgressPoolUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *IPv6EgressPoolCreate) OnConflict(opts ...sql.ConflictOption) *IPv6EgressPoolUpsertOne {
	_c.conflict = opts
	return &IPv6EgressPoolUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.IPv6EgressPool.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *IPv6EgressPoolCreate) OnConflictColumns(columns ...string) *IPv6EgressPoolUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &IPv6EgressPoolUpsertOne{
		create: _c,
	}
}

type (
	// IPv6EgressPoolUpsertOne is the builder for "upsert"-ing
	//  one IPv6EgressPool node.
	IPv6EgressPoolUpsertOne struct {
		create *IPv6EgressPoolCreate
	}

	// IPv6EgressPoolUpsert is the "OnConflict" setter.
	IPv6EgressPoolUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *IPv6EgressPoolUpsert) SetUpdatedAt(v time.Time) *IPv6EgressPoolUpsert {
	u.Set(ipv6egresspool.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *IPv6EgressPoolUpsert) UpdateUpdatedAt() *IPv6EgressPoolUpsert {
	u.SetExcluded(ipv6egresspool.FieldUpdatedAt)
	return u
}

// SetName sets the "name" field.
func (u *IPv6EgressPoolUpsert) SetName(v string) *IPv6EgressPoolUpsert {
	u.Set(ipv6egresspool.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *IPv6EgressPoolUpsert) UpdateName() *IPv6EgressPoolUpsert {
	u.SetExcluded(ipv6egresspool.FieldName)
	return u
}

// SetCidr sets the "cidr" field.
func (u *IPv6EgressPoolUpsert) SetCidr(v string) *IPv6EgressPoolUpsert {
	u.Set(ipv6egresspool.FieldCidr, v)
	return u
}

// UpdateCidr sets the "cidr" field to the value that was provided on create.
func (u *IPv6EgressPoolUpsert) UpdateCidr() *IPv6EgressPoolUpsert {
	u.SetExcluded(ipv6egresspool.FieldCidr)
	return u
}

// SetNodeID sets the "node_id" field.
func (u *IPv6EgressPoolUpsert) SetNodeID(v string) *IPv6EgressPoolUpsert {
	u.Set(ipv6egresspool.FieldNodeID, v)
	return u
}

// UpdateNodeID sets the "node_id" field to the value that was provided on create.
func (u *IPv6EgressPoolUpsert) UpdateNodeID() *IPv6EgressPoolUpsert {
	u.SetExcluded(ipv6egresspool.FieldNodeID)
	return u
}

// ClearNodeID clears the value of the "node_id" field.
func (u *IPv6EgressPoolUpsert) ClearNodeID() *IPv6EgressPoolUpsert {
	u.SetNull(ipv6egresspool.FieldNodeID)
	return u
}

// SetStatus sets the "status" field.
func (u *IPv6EgressPoolUpsert) SetStatus(v string) *IPv6EgressPoolUpsert {
	u.Set(ipv6egresspool.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *IPv6EgressPoolUpsert) UpdateStatus() *IPv6EgressPoolUpsert {
	u.SetExcluded(ipv6egresspool.FieldStatus)
	return u
}

// SetIsDefault sets the "is_default" field.
func (u *IPv6EgressPoolUpsert) SetIsDefault(v bool) *IPv6EgressPoolUpsert {
	u.Set(ipv6egresspool.FieldIsDefault, v)
	return u
}

// UpdateIsDefault sets the "is_default" field to the value that was provided on create.
func (u *IPv6EgressPoolUpsert) UpdateIsDefault() *IPv6EgressPoolUpsert {
	u.SetExcluded(ipv6egresspool.FieldIsDefault)
	return u
}

// SetAllocationVersion sets the "allocation_version" field.
func (u *IPv6EgressPoolUpsert) SetAllocationVersion(v int64) *IPv6EgressPoolUpsert {
	u.Set(ipv6egresspool.FieldAllocationVersion, v)
	return u
}

// UpdateAllocationVersion sets the "allocation_version" field to the value that was provided on create.
func (u *IPv6EgressPoolUpsert) UpdateAllocationVersion() *IPv6EgressPoolUpsert {
	u.SetExcluded(ipv6egresspool.FieldAllocationVersion)
	return u
}

// AddAllocationVersion adds v to the "allocation_version" field.
func (u *IPv6EgressPoolUpsert) AddAllocationVersion(v int64) *IPv6EgressPoolUpsert {
	u.Add(ipv6egresspool.FieldAllocationVersion, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.IPv6EgressPool.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *IPv6EgressPoolUpsertOne) UpdateNewValues() *IPv6EgressPoolUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(ipv6egresspool.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.IPv6EgressPool.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *IPv6EgressPoolUpsertOne) Ignore() *IPv6EgressPoolUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *IPv6EgressPoolUpsertOne) DoNothing() *IPv6EgressPoolUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the IPv6EgressPoolCreate.OnConflict
// documentation for more info.
func (u *IPv6EgressPoolUpsertOne) Update(set func(*IPv6EgressPoolUpsert)) *IPv6EgressPoolUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&IPv6EgressPoolUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *IPv6EgressPoolUpsertOne) SetUpdatedAt(v time.Time) *IPv6EgressPoolUpsertOne {
	return u.Update(func(s *IPv6EgressPoolUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *IPv6EgressPoolUpsertOne) UpdateUpdatedAt() *IPv6EgressPoolUpsertOne {
	return u.Update(func(s *IPv6EgressPoolUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *IPv6EgressPoolUpsertOne) SetName(v string) *IPv6EgressPoolUpsertOne {
	return u.Update(func(s *IPv6EgressPoolUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *IPv6EgressPoolUpsertOne) UpdateName() *IPv6EgressPoolUpsertOne {
	return u.Update(func(s *IPv6EgressPoolUpsert) {
		s.UpdateName()
	})
}

// SetCidr sets the "cidr" field.
func (u *IPv6EgressPoolUpsertOne) SetCidr(v string) *IPv6EgressPoolUpsertOne {
	return u.Update(func(s *IPv6EgressPoolUpsert) {
		s.SetCidr(v)
	})
}

// UpdateCidr sets the "cidr" field to the value that was provided on create.
func (u *IPv6EgressPoolUpsertOne) UpdateCidr() *IPv6EgressPoolUpsertOne {
	return u.Update(func(s *IPv6EgressPoolUpsert) {
		s.UpdateCidr()
	})
}

// SetNodeID sets the "node_id" field.
func (u *IPv6EgressPoolUpsertOne) SetNodeID(v string) *IPv6EgressPoolUpsertOne {
	return u.Update(func(s *IPv6EgressPoolUpsert) {
		s.SetNodeID(v)
	})
}

// UpdateNodeID sets the "node_id" field to the value that was provided on create.
func (u *IPv6EgressPoolUpsertOne) UpdateNodeID() *IPv6EgressPoolUpsertOne {
	return u.Update(func(s *IPv6EgressPoolUpsert) {
		s.UpdateNodeID()
	})
}

// ClearNodeID clears the value of the "node_id" field.
func (u *IPv6EgressPoolUpsertOne) ClearNodeID() *IPv6EgressPoolUpsertOne {
	return u.Update(func(s *IPv6EgressPoolUpsert) {
		s.ClearNodeID()
	})
}

// SetStatus sets the "status" field.
func (u *IPv6EgressPoolUpsertOne) SetStatus(v string) *IPv6EgressPoolUpsertOne {
	return u.Update(func(s *IPv6EgressPoolUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *IPv6EgressPoolUpsertOne) UpdateStatus() *IPv6EgressPoolUpsertOne {
	return u.Update(func(s *IPv6EgressPoolUpsert) {
		s.UpdateStatus()
	})
}

// SetIsDefault sets the "is_default" field.
func (u *IPv6EgressPoolUpsertOne) SetIsDefault(v bool) *IPv6EgressPoolUpsertOne {
	return u.Update(func(s *IPv6EgressPoolUpsert) {
		s.SetIsDefault(v)
	})
}

// UpdateIsDefault sets the "is_default" field to the value that was provided on create.
func (u *IPv6EgressPoolUpsertOne) UpdateIsDefault() *IPv6EgressPoolUpsertOne {
	return u.Update(func(s *IPv6EgressPoolUpsert) {
		s.UpdateIsDefault()
	})
}

// SetAllocationVersion sets the "allocation_version" field.
func (u *IPv6EgressPoolUpsertOne) SetAllocationVersion(v int64) *IPv6EgressPoolUpsertOne {
	return u.Update(func(s *IPv6EgressPoolUpsert) {
		s.SetAllocationVersion(v)
	})
}

// AddAllocationVersion adds v to the "allocation_version" field.
func (u *IPv6EgressPoolUpsertOne) AddAllocationVersion(v int64) *IPv6EgressPoolUpsertOne {
	return u.Update(func(s *IPv6EgressPoolUpsert) {
		s.AddAllocationVersion(v)
	})
}

// UpdateAllocationVersion sets the "allocation_version" field to the value that was provided on create.
func (u *IPv6EgressPoolUpsertOne) UpdateAllocationVersion() *IPv6EgressPoolUpsertOne {
	return u.Update(func(s *IPv6EgressPoolUpsert) {
		s.UpdateAllocationVersion()
	})
}

// Exec executes the query.
func (u *IPv6EgressPoolUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for IPv6EgressPoolCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *IPv6EgressPoolUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *IPv6EgressPoolUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *IPv6EgressPoolUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// IPv6EgressPoolCreateBulk is the builder for creating many IPv6EgressPool entities in bulk.
type IPv6EgressPoolCreateBulk struct {
	config
	err      error
	builders []*IPv6EgressPoolCreate
	conflict []sql.ConflictOption
}

// Save creates the IPv6EgressPool entities in the database.
func (_c *IPv6EgressPoolCreateBulk) Save(ctx context.Context) ([]*IPv6EgressPool, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*IPv6EgressPool, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*IPv6EgressPoolMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *IPv6EgressPoolCreateBulk) SaveX(ctx context.Context) []*IPv6EgressPool {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IPv6EgressPoolCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IPv6EgressPoolCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.IPv6EgressPool.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.IPv6EgressPoolUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *IPv6EgressPoolCreateBulk) OnConflict(opts ...sql.ConflictOption) *IPv6EgressPoolUpsertBulk {
	_c.conflict = opts
	return &IPv6EgressPoolUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.IPv6EgressPool.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *IPv6EgressPoolCreateBulk) OnConflictColumns(columns ...string) *IPv6EgressPoolUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &IPv6EgressPoolUpsertBulk{
		create: _c,
	}
}

// IPv6EgressPoolUpsertBulk is the builder for "upsert"-ing
// a bulk of IPv6EgressPool nodes.
type IPv6EgressPoolUpsertBulk struct {
	create *IPv6EgressPoolCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.IPv6EgressPool.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *IPv6EgressPoolUpsertBulk) UpdateNewValues() *IPv6EgressPoolUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(ipv6egresspool.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.IPv6EgressPool.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *IPv6EgressPoolUpsertBulk) Ignore() *IPv6EgressPoolUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *IPv6EgressPoolUpsertBulk) DoNothing() *IPv6EgressPoolUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the IPv6EgressPoolCreateBulk.OnConflict
// documentation for more info.
func (u *IPv6EgressPoolUpsertBulk) Update(set func(*IPv6EgressPoolUpsert)) *IPv6EgressPoolUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&IPv6EgressPoolUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *IPv6EgressPoolUpsertBulk) SetUpdatedAt(v time.Time) *IPv6EgressPoolUpsertBulk {
	return u.Update(func(s *IPv6EgressPoolUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *IPv6EgressPoolUpsertBulk) UpdateUpdatedAt() *IPv6EgressPoolUpsertBulk {
	return u.Update(func(s *IPv6EgressPoolUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *IPv6EgressPoolUpsertBulk) SetName(v string) *IPv6EgressPoolUpsertBulk {
	return u.Update(func(s *IPv6EgressPoolUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *IPv6EgressPoolUpsertBulk) UpdateName() *IPv6EgressPoolUpsertBulk {
	return u.Update(func(s *IPv6EgressPoolUpsert) {
		s.UpdateName()
	})
}

// SetCidr sets the "cidr" field.
func (u *IPv6EgressPoolUpsertBulk) SetCidr(v string) *IPv6EgressPoolUpsertBulk {
	return u.Update(func(s *IPv6EgressPoolUpsert) {
		s.SetCidr(v)
	})
}

// UpdateCidr sets the "cidr" field to the value that was provided on create.
func (u *IPv6EgressPoolUpsertBulk) UpdateCidr() *IPv6EgressPoolUpsertBulk {
	return u.Update(func(s *IPv6EgressPoolUpsert) {
		s.UpdateCidr()
	})
}

// SetNodeID sets the "node_id" field.
func (u *IPv6EgressPoolUpsertBulk) SetNodeID(v string) *IPv6EgressPoolUpsertBulk {
	return u.Update(func(s *IPv6EgressPoolUpsert) {
		s.SetNodeID(v)
	})
}

// UpdateNodeID sets the "node_id" field to the value that was provided on create.
func (u *IPv6EgressPoolUpsertBulk) UpdateNodeID() *IPv6EgressPoolUpsertBulk {
	return u.Update(func(s *IPv6EgressPoolUpsert) {
		s.UpdateNodeID()
	})
}

// ClearNodeID clears the value of the "node_id" field.
func (u *IPv6EgressPoolUpsertBulk) ClearNodeID() *IPv6EgressPoolUpsertBulk {
	return u.Update(func(s *IPv6EgressPoolUpsert) {
		s.ClearNodeID()
	})
}

// SetStatus sets the "status" field.
func (u *IPv6EgressPoolUpsertBulk) SetStatus(v string) *IPv6EgressPoolUpsertBulk {
	return u.Update(func(s *IPv6EgressPoolUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *IPv6EgressPoolUpsertBulk) UpdateStatus() *IPv6EgressPoolUpsertBulk {
	return u.Update(func(s *IPv6EgressPoolUpsert) {
		s.UpdateStatus()
	})
}

// SetIsDefault sets the "is_default" field.
func (u *IPv6EgressPoolUpsertBulk) SetIsDefault(v bool) *IPv6EgressPoolUpsertBulk {
	return u.Update(func(s *IPv6EgressPoolUpsert) {
		s.SetIsDefault(v)
	})
}

// UpdateIsDefault sets the "is_default" field to the value that was provided on create.
func (u *IPv6EgressPoolUpsertBulk) UpdateIsDefault() *IPv6EgressPoolUpsertBulk {
	return u.Update(func(s *IPv6EgressPoolUpsert) {
		s.UpdateIsDefault()
	})
}

// SetAllocationVersion sets the "allocation_version" field.
func (u *IPv6EgressPoolUpsertBulk) SetAllocationVersion(v int64) *IPv6EgressPoolUpsertBulk {
	return u.Update(func(s *IPv6EgressPoolUpsert) {
		s.SetAllocationVersion(v)
	})
}

// AddAllocationVersion adds v to the "allocation_version" field.
func (u *IPv6EgressPoolUpsertBulk) AddAllocationVersion(v int64) *IPv6EgressPoolUpsertBulk {
	return u.Update(func(s *IPv6EgressPoolUpsert) {
		s.AddAllocationVersion(v)
	})
}

// UpdateAllocationVersion sets the "allocation_version" field to the value that was provided on create.
func (u *IPv6EgressPoolUpsertBulk) UpdateAllocationVersion() *IPv6EgressPoolUpsertBulk {
	return u.Update(func(s *IPv6EgressPoolUpsert) {
		s.UpdateAllocationVersion()
	})
}

// Exec executes the query.
func (u *IPv6EgressPoolUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the IPv6EgressPoolCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for IPv6EgressPoolCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *IPv6EgressPoolUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
