// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/ipv6egresspool"
)

// IPv6EgressPool is the model entity for the IPv6EgressPool schema.
type IPv6EgressPool struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Cidr holds the value of the "cidr" field.
	Cidr string `json:"cidr,omitempty"`
	// NodeID holds the value of the "node_id" field.
	NodeID *string `json:"node_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// IsDefault holds the value of the "is_default" field.
	IsDefault bool `json:"is_default,omitempty"`
	// AllocationVersion holds the value of the "allocation_version" field.
	AllocationVersion int64 `json:"allocation_version,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the IPv6EgressPoolQuery when eager-loading is set.
	Edges        IPv6EgressPoolEdges `json:"edges"`
	selectValues sql.SelectValues
}

// IPv6EgressPoolEdges holds the relations/edges for other nodes in the graph.
type IPv6EgressPoolEdges struct {
	// Bindings holds the value of the bindings edge.
	Bindings []*AccountEgressBinding `json:"bindings,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// BindingsOrErr returns the Bindings value or an error if the edge
// was not loaded in eager-loading.
func (e IPv6EgressPoolEdges) BindingsOrErr() ([]*AccountEgressBinding, error) {
	if e.loadedTypes[0] {
		return e.Bindings, nil
	}
	return nil, &NotLoadedError{edge: "bindings"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*IPv6EgressPool) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ipv6egresspool.FieldIsDefault:
			values[i] = new(sql.NullBool)
		case ipv6egresspool.FieldID, ipv6egresspool.FieldAllocationVersion:
			values[i] = new(sql.NullInt64)
		case ipv6egresspool.FieldName, ipv6egresspool.FieldCidr, ipv6egresspool.FieldNodeID, ipv6egresspool.FieldStatus:
			values[i] = new(sql.NullString)
		case ipv6egresspool.FieldCreatedAt, ipv6egresspool.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the IPv6EgressPool fields.
func (_m *IPv6EgressPool) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ipv6egresspool.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case ipv6egresspool.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case ipv6egresspool.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case ipv6egresspool.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case ipv6egresspool.FieldCidr:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cidr", values[i])
			} else if value.Valid {
				_m.Cidr = value.String
			}
		case ipv6egresspool.FieldNodeID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field node_id", values[i])
			} else if value.Valid {
				_m.NodeID = new(string)
				*_m.NodeID = value.String
			}
		case ipv6egresspool.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case ipv6egresspool.FieldIsDefault:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_default", values[i])
			} else if value.Valid {
				_m.IsDefault = value.Bool
			}
		case ipv6egresspool.FieldAllocationVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field allocation_version", values[i])
			} else if value.Valid {
				_m.AllocationVersion = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the IPv6EgressPool.
// This includes values selected through modifiers, order, etc.
func (_m *IPv6EgressPool) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryBindings queries the "bindings" edge of the IPv6EgressPool entity.
func (_m *IPv6EgressPool) QueryBindings() *AccountEgressBindingQuery {
	return NewIPv6EgressPoolClient(_m.config).QueryBindings(_m)
}

// Update returns a builder for updating this IPv6EgressPool.
// Note that you need to call IPv6EgressPool.Unwrap() before calling this method if this IPv6EgressPool
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *IPv6EgressPool) Update() *IPv6EgressPoolUpdateOne {
	return NewIPv6EgressPoolClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the IPv6EgressPool entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *IPv6EgressPool) Unwrap() *IPv6EgressPool {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: IPv6EgressPool is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *IPv6EgressPool) String() string {
	var builder strings.Builder
	builder.WriteString("IPv6EgressPool(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("cidr=")
	builder.WriteString(_m.Cidr)
	builder.WriteString(", ")
	if v := _m.NodeID; v != nil {
		builder.WriteString("node_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("is_default=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsDefault))
	builder.WriteString(", ")
	builder.WriteString("allocation_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.AllocationVersion))
	builder.WriteByte(')')
	return builder.String()
}

// IPv6EgressPools is a parsable slice of IPv6EgressPool.
type IPv6EgressPools []*IPv6EgressPool
