// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/accountegressbinding"
	"github.com/Wei-Shaw/sub2api/ent/ipv6egresspool"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// IPv6EgressPoolQuery is the builder for querying IPv6EgressPool entities.
type IPv6EgressPoolQuery struct {
	config
	ctx          *QueryContext
	order        []ipv6egresspool.OrderOption
	inters       []Interceptor
	predicates   []predicate.IPv6EgressPool
	withBindings *AccountEgressBindingQuery
	modifiers    []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the IPv6EgressPoolQuery builder.
func (_q *IPv6EgressPoolQuery) Where(ps ...predicate.IPv6EgressPool) *IPv6EgressPoolQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *IPv6EgressPoolQuery) Limit(limit int) *IPv6EgressPoolQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *IPv6EgressPoolQuery) Offset(offset int) *IPv6EgressPoolQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *IPv6EgressPoolQuery) Unique(unique bool) *IPv6EgressPoolQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *IPv6EgressPoolQuery) Order(o ...ipv6egresspool.OrderOption) *IPv6EgressPoolQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryBindings chains the current query on the "bindings" edge.
func (_q *IPv6EgressPoolQuery) QueryBindings() *AccountEgressBindingQuery {
	query := (&AccountEgressBindingClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(ipv6egresspool.Table, ipv6egresspool.FieldID, selector),
			sqlgraph.To(accountegressbinding.Table, accountegressbinding.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ipv6egresspool.BindingsTable, ipv6egresspool.BindingsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first IPv6EgressPool entity from the query.
// Returns a *NotFoundError when no IPv6EgressPool was found.
func (_q *IPv6EgressPoolQuery) First(ctx context.Context) (*IPv6EgressPool, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{ipv6egresspool.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *IPv6EgressPoolQuery) FirstX(ctx context.Context) *IPv6EgressPool {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first IPv6EgressPool ID from the query.
// Returns a *NotFoundError when no IPv6EgressPool ID was found.
func (_q *IPv6EgressPoolQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{ipv6egresspool.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *IPv6EgressPoolQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single IPv6EgressPool entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one IPv6EgressPool entity is found.
// Returns a *NotFoundError when no IPv6EgressPool entities are found.
func (_q *IPv6EgressPoolQuery) Only(ctx context.Context) (*IPv6EgressPool, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{ipv6egresspool.Label}
	default:
		return nil, &NotSingularError{ipv6egresspool.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *IPv6EgressPoolQuery) OnlyX(ctx context.Context) *IPv6EgressPool {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only IPv6EgressPool ID in the query.
// Returns a *NotSingularError when more than one IPv6EgressPool ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *IPv6EgressPoolQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{ipv6egresspool.Label}
	default:
		err = &NotSingularError{ipv6egresspool.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *IPv6EgressPoolQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of IPv6EgressPools.
func (_q *IPv6EgressPoolQuery) All(ctx context.Context) ([]*IPv6EgressPool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*IPv6EgressPool, *IPv6EgressPoolQuery]()
	return withInterceptors[[]*IPv6EgressPool](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *IPv6EgressPoolQuery) AllX(ctx context.Context) []*IPv6EgressPool {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of IPv6EgressPool IDs.
func (_q *IPv6EgressPoolQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(ipv6egresspool.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *IPv6EgressPoolQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *IPv6EgressPoolQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*IPv6EgressPoolQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *IPv6EgressPoolQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *IPv6EgressPoolQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *IPv6EgressPoolQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the IPv6EgressPoolQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *IPv6EgressPoolQuery) Clone() *IPv6EgressPoolQuery {
	if _q == nil {
		return nil
	}
	return &IPv6EgressPoolQuery{
		config:       _q.config,
		ctx:          _q.ctx.Clone(),
		order:        append([]ipv6egresspool.OrderOption{}, _q.order...),
		inters:       append([]Interceptor{}, _q.inters...),
		predicates:   append([]predicate.IPv6EgressPool{}, _q.predicates...),
		withBindings: _q.withBindings.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithBindings tells the query-builder to eager-load the nodes that are connected to
// the "bindings" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *IPv6EgressPoolQuery) WithBindings(opts ...func(*AccountEgressBindingQuery)) *IPv6EgressPoolQuery {
	query := (&AccountEgressBindingClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withBindings = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.IPv6EgressPool.Query().
//		GroupBy(ipv6egresspool.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *IPv6EgressPoolQuery) GroupBy(field string, fields ...string) *IPv6EgressPoolGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &IPv6EgressPoolGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = ipv6egresspool.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.IPv6EgressPool.Query().
//		Select(ipv6egresspool.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *IPv6EgressPoolQuery) Select(fields ...string) *IPv6EgressPoolSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &IPv6EgressPoolSelect{IPv6EgressPoolQuery: _q}
	sbuild.label = ipv6egresspool.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a IPv6EgressPoolSelect configured with the given aggregations.
func (_q *IPv6EgressPoolQuery) Aggregate(fns ...AggregateFunc) *IPv6EgressPoolSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *IPv6EgressPoolQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !ipv6egresspool.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *IPv6EgressPoolQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*IPv6EgressPool, error) {
	var (
		nodes       = []*IPv6EgressPool{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withBindings != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*IPv6EgressPool).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &IPv6EgressPool{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withBindings; query != nil {
		if err := _q.loadBindings(ctx, query, nodes,
			func(n *IPv6EgressPool) { n.Edges.Bindings = []*AccountEgressBinding{} },
			func(n *IPv6EgressPool, e *AccountEgressBinding) { n.Edges.Bindings = append(n.Edges.Bindings, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *IPv6EgressPoolQuery) loadBindings(ctx context.Context, query *AccountEgressBindingQuery, nodes []*IPv6EgressPool, init func(*IPv6EgressPool), assign func(*IPv6EgressPool, *AccountEgressBinding)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*IPv6EgressPool)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(accountegressbinding.FieldPoolID)
	}
	query.Where(predicate.AccountEgressBinding(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(ipv6egresspool.BindingsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.PoolID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "pool_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *IPv6EgressPoolQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *IPv6EgressPoolQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(ipv6egresspool.Table, ipv6egresspool.Columns, sqlgraph.NewFieldSpec(ipv6egresspool.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ipv6egresspool.FieldID)
		for i := range fields {
			if fields[i] != ipv6egresspool.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *IPv6EgressPoolQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(ipv6egresspool.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = ipv6egresspool.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *IPv6EgressPoolQuery) ForUpdate(opts ...sql.LockOption) *IPv6EgressPoolQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *IPv6EgressPoolQuery) ForShare(opts ...sql.LockOption) *IPv6EgressPoolQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// IPv6EgressPoolGroupBy is the group-by builder for IPv6EgressPool entities.
type IPv6EgressPoolGroupBy struct {
	selector
	build *IPv6EgressPoolQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *IPv6EgressPoolGroupBy) Aggregate(fns ...AggregateFunc) *IPv6EgressPoolGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *IPv6EgressPoolGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*IPv6EgressPoolQuery, *IPv6EgressPoolGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *IPv6EgressPoolGroupBy) sqlScan(ctx context.Context, root *IPv6EgressPoolQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// IPv6EgressPoolSelect is the builder for selecting fields of IPv6EgressPool entities.
type IPv6EgressPoolSelect struct {
	*IPv6EgressPoolQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *IPv6EgressPoolSelect) Aggregate(fns ...AggregateFunc) *IPv6EgressPoolSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *IPv6EgressPoolSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*IPv6EgressPoolQuery, *IPv6EgressPoolSelect](ctx, _s.IPv6EgressPoolQuery, _s, _s.inters, v)
}

func (_s *IPv6EgressPoolSelect) sqlScan(ctx context.Context, root *IPv6EgressPoolQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
