// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/accountegressbinding"
	"github.com/Wei-Shaw/sub2api/ent/ipv6egresspool"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// IPv6EgressPoolUpdate is the builder for updating IPv6EgressPool entities.
type IPv6EgressPoolUpdate struct {
	config
	hooks    []Hook
	mutation *IPv6EgressPoolMutation
}

// Where appends a list predicates to the IPv6EgressPoolUpdate builder.
func (_u *IPv6EgressPoolUpdate) Where(ps ...predicate.IPv6EgressPool) *IPv6EgressPoolUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *IPv6EgressPoolUpdate) SetUpdatedAt(v time.Time) *IPv6EgressPoolUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *IPv6EgressPoolUpdate) SetName(v string) *IPv6EgressPoolUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *IPv6EgressPoolUpdate) SetNillableName(v *string) *IPv6EgressPoolUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCidr sets the "cidr" field.
func (_u *IPv6EgressPoolUpdate) SetCidr(v string) *IPv6EgressPoolUpdate {
	_u.mutation.SetCidr(v)
	return _u
}

// SetNillableCidr sets the "cidr" field if the given value is not nil.
func (_u *IPv6EgressPoolUpdate) SetNillableCidr(v *string) *IPv6EgressPoolUpdate {
	if v != nil {
		_u.SetCidr(*v)
	}
	return _u
}

// SetNodeID sets the "node_id" field.
func (_u *IPv6EgressPoolUpdate) SetNodeID(v string) *IPv6EgressPoolUpdate {
	_u.mutation.SetNodeID(v)
	return _u
}

// SetNillableNodeID sets the "node_id" field if the given value is not nil.
func (_u *IPv6EgressPoolUpdate) SetNillableNodeID(v *string) *IPv6EgressPoolUpdate {
	if v != nil {
		_u.SetNodeID(*v)
	}
	return _u
}

// ClearNodeID clears the value of the "node_id" field.
func (_u *IPv6EgressPoolUpdate) ClearNodeID() *IPv6EgressPoolUpdate {
	_u.mutation.ClearNodeID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *IPv6EgressPoolUpdate) SetStatus(v string) *IPv6EgressPoolUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *IPv6EgressPoolUpdate) SetNillableStatus(v *string) *IPv6EgressPoolUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetIsDefault sets the "is_default" field.
func (_u *IPv6EgressPoolUpdate) SetIsDefault(v bool) *IPv6EgressPoolUpdate {
	_u.mutation.SetIsDefault(v)
	return _u
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_u *IPv6EgressPoolUpdate) SetNillableIsDefault(v *bool) *IPv6EgressPoolUpdate {
	if v != nil {
		_u.SetIsDefault(*v)
	}
	return _u
}

// SetAllocationVersion sets the "allocation_version" field.
func (_u *IPv6EgressPoolUpdate) SetAllocationVersion(v int64) *IPv6EgressPoolUpdate {
	_u.mutation.ResetAllocationVersion()
	_u.mutation.SetAllocationVersion(v)
	return _u
}

// SetNillableAllocationVersion sets the "allocation_version" field if the given value is not nil.
func (_u *IPv6EgressPoolUpdate) SetNillableAllocationVersion(v *int64) *IPv6EgressPoolUpdate {
	if v != nil {
		_u.SetAllocationVersion(*v)
	}
	return _u
}

// AddAllocationVersion adds value to the "allocation_version" field.
func (_u *IPv6EgressPoolUpdate) AddAllocationVersion(v int64) *IPv6EgressPoolUpdate {
	_u.mutation.AddAllocationVersion(v)
	return _u
}

// AddBindingIDs adds the "bindings" edge to the AccountEgressBinding entity by IDs.
func (_u *IPv6EgressPoolUpdate) AddBindingIDs(ids ...int64) *IPv6EgressPoolUpdate {
	_u.mutation.AddBindingIDs(ids...)
	return _u
}

// AddBindings adds the "bindings" edges to the AccountEgressBinding entity.
func (_u *IPv6EgressPoolUpdate) AddBindings(v ...*AccountEgressBinding) *IPv6EgressPoolUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBindingIDs(ids...)
}

// Mutation returns the IPv6EgressPoolMutation object of the builder.
func (_u *IPv6EgressPoolUpdate) Mutation() *IPv6EgressPoolMutation {
	return _u.mutation
}

// ClearBindings clears all "bindings" edges to the AccountEgressBinding entity.
func (_u *IPv6EgressPoolUpdate) ClearBindings() *IPv6EgressPoolUpdate {
	_u.mutation.ClearBindings()
	return _u
}

// RemoveBindingIDs removes the "bindings" edge to AccountEgressBinding entities by IDs.
func (_u *IPv6EgressPoolUpdate) RemoveBindingIDs(ids ...int64) *IPv6EgressPoolUpdate {
	_u.mutation.RemoveBindingIDs(ids...)
	return _u
}

// RemoveBindings removes "bindings" edges to AccountEgressBinding entities.
func (_u *IPv6EgressPoolUpdate) RemoveBindings(v ...*AccountEgressBinding) *IPv6EgressPoolUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBindingIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *IPv6EgressPoolUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IPv6EgressPoolUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *IPv6EgressPoolUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IPv6EgressPoolUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *IPv6EgressPoolUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := ipv6egresspool.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *IPv6EgressPoolUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := ipv6egresspool.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "IPv6EgressPool.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Cidr(); ok {
		if err := ipv6egresspool.CidrValidator(v); err != nil {
			return &ValidationError{Name: "cidr", err: fmt.Errorf(`ent: validator failed for field "IPv6EgressPool.cidr": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NodeID(); ok {
		if err := ipv6egresspool.NodeIDValidator(v); err != nil {
			return &ValidationError{Name: "node_id", err: fmt.Errorf(`ent: validator failed for field "IPv6EgressPool.node_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := ipv6egresspool.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "IPv6EgressPool.status": %w`, err)}
		}
	}
	return nil
}

func (_u *IPv6EgressPoolUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ipv6egresspool.Table, ipv6egresspool.Columns, sqlgraph.NewFieldSpec(ipv6egresspool.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(ipv6egresspool.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(ipv6egresspool.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Cidr(); ok {
		_spec.SetField(ipv6egresspool.FieldCidr, field.TypeString, value)
	}
	if value, ok := _u.mutation.NodeID(); ok {
		_spec.SetField(ipv6egresspool.FieldNodeID, field.TypeString, value)
	}
	if _u.mutation.NodeIDCleared() {
		_spec.ClearField(ipv6egresspool.FieldNodeID, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(ipv6egresspool.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsDefault(); ok {
		_spec.SetField(ipv6egresspool.FieldIsDefault, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AllocationVersion(); ok {
		_spec.SetField(ipv6egresspool.FieldAllocationVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAllocationVersion(); ok {
		_spec.AddField(ipv6egresspool.FieldAllocationVersion, field.TypeInt64, value)
	}
	if _u.mutation.BindingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ipv6egresspool.BindingsTable,
			Columns: []string{ipv6egresspool.BindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accountegressbinding.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBindingsIDs(); len(nodes) > 0 && !_u.mutation.BindingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ipv6egresspool.BindingsTable,
			Columns: []string{ipv6egresspool.BindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accountegressbinding.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BindingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ipv6egresspool.BindingsTable,
			Columns: []string{ipv6egresspool.BindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accountegressbinding.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ipv6egresspool.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// IPv6EgressPoolUpdateOne is the builder for updating a single IPv6EgressPool entity.
type IPv6EgressPoolUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *IPv6EgressPoolMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *IPv6EgressPoolUpdateOne) SetUpdatedAt(v time.Time) *IPv6EgressPoolUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *IPv6EgressPoolUpdateOne) SetName(v string) *IPv6EgressPoolUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *IPv6EgressPoolUpdateOne) SetNillableName(v *string) *IPv6EgressPoolUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCidr sets the "cidr" field.
func (_u *IPv6EgressPoolUpdateOne) SetCidr(v string) *IPv6EgressPoolUpdateOne {
	_u.mutation.SetCidr(v)
	return _u
}

// SetNillableCidr sets the "cidr" field if the given value is not nil.
func (_u *IPv6EgressPoolUpdateOne) SetNillableCidr(v *string) *IPv6EgressPoolUpdateOne {
	if v != nil {
		_u.SetCidr(*v)
	}
	return _u
}

// SetNodeID sets the "node_id" field.
func (_u *IPv6EgressPoolUpdateOne) SetNodeID(v string) *IPv6EgressPoolUpdateOne {
	_u.mutation.SetNodeID(v)
	return _u
}

// SetNillableNodeID sets the "node_id" field if the given value is not nil.
func (_u *IPv6EgressPoolUpdateOne) SetNillableNodeID(v *string) *IPv6EgressPoolUpdateOne {
	if v != nil {
		_u.SetNodeID(*v)
	}
	return _u
}

// ClearNodeID clears the value of the "node_id" field.
func (_u *IPv6EgressPoolUpdateOne) ClearNodeID() *IPv6EgressPoolUpdateOne {
	_u.mutation.ClearNodeID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *IPv6EgressPoolUpdateOne) SetStatus(v string) *IPv6EgressPoolUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *IPv6EgressPoolUpdateOne) SetNillableStatus(v *string) *IPv6EgressPoolUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetIsDefault sets the "is_default" field.
func (_u *IPv6EgressPoolUpdateOne) SetIsDefault(v bool) *IPv6EgressPoolUpdateOne {
	_u.mutation.SetIsDefault(v)
	return _u
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_u *IPv6EgressPoolUpdateOne) SetNillableIsDefault(v *bool) *IPv6EgressPoolUpdateOne {
	if v != nil {
		_u.SetIsDefault(*v)
	}
	return _u
}

// SetAllocationVersion sets the "allocation_version" field.
func (_u *IPv6EgressPoolUpdateOne) SetAllocationVersion(v int64) *IPv6EgressPoolUpdateOne {
	_u.mutation.ResetAllocationVersion()
	_u.mutation.SetAllocationVersion(v)
	return _u
}

// SetNillableAllocationVersion sets the "allocation_version" field if the given value is not nil.
func (_u *IPv6EgressPoolUpdateOne) SetNillableAllocationVersion(v *int64) *IPv6EgressPoolUpdateOne {
	if v != nil {
		_u.SetAllocationVersion(*v)
	}
	return _u
}

// AddAllocationVersion adds value to the "allocation_version" field.
func (_u *IPv6EgressPoolUpdateOne) AddAllocationVersion(v int64) *IPv6EgressPoolUpdateOne {
	_u.mutation.AddAllocationVersion(v)
	return _u
}

// AddBindingIDs adds the "bindings" edge to the AccountEgressBinding entity by IDs.
func (_u *IPv6EgressPoolUpdateOne) AddBindingIDs(ids ...int64) *IPv6EgressPoolUpdateOne {
	_u.mutation.AddBindingIDs(ids...)
	return _u
}

// AddBindings adds the "bindings" edges to the AccountEgressBinding entity.
func (_u *IPv6EgressPoolUpdateOne) AddBindings(v ...*AccountEgressBinding) *IPv6EgressPoolUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBindingIDs(ids...)
}

// Mutation returns the IPv6EgressPoolMutation object of the builder.
func (_u *IPv6EgressPoolUpdateOne) Mutation() *IPv6EgressPoolMutation {
	return _u.mutation
}

// ClearBindings clears all "bindings" edges to the AccountEgressBinding entity.
func (_u *IPv6EgressPoolUpdateOne) ClearBindings() *IPv6EgressPoolUpdateOne {
	_u.mutation.ClearBindings()
	return _u
}

// RemoveBindingIDs removes the "bindings" edge to AccountEgressBinding entities by IDs.
func (_u *IPv6EgressPoolUpdateOne) RemoveBindingIDs(ids ...int64) *IPv6EgressPoolUpdateOne {
	_u.mutation.RemoveBindingIDs(ids...)
	return _u
}

// RemoveBindings removes "bindings" edges to AccountEgressBinding entities.
func (_u *IPv6EgressPoolUpdateOne) RemoveBindings(v ...*AccountEgressBinding) *IPv6EgressPoolUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBindingIDs(ids...)
}

// Where appends a list predicates to the IPv6EgressPoolUpdate builder.
func (_u *IPv6EgressPoolUpdateOne) Where(ps ...predicate.IPv6EgressPool) *IPv6EgressPoolUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *IPv6EgressPoolUpdateOne) Select(field string, fields ...string) *IPv6EgressPoolUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated IPv6EgressPool entity.
func (_u *IPv6EgressPoolUpdateOne) Save(ctx context.Context) (*IPv6EgressPool, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IPv6EgressPoolUpdateOne) SaveX(ctx context.Context) *IPv6EgressPool {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *IPv6EgressPoolUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IPv6EgressPoolUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *IPv6EgressPoolUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := ipv6egresspool.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *IPv6EgressPoolUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := ipv6egresspool.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "IPv6EgressPool.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Cidr(); ok {
		if err := ipv6egresspool.CidrValidator(v); err != nil {
			return &ValidationError{Name: "cidr", err: fmt.Errorf(`ent: validator failed for field "IPv6EgressPool.cidr": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NodeID(); ok {
		if err := ipv6egresspool.NodeIDValidator(v); err != nil {
			return &ValidationError{Name: "node_id", err: fmt.Errorf(`ent: validator failed for field "IPv6EgressPool.node_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := ipv6egresspool.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "IPv6EgressPool.status": %w`, err)}
		}
	}
	return nil
}

func (_u *IPv6EgressPoolUpdateOne) sqlSave(ctx context.Context) (_node *IPv6EgressPool, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ipv6egresspool.Table, ipv6egresspool.Columns, sqlgraph.NewFieldSpec(ipv6egresspool.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "IPv6EgressPool.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ipv6egresspool.FieldID)
		for _, f := range fields {
			if !ipv6egresspool.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ipv6egresspool.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(ipv6egresspool.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(ipv6egresspool.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Cidr(); ok {
		_spec.SetField(ipv6egresspool.FieldCidr, field.TypeString, value)
	}
	if value, ok := _u.mutation.NodeID(); ok {
		_spec.SetField(ipv6egresspool.FieldNodeID, field.TypeString, value)
	}
	if _u.mutation.NodeIDCleared() {
		_spec.ClearField(ipv6egresspool.FieldNodeID, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(ipv6egresspool.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsDefault(); ok {
		_spec.SetField(ipv6egresspool.FieldIsDefault, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AllocationVersion(); ok {
		_spec.SetField(ipv6egresspool.FieldAllocationVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAllocationVersion(); ok {
		_spec.AddField(ipv6egresspool.FieldAllocationVersion, field.TypeInt64, value)
	}
	if _u.mutation.BindingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ipv6egresspool.BindingsTable,
			Columns: []string{ipv6egresspool.BindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accountegressbinding.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBindingsIDs(); len(nodes) > 0 && !_u.mutation.BindingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ipv6egresspool.BindingsTable,
			Columns: []string{ipv6egresspool.BindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accountegressbinding.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BindingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ipv6egresspool.BindingsTable,
			Columns: []string{ipv6egresspool.BindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accountegressbinding.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &IPv6EgressPool{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ipv6egresspool.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
