// Code generated by ent, DO NOT EDIT.

package chatmessageasset

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// MessageID applies equality check predicate on the "message_id" field. It's identical to MessageIDEQ.
func MessageID(v int64) predicate.ChatMessageAsset {
	return predicate.ChatMessageAsset(sql.FieldEQ(FieldMessageID, v))
}

// AssetID applies equality check predicate on the "asset_id" field. It's identical to AssetIDEQ.
func AssetID(v int64) predicate.ChatMessageAsset {
	return predicate.ChatMessageAsset(sql.FieldEQ(FieldAssetID, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v int) predicate.ChatMessageAsset {
	return predicate.ChatMessageAsset(sql.FieldEQ(FieldSortOrder, v))
}

// MessageIDEQ applies the EQ predicate on the "message_id" field.
func MessageIDEQ(v int64) predicate.ChatMessageAsset {
	return predicate.ChatMessageAsset(sql.FieldEQ(FieldMessageID, v))
}

// MessageIDNEQ applies the NEQ predicate on the "message_id" field.
func MessageIDNEQ(v int64) predicate.ChatMessageAsset {
	return predicate.ChatMessageAsset(sql.FieldNEQ(FieldMessageID, v))
}

// MessageIDIn applies the In predicate on the "message_id" field.
func MessageIDIn(vs ...int64) predicate.ChatMessageAsset {
	return predicate.ChatMessageAsset(sql.FieldIn(FieldMessageID, vs...))
}

// MessageIDNotIn applies the NotIn predicate on the "message_id" field.
func MessageIDNotIn(vs ...int64) predicate.ChatMessageAsset {
	return predicate.ChatMessageAsset(sql.FieldNotIn(FieldMessageID, vs...))
}

// AssetIDEQ applies the EQ predicate on the "asset_id" field.
func AssetIDEQ(v int64) predicate.ChatMessageAsset {
	return predicate.ChatMessageAsset(sql.FieldEQ(FieldAssetID, v))
}

// AssetIDNEQ applies the NEQ predicate on the "asset_id" field.
func AssetIDNEQ(v int64) predicate.ChatMessageAsset {
	return predicate.ChatMessageAsset(sql.FieldNEQ(FieldAssetID, v))
}

// AssetIDIn applies the In predicate on the "asset_id" field.
func AssetIDIn(vs ...int64) predicate.ChatMessageAsset {
	return predicate.ChatMessageAsset(sql.FieldIn(FieldAssetID, vs...))
}

// AssetIDNotIn applies the NotIn predicate on the "asset_id" field.
func AssetIDNotIn(vs ...int64) predicate.ChatMessageAsset {
	return predicate.ChatMessageAsset(sql.FieldNotIn(FieldAssetID, vs...))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v int) predicate.ChatMessageAsset {
	return predicate.ChatMessageAsset(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v int) predicate.ChatMessageAsset {
	return predicate.ChatMessageAsset(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...int) predicate.ChatMessageAsset {
	return predicate.ChatMessageAsset(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...int) predicate.ChatMessageAsset {
	return predicate.ChatMessageAsset(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v int) predicate.ChatMessageAsset {
	return predicate.ChatMessageAsset(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v int) predicate.ChatMessageAsset {
	return predicate.ChatMessageAsset(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v int) predicate.ChatMessageAsset {
	return predicate.ChatMessageAsset(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v int) predicate.ChatMessageAsset {
	return predicate.ChatMessageAsset(sql.FieldLTE(FieldSortOrder, v))
}

// HasMessage applies the HasEdge predicate on the "message" edge.
func HasMessage() predicate.ChatMessageAsset {
	return predicate.ChatMessageAsset(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, MessageColumn),
			sqlgraph.Edge(sqlgraph.M2O, false, MessageTable, MessageColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMessageWith applies the HasEdge predicate on the "message" edge with a given conditions (other predicates).
func HasMessageWith(preds ...predicate.ChatMessage) predicate.ChatMessageAsset {
	return predicate.ChatMessageAsset(func(s *sql.Selector) {
		step := newMessageStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAsset applies the HasEdge predicate on the "asset" edge.
func HasAsset() predicate.ChatMessageAsset {
	return predicate.ChatMessageAsset(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, AssetColumn),
			sqlgraph.Edge(sqlgraph.M2O, false, AssetTable, AssetColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAssetWith applies the HasEdge predicate on the "asset" edge with a given conditions (other predicates).
func HasAssetWith(preds ...predicate.ChatAsset) predicate.ChatMessageAsset {
	return predicate.ChatMessageAsset(func(s *sql.Selector) {
		step := newAssetStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ChatMessageAsset) predicate.ChatMessageAsset {
	return predicate.ChatMessageAsset(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ChatMessageAsset) predicate.ChatMessageAsset {
	return predicate.ChatMessageAsset(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ChatMessageAsset) predicate.ChatMessageAsset {
	return predicate.ChatMessageAsset(sql.NotPredicates(p))
}
