<template>
  <main class="min-h-screen bg-gray-50 px-4 py-8 text-gray-900 dark:bg-dark-950 dark:text-gray-50 sm:px-8">
    <div class="mx-auto max-w-6xl space-y-6">
      <header class="flex flex-wrap items-end justify-between gap-4 border-b border-gray-200 pb-5 dark:border-dark-700"><div><p class="text-xs font-semibold uppercase tracking-[0.18em] text-gray-400">{{ t('common.accountQuality.eyebrow') }}</p><h1 class="mt-2 text-3xl font-semibold tracking-tight">{{ t('common.accountQuality.title') }}<span class="text-emerald-500">.</span></h1><p class="mt-2 text-sm text-gray-500 dark:text-gray-400">{{ snapshot?.model || t('common.accountQuality.subtitle') }} · thinking {{ snapshot?.effort || 'medium' }} · {{ t('common.accountQuality.recent') }}</p></div><button class="rounded-md border border-gray-300 bg-white px-3 py-2 text-sm text-gray-600 shadow-sm dark:border-dark-600 dark:bg-dark-800 dark:text-gray-200" :disabled="loading" @click="load">{{ loading ? t('common.accountQuality.refreshing') : t('common.accountQuality.refresh') }}</button></header>
      <p v-if="error" class="rounded-md border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800">{{ t('common.accountQuality.qualityDisabled') }}</p>
      <section v-if="snapshot" class="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><article v-for="card in cards" :key="card.label" class="rounded-xl border border-gray-200 bg-white p-5 shadow-sm dark:border-dark-700 dark:bg-dark-800"><p class="text-xs text-gray-500 dark:text-gray-400">{{ card.label }}</p><strong class="mt-3 block text-3xl tabular-nums" :class="card.class">{{ card.value }}</strong><p class="mt-2 text-xs text-gray-400">{{ card.note }}</p></article></section>
      <section class="rounded-xl border border-gray-200 bg-white p-5 shadow-sm dark:border-dark-700 dark:bg-dark-800"><div class="flex items-center justify-between gap-3"><div><h2 class="font-semibold">{{ t('common.accountQuality.timeline') }}</h2><p class="mt-1 text-xs text-gray-400">{{ t('common.accountQuality.timelineNote') }}</p></div><span class="text-xs text-gray-400">{{ snapshot?.model_version || '8.4.14' }}</span></div><div class="mt-5 grid min-h-10 grid-cols-[repeat(auto-fill,minmax(10px,1fr))] gap-1"><button v-for="(point, index) in snapshot?.points || []" :key="point.id || index" class="h-9 rounded-sm transition hover:-translate-y-1" :class="pointClass(point)" :title="pointTitle(point)" /><span v-if="!snapshot?.points?.length" class="col-span-full py-8 text-center text-sm text-gray-400">{{ t('common.accountQuality.empty') }}</span></div><div class="mt-4 flex flex-wrap gap-4 text-xs text-gray-500"><span><i class="mr-1 inline-block h-2 w-2 rounded-sm bg-emerald-500" />{{ t('common.accountQuality.normal') }}</span><span><i class="mr-1 inline-block h-2 w-2 rounded-sm bg-rose-500" />{{ t('common.accountQuality.abnormal') }}</span><span><i class="mr-1 inline-block h-2 w-2 rounded-sm bg-amber-400" />{{ t('common.accountQuality.waiting') }}</span><span><i class="mr-1 inline-block h-2 w-2 rounded-sm bg-gray-300" />{{ t('common.accountQuality.failed') }}</span></div></section>
      <section v-if="readyPoints.length" class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><article v-for="point in readyPoints.slice(0, 12)" :key="point.id" class="overflow-hidden rounded-xl border border-gray-200 bg-white shadow-sm dark:border-dark-700 dark:bg-dark-800"><img :src="`/api/v1/account-quality-share/image/${point.id}?format=webp`" :alt="t('common.accountQuality.abnormal')" class="aspect-square w-full object-contain bg-gray-100 dark:bg-dark-900" loading="lazy" /><div class="flex items-center justify-between p-3 text-xs"><span class="font-medium" :class="point.label === 'normal' ? 'text-emerald-600' : 'text-rose-600'">{{ point.label === 'normal' ? t('common.accountQuality.normal') : t('common.accountQuality.abnormal') }}</span><span class="text-gray-400">{{ formatTime(point.started_at) }} · {{ formatLatency(point.latency_ms) }}</span></div></article></section>
      <footer class="text-xs text-gray-400">{{ t('common.accountQuality.footer', { minutes: snapshot?.interval_minutes || '-' }) }}</footer>
    </div>
  </main>
</template>
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { getPublicSnapshot, type AccountQualityPublicPoint, type AccountQualityPublicSnapshot } from '../../data/datasources/accountQualityPublicDatasource'
const { t } = useI18n(); const snapshot = ref<AccountQualityPublicSnapshot | null>(null); const loading = ref(false); const error = ref(''); let timer: ReturnType<typeof setInterval> | null = null
const readyPoints = computed(() => (snapshot.value?.points || []).filter(point => ['ready', 'wrong'].includes(point.status) && point.id))
const cards = computed(() => snapshot.value ? [
  { label: t('common.accountQuality.total'), value: snapshot.value.total, note: t('common.accountQuality.totalNote'), class: 'text-gray-900 dark:text-white' },
  { label: t('common.accountQuality.passed'), value: snapshot.value.passed, note: t('common.accountQuality.passedNote'), class: 'text-emerald-600' },
  { label: t('common.accountQuality.degraded'), value: snapshot.value.degraded, note: t('common.accountQuality.degradedNote'), class: 'text-rose-600' },
  { label: t('common.accountQuality.uncertain'), value: snapshot.value.uncertain, note: t('common.accountQuality.uncertainNote'), class: 'text-amber-500' },
  { label: t('common.accountQuality.errors'), value: snapshot.value.error, note: t('common.accountQuality.errorsNote'), class: 'text-gray-500' },
] : [])
async function load(): Promise<void> { loading.value = true; try { snapshot.value = await getPublicSnapshot(); error.value = '' } catch { error.value = 'error' } finally { loading.value = false } }
function pointClass(point: AccountQualityPublicPoint): string { if (point.status === 'ready' && point.label === 'normal') return 'bg-emerald-500'; if (point.status === 'ready' && point.label === 'unnormal') return 'bg-rose-500'; if (point.status === 'uncertain') return 'bg-amber-400'; return 'bg-gray-300' }
function pointTitle(point: AccountQualityPublicPoint): string { return `${formatTime(point.started_at)} · ${point.label || point.status}${point.confidence ? ` · ${(point.confidence * 100).toFixed(1)}%` : ''}` }
function formatTime(value: string): string { return new Intl.DateTimeFormat('zh-CN', { timeZone: 'Asia/Shanghai', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit' }).format(new Date(value)).replace(/\//g, '-') }
function formatLatency(value?: number): string { return value == null ? '-' : `${(value / 1000).toFixed(1)}s` }
onMounted(() => { void load(); timer = setInterval(() => void load(), 20_000) }); onBeforeUnmount(() => { if (timer) clearInterval(timer) })
</script>
