// Code generated by ent, DO NOT EDIT.

package ipv6egresspool

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldEQ(FieldUpdatedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldEQ(FieldName, v))
}

// Cidr applies equality check predicate on the "cidr" field. It's identical to CidrEQ.
func Cidr(v string) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldEQ(FieldCidr, v))
}

// NodeID applies equality check predicate on the "node_id" field. It's identical to NodeIDEQ.
func NodeID(v string) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldEQ(FieldNodeID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldEQ(FieldStatus, v))
}

// IsDefault applies equality check predicate on the "is_default" field. It's identical to IsDefaultEQ.
func IsDefault(v bool) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldEQ(FieldIsDefault, v))
}

// AllocationVersion applies equality check predicate on the "allocation_version" field. It's identical to AllocationVersionEQ.
func AllocationVersion(v int64) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldEQ(FieldAllocationVersion, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldLTE(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldContainsFold(FieldName, v))
}

// CidrEQ applies the EQ predicate on the "cidr" field.
func CidrEQ(v string) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldEQ(FieldCidr, v))
}

// CidrNEQ applies the NEQ predicate on the "cidr" field.
func CidrNEQ(v string) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldNEQ(FieldCidr, v))
}

// CidrIn applies the In predicate on the "cidr" field.
func CidrIn(vs ...string) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldIn(FieldCidr, vs...))
}

// CidrNotIn applies the NotIn predicate on the "cidr" field.
func CidrNotIn(vs ...string) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldNotIn(FieldCidr, vs...))
}

// CidrGT applies the GT predicate on the "cidr" field.
func CidrGT(v string) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldGT(FieldCidr, v))
}

// CidrGTE applies the GTE predicate on the "cidr" field.
func CidrGTE(v string) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldGTE(FieldCidr, v))
}

// CidrLT applies the LT predicate on the "cidr" field.
func CidrLT(v string) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldLT(FieldCidr, v))
}

// CidrLTE applies the LTE predicate on the "cidr" field.
func CidrLTE(v string) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldLTE(FieldCidr, v))
}

// CidrContains applies the Contains predicate on the "cidr" field.
func CidrContains(v string) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldContains(FieldCidr, v))
}

// CidrHasPrefix applies the HasPrefix predicate on the "cidr" field.
func CidrHasPrefix(v string) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldHasPrefix(FieldCidr, v))
}

// CidrHasSuffix applies the HasSuffix predicate on the "cidr" field.
func CidrHasSuffix(v string) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldHasSuffix(FieldCidr, v))
}

// CidrEqualFold applies the EqualFold predicate on the "cidr" field.
func CidrEqualFold(v string) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldEqualFold(FieldCidr, v))
}

// CidrContainsFold applies the ContainsFold predicate on the "cidr" field.
func CidrContainsFold(v string) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldContainsFold(FieldCidr, v))
}

// NodeIDEQ applies the EQ predicate on the "node_id" field.
func NodeIDEQ(v string) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldEQ(FieldNodeID, v))
}

// NodeIDNEQ applies the NEQ predicate on the "node_id" field.
func NodeIDNEQ(v string) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldNEQ(FieldNodeID, v))
}

// NodeIDIn applies the In predicate on the "node_id" field.
func NodeIDIn(vs ...string) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldIn(FieldNodeID, vs...))
}

// NodeIDNotIn applies the NotIn predicate on the "node_id" field.
func NodeIDNotIn(vs ...string) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldNotIn(FieldNodeID, vs...))
}

// NodeIDGT applies the GT predicate on the "node_id" field.
func NodeIDGT(v string) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldGT(FieldNodeID, v))
}

// NodeIDGTE applies the GTE predicate on the "node_id" field.
func NodeIDGTE(v string) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldGTE(FieldNodeID, v))
}

// NodeIDLT applies the LT predicate on the "node_id" field.
func NodeIDLT(v string) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldLT(FieldNodeID, v))
}

// NodeIDLTE applies the LTE predicate on the "node_id" field.
func NodeIDLTE(v string) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldLTE(FieldNodeID, v))
}

// NodeIDContains applies the Contains predicate on the "node_id" field.
func NodeIDContains(v string) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldContains(FieldNodeID, v))
}

// NodeIDHasPrefix applies the HasPrefix predicate on the "node_id" field.
func NodeIDHasPrefix(v string) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldHasPrefix(FieldNodeID, v))
}

// NodeIDHasSuffix applies the HasSuffix predicate on the "node_id" field.
func NodeIDHasSuffix(v string) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldHasSuffix(FieldNodeID, v))
}

// NodeIDIsNil applies the IsNil predicate on the "node_id" field.
func NodeIDIsNil() predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldIsNull(FieldNodeID))
}

// NodeIDNotNil applies the NotNil predicate on the "node_id" field.
func NodeIDNotNil() predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldNotNull(FieldNodeID))
}

// NodeIDEqualFold applies the EqualFold predicate on the "node_id" field.
func NodeIDEqualFold(v string) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldEqualFold(FieldNodeID, v))
}

// NodeIDContainsFold applies the ContainsFold predicate on the "node_id" field.
func NodeIDContainsFold(v string) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldContainsFold(FieldNodeID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldContainsFold(FieldStatus, v))
}

// IsDefaultEQ applies the EQ predicate on the "is_default" field.
func IsDefaultEQ(v bool) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldEQ(FieldIsDefault, v))
}

// IsDefaultNEQ applies the NEQ predicate on the "is_default" field.
func IsDefaultNEQ(v bool) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldNEQ(FieldIsDefault, v))
}

// AllocationVersionEQ applies the EQ predicate on the "allocation_version" field.
func AllocationVersionEQ(v int64) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldEQ(FieldAllocationVersion, v))
}

// AllocationVersionNEQ applies the NEQ predicate on the "allocation_version" field.
func AllocationVersionNEQ(v int64) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldNEQ(FieldAllocationVersion, v))
}

// AllocationVersionIn applies the In predicate on the "allocation_version" field.
func AllocationVersionIn(vs ...int64) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldIn(FieldAllocationVersion, vs...))
}

// AllocationVersionNotIn applies the NotIn predicate on the "allocation_version" field.
func AllocationVersionNotIn(vs ...int64) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldNotIn(FieldAllocationVersion, vs...))
}

// AllocationVersionGT applies the GT predicate on the "allocation_version" field.
func AllocationVersionGT(v int64) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldGT(FieldAllocationVersion, v))
}

// AllocationVersionGTE applies the GTE predicate on the "allocation_version" field.
func AllocationVersionGTE(v int64) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldGTE(FieldAllocationVersion, v))
}

// AllocationVersionLT applies the LT predicate on the "allocation_version" field.
func AllocationVersionLT(v int64) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldLT(FieldAllocationVersion, v))
}

// AllocationVersionLTE applies the LTE predicate on the "allocation_version" field.
func AllocationVersionLTE(v int64) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.FieldLTE(FieldAllocationVersion, v))
}

// HasBindings applies the HasEdge predicate on the "bindings" edge.
func HasBindings() predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, BindingsTable, BindingsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBindingsWith applies the HasEdge predicate on the "bindings" edge with a given conditions (other predicates).
func HasBindingsWith(preds ...predicate.AccountEgressBinding) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(func(s *sql.Selector) {
		step := newBindingsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.IPv6EgressPool) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.IPv6EgressPool) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.IPv6EgressPool) predicate.IPv6EgressPool {
	return predicate.IPv6EgressPool(sql.NotPredicates(p))
}
